### ISSUE TITLE
Enabling basic auth causes Websocket error

### ISSUE THREAD

**Issue by svenger87** [iotaledger/hornet#1]
Enablig basic auth for the dashboard causes Websocket error.
Seems like some stats can´t be gathered when basic auth is activated.

![image](https://user-images.githubusercontent.com/35897839/70655867-498f0c00-1c59-11ea-8cfb-95df78286989.png)

**Comment by IoTMOD** [comment]
Addition: Tested with Chrome

**Comment by svenger87** [comment]
The issue seems to not have something to do with basic auth.

It seems to appear after a certain time when you leave the dashboard running.

**Comment by luca-moser** [comment]
If you're running your dashboard behind a proxy, make sure that the connection is kept alive via it.

**Comment by IoTMOD** [comment]
```
[ ERROR ] SPA: error while writing to web socket client xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxx:xxxx: write tcp [xxxx:xxx:xxx:xxxx::1]:8081->[xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxx:xxxx]:59344: i/o timeout
```
No proxy

**Comment by svenger87** [comment]
Issue no longer exists with 0.4 rc
