### ISSUE TITLE
Add ability for Hornet node to re-read config.json while running

### ISSUE THREAD

**Issue by centercirclesolutions** [iotaledger/hornet#101]
Simple but low priority request. Many daemons provide the ability to send a signal while running to reload their configuration files. While there are already means to make changes to the hornet node while running this might be an easy way to allow in-flight updates for features that have not been added to the API.

e.g. `kill -SIGHUP 1234`

**Comment by muXxer** [comment]
We will add this feature for the new `neighbors.json`, but not for the global `config.json`.

**Comment by centercirclesolutions** [comment]
Sounds good.

I can understand where changing profiles on the fly would be an issue.

Thanks MuXxer!
