### ISSUE TITLE
Wrong error when fetching utxo changes for a milestone that doesn't exist yet

### ISSUE THREAD

**Issue by samuel-rufi** [iotaledger/hornet#1027]
**Description**
When trying to fetch utxo changes for a milestone that doesn't exist yet the node will return an internal error.

**To Reproduce**
Request `/api/v1/milestones/23423423/utxo-changes`

**Expected behavior**
Instead of returning an internal error it should return a `404`.

**Environment information:**
Version: 0.6.0-alpha

**Comment by muXxer** [comment]
Fixed with #1028
