### ISSUE TITLE
Run my private tangle

### ISSUE THREAD

**Issue by YangXianqi** [iotaledger/hornet#1032]
When I use sudo COO_SEED="$YOURSEED" -u hornet hornet --cooBootstrap to run my private tangle, I met this situation,
UDYXTZBE9GZGPM9SSQV9LTZNDLJIZMPUVVXYXFYVBLIEUHLSEWFTKZZLXYRHHWVQV9MNNX9KZC9D9UZWZ != $My coordinator's address: configured coordinator address does not match database information
How to solve this problem. I create the private tangle according to https://docs.iota.org/docs/hornet/1.1/tutorials/set-up-a-private-tangle-hornet

**Comment by muXxer** [comment]
Like already answered by Dr. Electron in the discord server, don't use the almost deprecated stuff to setup your own tangle.
Use the new tutorial here https://hornet.docs.iota.org/tutorials/private_tangle.html
