### ISSUE TITLE
401 unauthorized add peers, runnig behind a proxy (nginx)

### ISSUE THREAD

**Issue by nuriel77** [iotaledger/hornet#1064]
**Describe the bug**
I am getting 401 unauthorized when trying to add peers on the dashboard.

I wonder if hornet dashboard was already tested behind a reverse-proxy such as nginx?

Looking at the config, I assume that all POST API calls should go to the 14265 port (API)?
While I connect to the dashboard on ip:8081 (it reverse proxies me to 127.0.0.1:8087).
Dashboard works fine.

What doesn't work is adding peers. The dashboard does a POST to my `ip:8081` (the dashboard's address) rather than to the restAPI port.

If my guess is right, there should also be an option to say what is the proxied address so the dashboard performs the post to the correct address to reach the restAPI. In my case, I have a reverse proxy for the restAPI too (at ip:14267).

If my assumption is right, would it make sense to add another field under bindAddress of restAPI to say what is the external address - that could tell the dashboard how to find the API.

```
    "bindAddress": "127.0.0.1:14265",
    "powEnabled": true,
    "powWorkerCount": 1,
    "limits": {
      "bodyLength": "1M",
      "maxResults": 1000
    }
  },
  "dashboard": {
    "bindAddress": "127.0.0.1:8087",
```

I might be completely off on the scenario, but maybe this makes sense after all.

**To Reproduce**
Run behind a reverse proxy (nginx)

**Expected behavior**
Be able to manage peers

**Environment information:**
 - OS: [e.g. Ubuntu 18.04]
 - RAM: [e.g. 4 GB]
 - Cores: [e.g. 4 Cores]
 - Type: [e.g. Raspberry Pi 3B+, VPS, ...]
 - Browser [e.g. chrome, safari] (e.g. for HORNET Dashboard issues)
 - HORNET version 1.0.1

**Additional context**
Add any other context about the problem here [e.g. HORNET logs, errors, screenshots]

**Comment by peterneutron** [comment]
I'am running a working Hornet 1.0.1 node behind an NGINX reverse proxy. Please check the following.

1. Port 14626 UDP is open
2. Port 15600 TCP is open
3. Port 14265 TCP is open
4. In your hornet config change bind address `"bindAddress": "127.0.0.1:14265",` to `"bindAddress": "0.0.0.0:14265",`
5. In your NGINX config create the following proxy pass directives

```
location /ws {
       proxy_pass http://127.0.0.1:8081/ws;
       proxy_set_header Host $host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_http_version 1.1;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "upgrade";
    }

    location / {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:8081;
        proxy_http_version 1.1;
	proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
    }

    location /health {
        proxy_pass http://localhost:14265/health;
    }

    location /api/v1 {
        proxy_pass http://localhost:14265/api/v1;
    }
```

Edit: I'am the Maintainer of the Arch AUR `hornet-git` package (builds from git) so everything above applies to this package.

**Comment by nuriel77** [comment]
@setBoolean thanks! I will give it a try. I see already I've missed this part:
```
    location /api/v1 {
        proxy_pass http://localhost:14265/api/v1;
    }
```

(By the way, there's probably no need to bind `"bindAddress": "0.0.0.0:14265"` because nginx is proxying to localhost, and 14265 can be kept listening locally only)

**Comment by peterneutron** [comment]
> (By the way, there's probably no need to bind "bindAddress": "0.0.0.0:14265" because nginx is proxying to localhost, and 14265 can be kept listening locally only)

Is this accurate though? If anything tries to remotely access your node directly on port 14265 it will receive an error because your node only offers port 14265 through http/https on ports 80/443.

Anyway I'am glad you solved your problem 🙂

**Comment by nuriel77** [comment]
> Is this accurate though? If anything tries to remotely access your node directly on port 14265 it will receive an error because your node only offers port 14265 through http/https on ports 80/443.

In previous version of hornet I've used haproxy in front of 14265 (API) in order to do TLS(HTTPS), rate limiting, whitelisting etc (serving the API on external port 14267).
But now I am thinking I can drop haproxy and just use the /api/v1 path via nginx and have rate limiting, tls termination etc.

**Comment by peterneutron** [comment]
Depends on whether some remote part insists on a direct connection to port 14265, which I honestly don't know. But yeah now you could do rate limiting etc. directly trough nginx.
