### ISSUE TITLE
Dashboard always switches from normal to "The node is offline" site and shows no peers

### ISSUE THREAD

**Issue by HankMoody089** [iotaledger/hornet#1065]
**Describe the bug**
When running the latest Mainnet version the Dashboard always switches from normal to "The node is offline" site and shows no peers on Safari, MacOS and iOS. Node is running and with Chrome Browser everything is fine and works.

**To Reproduce**
Setup Node with the official Tutorial on Ubuntu 20.04 VPS (Hetzner) and then go to the dashboard with latest Version of Safari.

**Expected behavior**
Stabile showing of the dashboard specs, as it was before in the latest versions. First time for me with this problem.

**Environment information:**
 - OS: Ubuntu 20.04
 - RAM: 4 GB
 - Cores: 2 Cores
 - Type: VPS
 - Browser Safari 14.1 on Mac, latest on iOS
 - HORNET version latest 1.0.1

[message-11.txt](https://github.com/gohornet/hornet/files/6400166/message-11.txt)

**Additional context**
Add any other context about the problem here [e.g. HORNET logs, errors, screenshots]

**Comment by muXxer** [comment]
Can you try to clear your browser cache?
Or try another browser?
Do you have another old tab of the dashboard opened maybe?

**Comment by HankMoody089** [comment]
- Deleting browser cache didn't fix it. Same on iOS
- As said upon, with Chrome browser it's working fine. Seems there is a safari problem.
- No other old tab of the dashboard is opened.
- This is how it looks like...(Video captured on iPhone, iOS)

**Comment by HankMoody089** [comment]
This is from Chrome... 
<img width="1405" alt="Bildschirmfoto 2021-04-30 um 08 50 01" src="https://user-images.githubusercontent.com/60474745/116658961-1f92d280-a991-11eb-9bba-a08691ff45dd.png">

**Comment by Travetown** [comment]
I'm pretty sure the cause lies in the depths of the reserve proxy configuration. I installed 2 nodes (1x with apt and once via SWARM, which actually also works via apt, but the reserve proxy is configured differently). With the 1st node access to the dashboard works, with the other I have the same error.
Unfortunately, I have no useful knowledge of the proxy configuration

**Comment by luca-moser** [comment]
Can't reproduce on a MacBook Air M1 in Safari.

**Comment by HankMoody089** [comment]
Ok... Just updated today to latest Big Sur (11.4) and iOS (14.6), but didn't fix the problem for me. Chrome on Mac still working perfect.

**Comment by luca-moser** [comment]
Do you experience the same if you access https://dashboard.chrysalis.lucamoser.io/ for example? Meaning, do the values not update after a while?

**Comment by HankMoody089** [comment]
Yours seems to work. Cannot test completely without login but the site stays like this and doesn't disappear like it's with my dashboard in the video...
![Bildschirmfoto 2021-05-25 um 12 04 11](https://user-images.githubusercontent.com/60474745/119479977-78b41300-bd51-11eb-83f7-7000ae3a8170.png)

**Comment by luca-moser** [comment]
You did not upload the video btw :)

**Comment by HankMoody089** [comment]
https://user-images.githubusercontent.com/60474745/119484662-861fcc00-bd56-11eb-86ae-33219a549fbb.MOV

**Comment by HankMoody089** [comment]
Deleted it because IP was shown. Thought you already watched it. 😅 Here again with domain...

**Comment by HankMoody089** [comment]
Same on MacOS and iOS

**Comment by admljhnsn** [comment]
not sure if it is related, but when i SSH into my dashboard from my iPhone using iSH, the same thing happens and the terminal says "channel x: chan_read_failed for istate 3" where x is an integer.

**Comment by HankMoody089** [comment]
I installed iOS 15 Beta now on my iPhone and iPadOS 15 Beta on my iPad. Hornet and Comnet Dashboard is working there, but now I got an issue with the old Dashboard used in Goshimmer. Strange. 😅 Node is up and running synced. 😉 ![image](https://user-images.githubusercontent.com/60474745/126074841-add82252-27e3-4540-877f-50ae611f1a78.jpeg)

**Comment by alexsporn** [comment]
A workaround was added in #1243
