### ISSUE TITLE
[Feature request] [Dashboard/Visualizer] Make maximum number of messages configurable.

### ISSUE THREAD

**Issue by peterneutron** [iotaledger/hornet#1066]
**Is your feature request related to a problem? Please describe.**
The current max. amount of messages displayed in the dashboard visualiser is hard capped at 5000 and is not user configurable. While I guess 5000 is a sane default for most hardware/browser configurations it should be up to the user to set this to any preferred value.

**Describe the solution you'd like**
Add an option to enter a custom max. amount of simultaneously displayed messages.

**Describe alternatives you've considered**
Continue sitting in front of a very small tangle.

**Additional context**
-

**Comment by muXxer** [comment]
Please open an issue in the node-dashboard repository :)
https://github.com/iotaledger/node-dashboard

**Comment by peterneutron** [comment]
> Please open an issue in the node-dashboard repository :)
> https://github.com/iotaledger/node-dashboard

Will do. But maybe you could help me out, I think I nailed is down a bit. Could you add me on Discord so I could send you a DM?

Ref: https://github.com/iotaledger/node-dashboard/issues/38
