### ISSUE TITLE
JWT, permitted routes and making the node public.

### ISSUE THREAD

**Issue by nuriel77** [iotaledger/hornet#1072]
**Is your feature request related to a problem? Please describe.**
Not sure whether this is a feature at this point, expected behavior or a bug.

**Context**
There are few issues here.
I think it is important to share what is being attempted first:

Many users want to have their nodes publicly available for Firefly, this requires TLS/HTTPS (done via a proxy e.g. nginx).
In addition, the users want to be able to manage things like peers via the dashboard.

I cannot configure nginx to restrict access to a route like `/api/v1/peers` (via e.g. auth basic) because that would prevent the dashboard's access to it.

One proposed idea was to enable JWT. However, I ran into some issues with it:

Dashboard cannot access API with JWT enabled
-----------------------------------------------------
Please note: this behavior was tested both with and without a proxy/nginx.
If JWT is enabled, the dashboard cannot work with the API any longer, I get the error:
`Failed to add peer: invalid jwt claims, error: code=401, message=invalid jwt claims`
I can access using e.g. curl only when setting to the JWT to the one from the Hornet log.

Expected behavior: when JWT is enabled, the dashboard should still have its full access to the API.

(By the way, I have 127.0.0.1 and ::1 whitelisted as in the original config.json)

Permitted Routes
-------------------
When enabling JWT, all the API's routes, even those in the `permittedRoutes` require the token.
But suppose I only want to require JWT for the non-permitted routes, I still want to let Firefly connect.
It seems to me that `permittedRoutes` should always be permitted, regardless of whether JWT is enabled or not.

**Extra info**
Using the docker hornet image version 1.0.1 on Ubuntu 20.04

Thank you.

**Comment by nuriel77** [comment]
I wanted to suggest an idea about the permitted routes issue, that if JWT is enabled: to add a boolean, something like `excludePermittedRoutesFromJWT`, if set to true, this would allow access to permittedRoutes even when JWT is enabled.

**Comment by muXxer** [comment]
I created a new tool for you in #1085 to create JWT tokens.

`./hornet tool jwt-api`

The correct config file and p2pstore must be loaded, otherwise the JWT is not valid.
