### ISSUE TITLE
Allow tools pwdhash to accept either stdin or ENV variable

### ISSUE THREAD

**Issue by nuriel77** [iotaledger/hornet#1073]
Consider tooling like hornet-playbook that help to automate various node management processes, the ability to generate the salt+password hash automatically would be very handy.

Consider the following example to best illustrate the idea:
```sh
$ read -s MYPASS
<user inputs the password>
$ echo $MYPASS
somepassword
$ docker run -it --rm -e PWDHASH="$MYPASS" --name test gohornet/hornet:1.0.1  tools pwdhash --from-env
Success!
Your hash: 1b855eec4980d645fcdbedfd4ad06cccd51a49ddb5426b96e524ae9344be9051
Your salt: 39a2bc364bf5c08d8f4a2fd2a60c4327b581830a02c665d270611e9e4de12bcb
```
Maybe the `--from-env` or any other arg is not really necessary if the PWDHASH environment variable is detected as defined.

This way, it is possible to wrap around this functionality and automate the user's salt+password hash with e.g. scripts etc.

**Comment by muXxer** [comment]
@no8ody will love it :D
yeah never thought about the env variable thing.
will have a look

**Comment by muXxer** [comment]
Added with #1085
