### ISSUE TITLE
Build from source - Indicated version of Hornet in dashboard

### ISSUE THREAD

**Issue by IkarusInDaHouse** [iotaledger/hornet#1074]
**Describe the bug**
It’s probably less a bug than an observation.
I built hornet from source by cloning the github repository: git clone https://github.com/gohornet/hornet.git && cd hornet

Then I used this script to compile it: build_hornet_rocksdb.sh

It compiles without errors, I could execute it and I guess hornet is going what it should do.

But if I do a “./hornet –v” to get the version of hornet, it shows the latest commit of the cloned repository not the version string.
In my case it shows “HORNET 2e4d5c2a”. But shouldn’t it show something like “HORNET 1.0.1 - 2e4d5c2a"?

**To Reproduce**
git clone https://github.com/gohornet/hornet.git && cd hornet
./scripts/build_hornet_rocksdb.sh
./hornet -v

**Expected behavior**
VersionString+CommitString as compiled version?

**Environment information:**
 - OS: kubuntu 20.04
 - HORNET version: clone latest version from github

**Additional context**

**Comment by muXxer** [comment]
This is on purpose. 
It's done in the script. :)

**Comment by IkarusInDaHouse** [comment]
Hi,
Yes the script pulls the latest Commit, that’s correct.
But according to the documentation: https://hornet.docs.iota.org/getting_started/installation_steps.html,
Section 2.3 / Build from source, it should give the Version AND the Commit.

Once it is compiled, then the executable file named hornet should be available in the current directory:
./hornet --version
Example of version:
HORNET 0.6.0-31ad46bb
    there is also short commit sha added to be sure what commit the given version is compiled against
