### ISSUE TITLE
revalidation fails

### ISSUE THREAD

**Issue by QNODE-CA** [iotaledger/hornet#1086]
**Describe the bug**
trying to repair corrupted database, I run hornet with --revalidate flag.  Node panicked with `panic: current confirmed milestone (68012) is newer than (67729)
`

**To Reproduce**
- run node with --revalidate flag
- node panics

**Expected behavior**
revalidation to complete and database repaired

**Environment information:**
 - OS:  Ubuntu 20.04.1
 - RAM:  16 GB
 - Cores:  6 Cores
 - Type:  ESXi VM
 - HORNET version 1.0.1 

**Additional context**

validator node had crashed for `panic: unable to query migrated funds from legacy node for receipt validation: API call failed: error message: milestone not found for wf-confirmation at 3716650;http status code: 404;` , corrupting the database

[revalidation fail.txt](https://github.com/gohornet/hornet/files/6437293/revalidation.fail.txt)

**Comment by muXxer** [comment]
Thx for the bug report. I will investigate.

**Comment by muXxer** [comment]
Fixed by #1096
