### ISSUE TITLE
Usage of p2pidentity (tool) unclear

### ISSUE THREAD

**Issue by MaKla89** [iotaledger/hornet#1089]
**Related Problem**
Me, as well as most of my neighbors did not fully understand what `hornet tools p2pidentity` does and documentation is slightly unclear about that. My p2p-store was somehow corrupted and I learned that - eventhough I could still backup my key-file from within that folder - I would need to create a new ID and inform all neighbors about that. I was somehow not clear about having to manually run `hornet tools p2pidentity` AND THEN also have to enter the tool's output into the config.json :) 

What we expected that tool to do:

- Generate a new random ID (including public and private key)
- Update the config.json with that new ID (since the tool prompts the warning if run from any place that does have a file called 'config.json')

What the tool actuall does:

- Spit out a warning if the tool is not run in a folder that does not include the config.json (eventhough it seems to not do anything with that file if provided)
- Generate a new random ID that is not saved or used anywhere (as far as I can see^^) unless the node operator does so manually in a second step

What the documentations says:

"The generated private key can then be injected to `identityPriavteKey`value in `config.json` file."

While I'm NOT saying that this is wrong, but it stil did not make me understand "well, doing that is a manual job on my side and if I don't add it to the config, the output I see will simply be discarded".

**Potential Solutions**

- EITHER make the documents a bit clearer about us needing to manually enter the result of that tool into the config.json (replace `key CAN be injected to config` with `key must be manually injected to config, otherwise nothing will happen` :D )
- OR add a short hint about this required step at the end of the tools output / print
- OR have that tool actually change the config.json (I see why this would not be ideal in some cases and it might be too much effort)

**Comment by QNODE-CA** [comment]
I agree with MaKla.  Perhaps a way to retrieve the private key would be useful, for people that have not inserted it in config.json, but thought that the equivalent info was just sitting in the /p2pstore/ folder?

**Comment by luca-moser** [comment]
I've made a PR with hopefully more clearer docs. In `./p2pstore` we store whatever `libp2p` persists for it to function (which is in a BadgerDB), which includes also the identity private key. We additionally also save a `key.pub` on our own in there, as it is the only way we can extract back out the identity when booting up the node. This is some kind of weird design with `libp2p` where you'd think that it would simply work by simply pointing it to an existing persisted store without having to separately store the public key. (I guess this was done so you can manage multiple peer identities with one store.)

> Spit out a warning if the tool is not run in a folder that does not include the config.json (eventhough it seems to not do anything with that file if provided)

This part might be confusing but it doesn't have anything to do with the tool, it is just a warning which will always occur in that case.

I've added 1) and 2) of your potential solutions; I think 3) changing the config.json might cause issue down the line.

@luca-yvr I've also added a tool `p2pidentityextract` which does exactly this.

https://github.com/gohornet/hornet/pull/1090

**Comment by MaKla89** [comment]
Perfect solution AND extremely fast, thank you :)

**Comment by QNODE-CA** [comment]
thank you!
