### ISSUE TITLE
panic: Ledger diff for milestone 1295604 does not sum up to zero

### ISSUE THREAD

**Issue by RandirVithren** [iotaledger/hornet#109]
**Describe the bug**
After restarting a Hornet that has been running for a week it panicked with a „Ledger diff does not sum up to zero“ error. 

**To Reproduce**
- start
- wait
- panic

**Expected behavior**
Don't panic

**Environment information:**
 - OS: Debian Buster with Armbian Linux 4.4.184-rockchip64
 - RAM: 4 GB
 - Cores: 4
 - Type: Pine Rock64
 - HORNET version 0.2.9

**Additional context**
[panic.txt](https://github.com/gohornet/hornet/files/4021135/panic.txt)

**Comment by muXxer** [comment]
I don't understand that "remove mainnetdb" step in between?

**Comment by RandirVithren** [comment]
Remove or delete the folder mainnetdb/ is obsolete. I have adjusted the description.

**Comment by muXxer** [comment]
But it has a totally different outcome. If you remove the DB, you start with a local snapshot. Which means your node starts syncing again.

**Comment by muXxer** [comment]
@RandirVithren you used a broken snapshot file. Snapshots from IRI are currently broken.
Please use this one or wait until IRI team fixed that.
https://dbfiles.iota.org/mainnet/hornet/2019-12-26_113404_UTC-export.gz.bin

Closing that issue for now
