### ISSUE TITLE
Dark theme as default

### ISSUE THREAD

**Issue by m4xe-de** [iotaledger/hornet#1091]
Describe the bug:
The dark theme is no longer displayed if you use another browser or delete the browser data.

To Reproduce:
- I have set the dark theme in the hornet dashboard under settings
- When I load hornet with deleted browser data or with another browser, it always opens in the light theme
- The same with the button in the menu bar

Expected behavior:
Dark theme as default on first load

Environment information:
 - OS: [Ubuntu 20.04.2 lts]
 - RAM: [8 GB]
 - Cores: [4 Cores]
 - Type: [Raspberry Pi 4]
 - Browser [Brave, Firefox]
 - HORNET version [1.0.1]

**Comment by muXxer** [comment]
The chosen theme is stored in your browser cache. If you delete it, or use another browser, you loose this information.
This is not a bug at all.

I will close that issue.
