### ISSUE TITLE
node panic: 'too many open files'

### ISSUE THREAD

**Issue by QNODE-CA** [iotaledger/hornet#1093]
**Describe the bug**
chrysalis validator node crashed (too many open files panic)

**To Reproduce**
- run chrysalis 1.0.1 node with default 1024 ulimit -n
- PANIC   Tangle  unable to confirm milestone due to receipt backup failure: unable to persist receipt onto disk: open receipts/3724371.114361.json: too many open files

**Expected behavior**
no panic

**Environment information:**
 - OS:  Ubuntu 20.04]
 - RAM:  16 GB
 - Cores:  8 vCores 
 - Type:  ESXi VM
 - HORNET version:  1.0.1

**Additional context**

while this is a validator node, and the error msg mentions a receipts backup failure, the open files error seems to be the cause of the crash (not receipt validation)
attaching console log at the time of the crash

[too-many-files-panic.txt](https://github.com/gohornet/hornet/files/6462621/too-many-files-panic.txt)

**Comment by muXxer** [comment]
The process is not able to open another file handle. You need to increase the ulimit.
This is not a bug as far as I see. Keep in mind the database engine opens more and more files, the more the database grows.

**Comment by Travetown** [comment]
@luca-yvr 


https://muhammadtriwibowo.medium.com/set-permanently-ulimit-n-open-files-in-ubuntu-4d61064429a
