### ISSUE TITLE
JSON option for cli tools output

### ISSUE THREAD

**Issue by nuriel77** [iotaledger/hornet#1095]
**Is your feature request related to a problem? Please describe.**
Not related to any problem.

**Describe the solution you'd like**

Would be handy to be able to request JSON output for cli tools commands, e.g.:

```
hornet tools p2pidentity --output json
```
Or (once it accepts password through ENV variable):
```
hornet tools pwdhash --output json
```
(or argument could just be `--json` if there's no plan/need to support other types in the future)

**Describe alternatives you've considered**
Currently parsing output via bash / sed / awk etc, but that is inconsistent and there's a chance output may change in the future  breaking tools that rely on it.

**Comment by muXxer** [comment]
https://media.giphy.com/media/eaECZB7V6GACc/giphy.gif

**Comment by nuriel77** [comment]
> https://media.giphy.com/media/eaECZB7V6GACc/giphy.gif

hahaha, no rush about this one @muXxer its just a nice-to-have ;)
