### ISSUE TITLE
Can't start hornet

### ISSUE THREAD

**Issue by adertask** [iotaledger/hornet#1098]
Hi,

this night hornet stopped running. Maybe db was full.
I delete maindb and snapshot folder and tried to restart. But hornet is not starting.
The config wasn't changed so I do not really understand the problem.

Got this error:

root@xxx:/var/lib/hornet# service hornet start
root@xxx:/var/lib/hornet# journalctl -fu hornet
-- Logs begin at Sat 2021-05-15 16:17:19 CEST. --
May 17 13:07:49 xxx hornet[5979]: github.com/gohornet/hornet/pkg/node.(*Node).init(0xc0006b9f10)
May 17 13:07:49 xxx hornet[5979]:         /__w/hornet/hornet/pkg/node/node.go:185 +0x77e
May 17 13:07:49 xxx hornet[5979]: github.com/gohornet/hornet/pkg/node.New(0xc00063ff60, 0x3, 0x3, 0x1d3ba40)
May 17 13:07:49 xxx hornet[5979]:         /__w/hornet/hornet/pkg/node/node.go:43 +0x20f
May 17 13:07:49 xxx hornet[5979]: github.com/gohornet/hornet/pkg/node.Run(0xc00063ff60, 0x3, 0x3, 0xc00020e3a0)
May 17 13:07:49 xxx hornet[5979]:         /__w/hornet/hornet/pkg/node/node.go:62 +0x3f
May 17 13:07:49 xxx hornet[5979]: main.main()
May 17 13:07:49 xxx hornet[5979]:         /__w/hornet/hornet/main.go:33 +0x334
May 17 13:07:49 xxx systemd[1]: hornet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 17 13:07:49 xxx systemd[1]: hornet.service: Failed with result 'exit-code'.
May 17 13:07:50 xxx systemd[1]: hornet.service: Scheduled restart job, restart counter is at 3.
May 17 13:07:50 xxx systemd[1]: Stopped HORNET.
May 17 13:07:50 xxx systemd[1]: Started HORNET.
May 17 13:07:50 xxx hornet[6004]: Parameters loaded:
May 17 13:07:50 xxx hornet[6004]:  {

after 5 times it stopped ..

Any ideas how I can solve that? I'm open to have a remote session.

Thanks for your support in advance.

Cheers
Mario

PS:
OS: Linux
Install: manually
Version 1.0.1

**Comment by muXxer** [comment]
Can you provide more lines, because that is not the full error message.

`journalctl -fu hornet -n 300`

**Comment by adertask** [comment]
Hi muXxer,

na klar / of course.

root@v42709:/var/lib/hornet# journalctl -fu hornet -n 300
-- Logs begin at Sat 2021-05-15 16:17:19 CEST. --
May 17 13:07:52 xxx systemd[1]: Started HORNET.
May 17 13:07:52 xxx hornet[6031]: Parameters loaded:
May 17 13:07:52 xxx hornet[6031]:  {
May 17 13:07:52 xxx hornet[6031]:   "coordinator": {
May 17 13:07:52 xxx hornet[6031]:     "checkpoints": {
May 17 13:07:52 xxx hornet[6031]:       "maxtrackedmessages": 10000
May 17 13:07:52 xxx hornet[6031]:     },
May 17 13:07:52 xxx hornet[6031]:     "interval": "10s",
May 17 13:07:52 xxx hornet[6031]:     "powworkercount": 0,
May 17 13:07:52 xxx hornet[6031]:     "quorum": {
May 17 13:07:52 xxx hornet[6031]:       "enabled": false,
May 17 13:07:52 xxx hornet[6031]:       "timeout": "2s"
May 17 13:07:52 xxx hornet[6031]:     },
May 17 13:07:52 xxx hornet[6031]:     "signing": {
May 17 13:07:52 xxx hornet[6031]:       "provider": "local",
May 17 13:07:52 xxx hornet[6031]:       "remoteaddress": "localhost:12345"
May 17 13:07:52 xxx hornet[6031]:     },
May 17 13:07:52 xxx hornet[6031]:     "statefilepath": "coordinator.state",
May 17 13:07:52 xxx hornet[6031]:     "tipsel": {
May 17 13:07:52 xxx hornet[6031]:       "heaviestbranchselectiontimeout": "100ms",
May 17 13:07:52 xxx hornet[6031]:       "maxheaviestbranchtipspercheckpoint": 10,
May 17 13:07:52 xxx hornet[6031]:       "minheaviestbranchunreferencedmessagesthreshold": 20,
May 17 13:07:52 xxx hornet[6031]:       "randomtipspercheckpoint": 3
May 17 13:07:52 xxx hornet[6031]:     }
May 17 13:07:52 xxx hornet[6031]:   },
May 17 13:07:52 xxx hornet[6031]:   "dashboard": {
May 17 13:07:52 xxx hornet[6031]:     "auth": {
May 17 13:07:52 xxx hornet[6031]:       "sessiontimeout": "72h",
May 17 13:07:52 xxx hornet[6031]:       "username": "hariotNode"
May 17 13:07:52 xxx hornet[6031]:     },
May 17 13:07:52 xxx hornet[6031]:     "bindaddress": "localhost:8081",
May 17 13:07:52 xxx hornet[6031]:     "dev": false
May 17 13:07:52 xxx hornet[6031]:   },
May 17 13:07:52 xxx hornet[6031]:   "db": {
May 17 13:07:52 xxx hornet[6031]:     "autorevalidation": false,
May 17 13:07:52 xxx hornet[6031]:     "debug": false,
May 17 13:07:52 xxx hornet[6031]:     "engine": "rocksdb",
May 17 13:07:52 xxx hornet[6031]:     "path": "mainnetdb"
May 17 13:07:52 xxx hornet[6031]:   },
May 17 13:07:52 xxx hornet[6031]:   "debug": {
May 17 13:07:52 xxx hornet[6031]:     "whiteflagparentssolidtimeout": "2s"
May 17 13:07:52 xxx hornet[6031]:   },
May 17 13:07:52 xxx hornet[6031]:   "gossip": {
May 17 13:07:52 xxx hornet[6031]:     "streamreadtimeout": "1m0s",
May 17 13:07:52 xxx hornet[6031]:     "streamwritetimeout": "10s"
May 17 13:07:52 xxx hornet[6031]:   },
May 17 13:07:52 xxx hornet[6031]:   "logger": {
May 17 13:07:52 xxx hornet[6031]:     "disablecaller": true,
May 17 13:07:52 xxx hornet[6031]:     "encoding": "console",
May 17 13:07:52 xxx hornet[6031]:     "level": "info",
May 17 13:07:52 xxx hornet[6031]:     "outputpaths": [
May 17 13:07:52 xxx hornet[6031]:       "stdout"
May 17 13:07:52 xxx hornet[6031]:     ]
May 17 13:07:52 xxx hornet[6031]:   },
May 17 13:07:52 xxx hornet[6031]:   "migrator": {
May 17 13:07:52 xxx hornet[6031]:     "querycooldownperiod": "5s",
May 17 13:07:52 xxx hornet[6031]:     "receiptmaxentries": 110,
May 17 13:07:52 xxx hornet[6031]:     "statefilepath": "migrator.state"
May 17 13:07:52 xxx hornet[6031]:   },
May 17 13:07:52 xxx hornet[6031]:   "mqtt": {
May 17 13:07:52 xxx hornet[6031]:     "bindaddress": "localhost:1883",
May 17 13:07:52 xxx hornet[6031]:     "workercount": 100,
May 17 13:07:52 xxx hornet[6031]:     "wsport": 1888
May 17 13:07:52 xxx hornet[6031]:   },
May 17 13:07:52 xxx hornet[6031]:   "node": {
May 17 13:07:52 xxx hornet[6031]:     "alias": "HORNET node",
May 17 13:07:52 xxx hornet[6031]:     "disableplugins": [],
May 17 13:07:52 xxx hornet[6031]:     "enableplugins": [
May 17 13:07:52 xxx hornet[6031]:       "Spammer"
May 17 13:07:52 xxx hornet[6031]:     ],
May 17 13:07:52 xxx hornet[6031]:     "profile": "auto"
May 17 13:07:52 xxx hornet[6031]:   },
May 17 13:07:52 xxx hornet[6031]:   "p2p": {
May 17 13:07:52 xxx hornet[6031]:     "bindmultiaddresses": [
May 17 13:07:52 xxx hornet[6031]:       "/ip4/0.0.0.0/tcp/15600"
May 17 13:07:52 xxx hornet[6031]:     ],
May 17 13:07:52 xxx hornet[6031]:     "connectionmanager": {
May 17 13:07:52 xxx hornet[6031]:       "highwatermark": 10,
May 17 13:07:52 xxx hornet[6031]:       "lowwatermark": 5
May 17 13:07:52 xxx hornet[6031]:     },
May 17 13:07:52 xxx hornet[6031]:     "gossipunknownpeerslimit": 4,
May 17 13:07:52 xxx hornet[6031]:     "identityprivatekey": "",
May 17 13:07:52 xxx hornet[6031]:     "peerstore": {
May 17 13:07:52 xxx hornet[6031]:       "path": "./p2pstore"
May 17 13:07:52 xxx hornet[6031]:     },
May 17 13:07:52 xxx hornet[6031]:     "reconnectinterval": "30s"
May 17 13:07:52 xxx hornet[6031]:   },
May 17 13:07:52 xxx hornet[6031]:   "p2pdisc": {
May 17 13:07:52 xxx hornet[6031]:     "advertiseinterval": "30s",
May 17 13:07:52 xxx hornet[6031]:     "maxdiscoveredpeerconns": 4,
May 17 13:07:52 xxx hornet[6031]:     "rendezvouspoint": "between-two-vertices",
May 17 13:07:52 xxx hornet[6031]:     "routingtablerefreshperiod": "60s"
May 17 13:07:52 xxx hornet[6031]:   },
May 17 13:07:52 xxx hornet[6031]:   "pow": {
May 17 13:07:52 xxx hornet[6031]:     "refreshtipsinterval": "5s"
May 17 13:07:52 xxx hornet[6031]:   },
May 17 13:07:52 xxx hornet[6031]:   "profiling": {
May 17 13:07:52 xxx hornet[6031]:     "bindaddress": "localhost:6060"
May 17 13:07:52 xxx hornet[6031]:   },
May 17 13:07:52 xxx hornet[6031]:   "prometheus": {
May 17 13:07:52 xxx hornet[6031]:     "bindaddress": "localhost:9311",
May 17 13:07:52 xxx hornet[6031]:     "cachesmetrics": true,
May 17 13:07:52 xxx hornet[6031]:     "coordinatormetrics": true,
May 17 13:07:52 xxx hornet[6031]:     "databasemetrics": true,
May 17 13:07:52 xxx hornet[6031]:     "debugmetrics": false,
May 17 13:07:52 xxx hornet[6031]:     "fileservicediscovery": {
May 17 13:07:52 xxx hornet[6031]:       "enabled": false,
May 17 13:07:52 xxx hornet[6031]:       "path": "target.json",
May 17 13:07:52 xxx hornet[6031]:       "target": "localhost:9311"
May 17 13:07:52 xxx hornet[6031]:     },
May 17 13:07:52 xxx hornet[6031]:     "gometrics": false,
May 17 13:07:52 xxx hornet[6031]:     "gossipmetrics": true,
May 17 13:07:52 xxx hornet[6031]:     "migrationmetrics": true,
May 17 13:07:52 xxx hornet[6031]:     "nodemetrics": true,
May 17 13:07:52 xxx hornet[6031]:     "processmetrics": false,
May 17 13:07:52 xxx hornet[6031]:     "promhttpmetrics": false,
May 17 13:07:52 xxx hornet[6031]:     "restapimetrics": true
May 17 13:07:52 xxx hornet[6031]:   },
May 17 13:07:52 xxx hornet[6031]:   "protocol": {
May 17 13:07:52 xxx hornet[6031]:     "bech32hrp": "iota",
May 17 13:07:52 xxx hornet[6031]:     "milestonepublickeycount": 2,
May 17 13:07:52 xxx hornet[6031]:     "minpowscore": 4000,
May 17 13:07:52 xxx hornet[6031]:     "networkid": "chrysalis-mainnet",
May 17 13:07:52 xxx hornet[6031]:     "publickeyranges": [
May 17 13:07:52 xxx hornet[6031]:       {
May 17 13:07:52 xxx hornet[6031]:         "end": 777600,
May 17 13:07:52 xxx hornet[6031]:         "key": "a9b46fe743df783dedd00c954612428b34241f5913cf249d75bed3aafd65e4cd",
May 17 13:07:52 xxx hornet[6031]:         "start": 0
May 17 13:07:52 xxx hornet[6031]:       },
May 17 13:07:52 xxx hornet[6031]:       {
May 17 13:07:52 xxx hornet[6031]:         "end": 1555200,
May 17 13:07:52 xxx hornet[6031]:         "key": "365fb85e7568b9b32f7359d6cbafa9814472ad0ecbad32d77beaf5dd9e84c6ba",
May 17 13:07:52 xxx hornet[6031]:         "start": 0
May 17 13:07:52 xxx hornet[6031]:       }
May 17 13:07:52 xxx hornet[6031]:     ]
May 17 13:07:52 xxx hornet[6031]:   },
May 17 13:07:52 xxx hornet[6031]:   "pruning": {
May 17 13:07:52 xxx hornet[6031]:     "delay": 60480,
May 17 13:07:52 xxx hornet[6031]:     "enabled": true,
May 17 13:07:52 xxx hornet[6031]:     "prunereceipts": false
May 17 13:07:52 xxx hornet[6031]:   },
May 17 13:07:52 xxx hornet[6031]:   "receipts": {
May 17 13:07:52 xxx hornet[6031]:     "backup": {
May 17 13:07:52 xxx hornet[6031]:       "enabled": false,
May 17 13:07:52 xxx hornet[6031]:       "folder": "receipts"
May 17 13:07:52 xxx hornet[6031]:     },
May 17 13:07:52 xxx hornet[6031]:     "validator": {
May 17 13:07:52 xxx hornet[6031]:       "api": {
May 17 13:07:52 xxx hornet[6031]:         "address": "http://localhost:14266",
May 17 13:07:52 xxx hornet[6031]:         "timeout": "5s"
May 17 13:07:52 xxx hornet[6031]:       },
May 17 13:07:52 xxx hornet[6031]:       "coordinator": {
May 17 13:07:52 xxx hornet[6031]:         "address": "UDYXTZBE9GZGPM9SSQV9LTZNDLJIZMPUVVXYXFYVBLIEUHLSEWFTKZZLXYRHHWVQV9MNNX9KZC9D9UZWZ",
May 17 13:07:52 xxx hornet[6031]:         "merkletreedepth": 24
May 17 13:07:52 xxx hornet[6031]:       },
May 17 13:07:52 xxx hornet[6031]:       "ignoresofterrors": false,
May 17 13:07:52 xxx hornet[6031]:       "validate": false
May 17 13:07:52 xxx hornet[6031]:     }
May 17 13:07:52 xxx hornet[6031]:   },
May 17 13:07:52 xxx hornet[6031]:   "requests": {
May 17 13:07:52 xxx hornet[6031]:     "discardolderthan": "15s",
May 17 13:07:52 xxx hornet[6031]:     "pendingreenqueueinterval": "5s"
May 17 13:07:52 xxx hornet[6031]:   },
May 17 13:07:52 xxx hornet[6031]:   "restapi": {
May 17 13:07:52 xxx hornet[6031]:     "bindaddress": "0.0.0.0:14265",
May 17 13:07:52 xxx hornet[6031]:     "excludehealthcheckfromauth": false,
May 17 13:07:52 xxx hornet[6031]:     "jwtauth": {
May 17 13:07:52 xxx hornet[6031]:       "enabled": false,
May 17 13:07:52 xxx hornet[6031]:       "salt": "HORNET"
May 17 13:07:52 xxx hornet[6031]:     },
May 17 13:07:52 xxx hornet[6031]:     "limits": {
May 17 13:07:52 xxx hornet[6031]:       "bodylength": "1M",
May 17 13:07:52 xxx hornet[6031]:       "maxresults": 1000
May 17 13:07:52 xxx hornet[6031]:     },
May 17 13:07:52 xxx hornet[6031]:     "permittedroutes": [
May 17 13:07:52 xxx hornet[6031]:       "/health",
May 17 13:07:52 xxx hornet[6031]:       "/mqtt",
May 17 13:07:52 xxx hornet[6031]:       "/api/v1/info",
May 17 13:07:52 xxx hornet[6031]:       "/api/v1/tips",
May 17 13:07:52 xxx hornet[6031]:       "/api/v1/messages/:messageID",
May 17 13:07:52 xxx hornet[6031]:       "/api/v1/messages/:messageID/metadata",
May 17 13:07:52 xxx hornet[6031]:       "/api/v1/messages/:messageID/raw",
May 17 13:07:52 xxx hornet[6031]:       "/api/v1/messages/:messageID/children",
May 17 13:07:52 xxx hornet[6031]:       "/api/v1/messages",
May 17 13:07:52 xxx hornet[6031]:       "/api/v1/transactions/:transactionID/included-message",
May 17 13:07:52 xxx hornet[6031]:       "/api/v1/milestones/:milestoneIndex",
May 17 13:07:52 xxx hornet[6031]:       "/api/v1/milestones/:milestoneIndex/utxo-changes",
May 17 13:07:52 xxx hornet[6031]:       "/api/v1/outputs/:outputID",
May 17 13:07:52 xxx hornet[6031]:       "/api/v1/addresses/:address",
May 17 13:07:52 xxx hornet[6031]:       "/api/v1/addresses/:address/outputs",
May 17 13:07:52 xxx hornet[6031]:       "/api/v1/addresses/ed25519/:address",
May 17 13:07:52 xxx hornet[6031]:       "/api/v1/addresses/ed25519/:address/outputs",
May 17 13:07:52 xxx hornet[6031]:       "/api/v1/treasury"
May 17 13:07:52 xxx hornet[6031]:     ],
May 17 13:07:52 xxx hornet[6031]:     "powenabled": true,
May 17 13:07:52 xxx hornet[6031]:     "powworkercount": 1,
May 17 13:07:52 xxx hornet[6031]:     "whitelistedaddresses": [
May 17 13:07:52 xxx hornet[6031]:       "127.0.0.1",
May 17 13:07:52 xxx hornet[6031]:       "::1"
May 17 13:07:52 xxx hornet[6031]:     ]
May 17 13:07:52 xxx hornet[6031]:   },
May 17 13:07:52 xxx hornet[6031]:   "snapshots": {
May 17 13:07:52 xxx hornet[6031]:     "deltapath": "snapshots/mainnet/delta_snapshot.bin",
May 17 13:07:52 xxx hornet[6031]:     "deltasizethresholdpercentage": 50,
May 17 13:07:52 xxx hornet[6031]:     "depth": 50,
May 17 13:07:52 xxx hornet[6031]:     "downloadurls": [
May 17 13:07:52 xxx hornet[6031]:       {
May 17 13:07:52 xxx hornet[6031]:         "delta": "https://chrysalis-dbfiles.iota.org/snapshots/hornet/latest-delta_snapshot.bin",
May 17 13:07:52 xxx hornet[6031]:         "full": "https://chrysalis-dbfiles.iota.org/snapshots/hornet/latest-full_snapshot.bin"
May 17 13:07:52 xxx hornet[6031]:       }
May 17 13:07:52 xxx hornet[6031]:     ],
May 17 13:07:52 xxx hornet[6031]:     "fullpath": "snapshots/mainnet/full_snapshot.bin",
May 17 13:07:52 xxx hornet[6031]:     "interval": 200
May 17 13:07:52 xxx hornet[6031]:   },
May 17 13:07:52 xxx hornet[6031]:   "spammer": {
May 17 13:07:52 xxx hornet[6031]:     "autostart": false,
May 17 13:07:52 xxx hornet[6031]:     "cpumaxusage": 0.8,
May 17 13:07:52 xxx hornet[6031]:     "index": "HORNET Spammer",
May 17 13:07:52 xxx hornet[6031]:     "indexsemilazy": "HORNET Spammer Semi-Lazy",
May 17 13:07:52 xxx hornet[6031]:     "message": "IOTA - A new dawn",
May 17 13:07:52 xxx hornet[6031]:     "mpsratelimit": 5,
May 17 13:07:52 xxx hornet[6031]:     "workers": 0
May 17 13:07:52 xxx hornet[6031]:   },
May 17 13:07:52 xxx hornet[6031]:   "tangle": {
May 17 13:07:52 xxx hornet[6031]:     "milestonetimeout": "30s"
May 17 13:07:52 xxx hornet[6031]:   },
May 17 13:07:52 xxx hornet[6031]:   "tipsel": {
May 17 13:07:52 xxx hornet[6031]:     "belowmaxdepth": 15,
May 17 13:07:52 xxx hornet[6031]:     "maxdeltamsgoldestconerootindextocmi": 13,
May 17 13:07:52 xxx hornet[6031]:     "maxdeltamsgyoungestconerootindextocmi": 8,
May 17 13:07:52 xxx hornet[6031]:     "nonlazy": {
May 17 13:07:52 xxx hornet[6031]:       "maxchildren": 30,
May 17 13:07:52 xxx hornet[6031]:       "maxreferencedtipage": "3s",
May 17 13:07:52 xxx hornet[6031]:       "retentionrulestipslimit": 100,
May 17 13:07:52 xxx hornet[6031]:       "spammertipsthreshold": 0
May 17 13:07:52 xxx hornet[6031]:     },
May 17 13:07:52 xxx hornet[6031]:     "semilazy": {
May 17 13:07:52 xxx hornet[6031]:       "maxchildren": 2,
May 17 13:07:52 xxx hornet[6031]:       "maxreferencedtipage": "3s",
May 17 13:07:52 xxx hornet[6031]:       "retentionrulestipslimit": 20,
May 17 13:07:52 xxx hornet[6031]:       "spammertipsthreshold": 30
May 17 13:07:52 xxx hornet[6031]:     }
May 17 13:07:52 xxx hornet[6031]:   },
May 17 13:07:52 xxx hornet[6031]:   "warpsync": {
May 17 13:07:52 xxx hornet[6031]:     "advancementrange": 150
May 17 13:07:52 xxx hornet[6031]:   }
May 17 13:07:52 xxx hornet[6031]: }
May 17 13:07:52 xxx hornet[6031]: The following plugins are enabled: Spammerpanic: unable to initialize data store for peer store: Value log truncate required to run DB. This might result in data loss
May 17 13:07:52 xxx hornet[6031]: goroutine 1 [running]:
May 17 13:07:52 xxx hornet[6031]: github.com/gohornet/hornet/core/p2p.provide.func1(0x0, 0x0, 0xc000010410, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
May 17 13:07:52 xxx hornet[6031]:         /__w/hornet/hornet/core/p2p/core.go:99 +0x8d1
May 17 13:07:52 xxx hornet[6031]: reflect.Value.call(0x1c9e1c0, 0x2515c18, 0x13, 0x1f1b6ff, 0x4, 0xc0007a6468, 0x1, 0x1, 0x30, 0x7f77dd921108, ...)
May 17 13:07:52 xxx hornet[6031]:         /usr/local/go/src/reflect/value.go:476 +0x8e7
May 17 13:07:52 xxx hornet[6031]: reflect.Value.Call(0x1c9e1c0, 0x2515c18, 0x13, 0xc0007a6468, 0x1, 0x1, 0x9c, 0x3, 0xc0006af200)
May 17 13:07:52 xxx hornet[6031]:         /usr/local/go/src/reflect/value.go:337 +0xb9
May 17 13:07:52 xxx hornet[6031]: go.uber.org/dig.defaultInvoker(0x1c9e1c0, 0x2515c18, 0x13, 0xc0007a6468, 0x1, 0x1, 0xc0005dd9a0, 0xc0007a6468, 0x1)
May 17 13:07:52 xxx hornet[6031]:         /github/home/go/pkg/mod/go.uber.org/dig@v1.10.0/dig.go:284 +0x65
May 17 13:07:52 xxx hornet[6031]: go.uber.org/dig.(*node).Call(0xc0006c1400, 0x26d8578, 0xc0005dd9a0, 0x26e5248, 0x1e050e0)
May 17 13:07:52 xxx hornet[6031]:         /github/home/go/pkg/mod/go.uber.org/dig@v1.10.0/dig.go:710 +0x27b
May 17 13:07:52 xxx hornet[6031]: go.uber.org/dig.paramSingle.Build(0x0, 0x0, 0x0, 0x26e5248, 0x1e050e0, 0x26d8578, 0xc0005dd9a0, 0x28, 0x1daa2a0, 0x1, ...)
May 17 13:07:52 xxx hornet[6031]:         /github/home/go/pkg/mod/go.uber.org/dig@v1.10.0/param.go:245 +0x2df
May 17 13:07:52 xxx hornet[6031]: go.uber.org/dig.paramObjectField.Build(...)
May 17 13:07:52 xxx hornet[6031]:         /github/home/go/pkg/mod/go.uber.org/dig@v1.10.0/param.go:384
May 17 13:07:52 xxx hornet[6031]: go.uber.org/dig.paramObject.Build(0x26e5248, 0x1daa2a0, 0xc000703810, 0x2, 0x2, 0x26d8578, 0xc0005dd9a0, 0xc0007a6420, 0x57d372, 0xc00005c800, ...)
May 17 13:07:52 xxx hornet[6031]:         /github/home/go/pkg/mod/go.uber.org/dig@v1.10.0/param.go:311 +0x152
May 17 13:07:52 xxx hornet[6031]: go.uber.org/dig.paramList.BuildList(0x26e5248, 0x1c771c0, 0xc00078ea00, 0x1, 0x1, 0x26d8578, 0xc0005dd9a0, 0xc0006af638, 0x5c090c, 0x10, ...)
May 17 13:07:52 xxx hornet[6031]:         /github/home/go/pkg/mod/go.uber.org/dig@v1.10.0/param.go:201 +0xb8
May 17 13:07:52 xxx hornet[6031]: go.uber.org/dig.(*node).Call(0xc0006c14a0, 0x26d8578, 0xc0005dd9a0, 0x26e5248, 0x1eda700)
May 17 13:07:52 xxx hornet[6031]:         /github/home/go/pkg/mod/go.uber.org/dig@v1.10.0/dig.go:701 +0x105
May 17 13:07:52 xxx hornet[6031]: go.uber.org/dig.paramSingle.Build(0x0, 0x0, 0x0, 0x26e5248, 0x1eda700, 0x26d8578, 0xc0005dd9a0, 0x40, 0x1e2ec60, 0xc0006af801, ...)
May 17 13:07:52 xxx hornet[6031]:         /github/home/go/pkg/mod/go.uber.org/dig@v1.10.0/param.go:245 +0x2df
May 17 13:07:52 xxx hornet[6031]: go.uber.org/dig.paramObjectField.Build(...)
May 17 13:07:52 xxx hornet[6031]:         /github/home/go/pkg/mod/go.uber.org/dig@v1.10.0/param.go:384
May 17 13:07:52 xxx hornet[6031]: go.uber.org/dig.paramObject.Build(0x26e5248, 0x1e2ec60, 0xc0001fa140, 0x5, 0x8, 0x26d8578, 0xc0005dd9a0, 0xc0007a63d8, 0x57d372, 0xc00005c800, ...)
May 17 13:07:52 xxx hornet[6031]:         /github/home/go/pkg/mod/go.uber.org/dig@v1.10.0/param.go:311 +0x152
May 17 13:07:52 xxx hornet[6031]: go.uber.org/dig.paramList.BuildList(0x26e5248, 0x1c56740, 0xc00078e850, 0x1, 0x1, 0x26d8578, 0xc0005dd9a0, 0x0, 0x0, 0x1, ...)
May 17 13:07:52 xxx hornet[6031]:         /github/home/go/pkg/mod/go.uber.org/dig@v1.10.0/param.go:201 +0xb8
May 17 13:07:52 xxx hornet[6031]: go.uber.org/dig.(*Container).Invoke(0xc0005dd9a0, 0x1c56740, 0x2515c10, 0x0, 0x0, 0x0, 0x0, 0x0)
May 17 13:07:52 xxx hornet[6031]:         /github/home/go/pkg/mod/go.uber.org/dig@v1.10.0/dig.go:432 +0x2cb
May 17 13:07:52 xxx hornet[6031]: github.com/gohornet/hornet/pkg/node.(*Node).init.func7(0xc00007f860, 0x1)
May 17 13:07:52 xxx hornet[6031]:         /__w/hornet/hornet/pkg/node/node.go:187 +0x6e
May 17 13:07:52 xxx hornet[6031]: github.com/gohornet/hornet/pkg/node.forEachCorePlugin(0xc00001ff80, 0x9, 0x10, 0xc0031dfd78)
May 17 13:07:52 xxx hornet[6031]:         /__w/hornet/hornet/pkg/node/node.go:320 +0x51
May 17 13:07:52 xxx hornet[6031]: github.com/gohornet/hornet/pkg/node.(*Node).ForEachCorePlugin(...)
May 17 13:07:52 xxx hornet[6031]:         /__w/hornet/hornet/pkg/node/node.go:328
May 17 13:07:52 xxx hornet[6031]: github.com/gohornet/hornet/pkg/node.(*Node).init(0xc0006bbf80)
May 17 13:07:52 xxx hornet[6031]:         /__w/hornet/hornet/pkg/node/node.go:185 +0x77e
May 17 13:07:52 xxx hornet[6031]: github.com/gohornet/hornet/pkg/node.New(0xc0006aff60, 0x3, 0x3, 0x1d3ba40)
May 17 13:07:52 xxx hornet[6031]:         /__w/hornet/hornet/pkg/node/node.go:43 +0x20f
May 17 13:07:52 xxx hornet[6031]: github.com/gohornet/hornet/pkg/node.Run(0xc0006aff60, 0x3, 0x3, 0xc0002d03a0)
May 17 13:07:52 xxx hornet[6031]:         /__w/hornet/hornet/pkg/node/node.go:62 +0x3f
May 17 13:07:52 xxx hornet[6031]: main.main()
May 17 13:07:52 xxx hornet[6031]:         /__w/hornet/hornet/main.go:33 +0x334
May 17 13:07:52 xxx systemd[1]: hornet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 17 13:07:52 xxx systemd[1]: hornet.service: Failed with result 'exit-code'.
May 17 13:07:53 xxx systemd[1]: hornet.service: Scheduled restart job, restart counter is at 5.
May 17 13:07:53 xxx systemd[1]: Stopped HORNET.
May 17 13:07:53 xxx systemd[1]: hornet.service: Start request repeated too quickly.
May 17 13:07:53 xxx systemd[1]: hornet.service: Failed with result 'exit-code'.
May 17 13:07:53 xxx systemd[1]: Failed to start HORNET.


Cheers,
Mario

**Comment by muXxer** [comment]
Delete your p2pstore folder. The internal database of the peer store was corrupted by the crash.
You will loose your p2p identity, so you have to exchange the new id with all your neighbors.

To prevent loosing your ID next time this happens again, run `./hornet tool p2pidentity` now and
and enter the p2p private key in the config under `p2p.identityPrivateKey`.
