### ISSUE TITLE
Obfuscate sensitive data in hornet's log output

### ISSUE THREAD

**Issue by nuriel77** [iotaledger/hornet#1099]
**Is your feature request related to a problem? Please describe.**
Users are likely to share their hornet logs with the community to get help on issues they encounter.

I think most users are not aware that the output can contain sensitive data, for example:
```
"identityprivatekey": "*****"
```
Having this obfuscated minimizes the risk of it being exposed.
The other values to consider obfuscating are the salt and password hash, although those are less likely to get hacked, it is probably good to obfuscate them anyway.

Of course, we should remind the community not to share their `config.json` fully with anyone as that could potentially expose their node's private key if it is set there.

**Describe the solution you'd like**
1. Obfuscate sensitive config params in log output
2. Add a warning in docs for users not to share the `config.json` fully, only the parts required if they need assistance

**Comment by luca-moser** [comment]
Seems as we have missed some config options to be masked in stdout. This is actually something which is already in place, for example for the dashboard password salt/hash. Will make a PR for the other config options.

**Comment by muXxer** [comment]
Fixed with #1100
