### ISSUE TITLE
If Dashboard not enabled node does not start up

### ISSUE THREAD

**Issue by jmcanterafonseca-iota** [iotaledger/hornet#1101]
**Describe the bug**
If the dashboard plugin is not enabled Hornet does not start up 

**To Reproduce**
Disable the dashboard plugin and not provide any dashboard configuration. 

**Expected behavior**
The Node should run seamlessly with no Dashboard enabled. 

**Environment information:**

Hornet latest. Docker 

**Additional context**
Error generated

```
The following plugins are enabled: RestAPI Spammer URTS
panic: missing dependencies for function "github.com/gohornet/hornet/plugins/restapi".init.0.func1 (/app/plugins/restapi/plugin.go:35): missing type: string[name="dashboardAuthUsername"]
```

**Comment by muXxer** [comment]
Fixed by #1107
