### ISSUE TITLE
Improving docker documentation for static p2pidentity

### ISSUE THREAD

**Issue by hristo-mavrodiev** [iotaledger/hornet#1112]
Docker is generating new p2pidentity when the user needs to delete mainnetdb folder and restart the container, if there isn't p2p private key in `config.json`. Will be good to include in docker documentation the process to generate p2pidentity.

**Comment by luca-moser** [comment]
This is available here already: https://hornet.docs.iota.org/post_installation/post_installation.html#node-identity
