### ISSUE TITLE
Tab content under "settings" disappear

### ISSUE THREAD

**Issue by ChristopherWalz** [iotaledger/hornet#1114]
**Describe the bug**
Clicking on "settings" and "general" or "plugins" tab, after it is already selected makes the tab content disappear.

**Environment information:**
- HORNET 1.0.1
- Chrome

**Comment by muXxer** [comment]
This is a dashboard bug. Can you please create an issue report in the correct repository? :)

https://github.com/iotaledger/node-dashboard

**Comment by ChristopherWalz** [comment]
There already seems to be one: https://github.com/iotaledger/node-dashboard/issues/47
