### ISSUE TITLE
Can't synchronize without manually adding peer nodes?

### ISSUE THREAD

**Issue by YL-Aaron** [iotaledger/hornet#1117]
![image](https://user-images.githubusercontent.com/39772884/119477771-d95b4400-bd81-11eb-8ba2-efa8505daa03.png)

**Comment by Travetown** [comment]
atutpeering is not implemented in this version.  Therefore the neighbors have to be added manually.

**Comment by YL-Aaron** [comment]
> 在此版本中未实现atutpeering。因此，必须手动添加邻居。

It's bad~~  Does the official provide a corresponding peer node?

**Comment by pauli2406** [comment]
> > 在此版本中未实现atutpeering。因此，必须手动添加邻居。
> 
> It's bad~~ Does the official provide a corresponding peer node?

Currently the best way to find neighbors is by joining the discord channel https://discord.iota.org/ and ask for it in  #nodesharing

**Comment by muXxer** [comment]
Autopeering was added in #1125
