### ISSUE TITLE
Pruning - setting above 99999 is not recognized

### ISSUE THREAD

**Issue by Travetown** [iotaledger/hornet#1118]
**Describe the bug**

I have set the pruning setting to 150000 in the config.json.  
After reaching the MS, pruning did not start.  
Only a setting below 100000 activated pruning.

Hornet 1.0.2-rc1

Hetzner CPX31 Ubuntu 20.04

**Comment by muXxer** [comment]
Did you had the full history since Milestone 0 ?

**Comment by Travetown** [comment]
no is was about 36,000

**Comment by muXxer** [comment]
The value is not the target milestone, but a delay.
So you would need to reach milestone 186000 if pruning should start if your current pruning index is 36000 and your delay is 150000. And there are some additional thresholds that are added internally.... something around 150 milestones as far as I remember.

Anyway, now we got the new pruning based on database size.
I will close this issue.
