### ISSUE TITLE
Include isSynced Flag to /info rest endpoint

### ISSUE THREAD

**Issue by pauli2406** [iotaledger/hornet#1119]
**Is your feature request related to a problem? Please describe.**
I would like to retrieve the isSynced flag via the rest endpoint api/v1/info of a node
This information is currently only available to the dashboard within the ws api in type 1.
`{
    "type": 1,
    "data": {
        "snapshot_index": 249459,
        "pruning_index": 189050,
        "is_healthy": true,
        "is_synced": true
    }
}`

**Describe the solution you'd like**
Extend the object that is being returned by /api/v1/info

`{
  "data": {
    "name": "HORNET",
    "version": "0.6.0-alpha",
    "isHealthy": true,
    **"isSynced": true,**
    "networkId": "testnet7",
    "bech32HRP": "atoi",
    "minPoWScore": 4000,
    "messagesPerSecond": 17,
    "referencedMessagesPerSecond": 16.8,
    "referencedRate": 98.82352941176471,
    "latestMilestoneTimestamp": 1617802102,
    "latestMilestoneIndex": 480,
    "confirmedMilestoneIndex": 480,
    "pruningIndex": 0,
    "features": [
      "PoW"
    ]
  }
}`

**Describe alternatives you've considered**
An alternative could be to create a new endpoint within the tangle route due to the fact this information is kinda tangle specific

**Comment by muXxer** [comment]
Why don't you use `isHealthy`? It's the better indicator, because isSynced is included, and it also tells you if your node has neighbors and the milestone is recent.

**Comment by pauli2406** [comment]
Oh, okay. In that case I actually miss understood this flag due to the existing separation within the hornet dashboard.

Is there also a difference between the meaning of /health (HTTP 200) and the isHealthy flag from /api/v1/info?

**Comment by muXxer** [comment]
No, it's the same.

**Comment by pauli2406** [comment]
alright, in that case I guess this feature request is not required anymore.
Thanks for the fast answer.
