### ISSUE TITLE
JWT-Api Token is not valid for endpoints like /api/v1/peers

### ISSUE THREAD

**Issue by pauli2406** [iotaledger/hornet#1124]
**Describe the bug**
The generated JWT token with the new helper tool  ```tool jwt-api``` works fine for the endpoints like /info and /tips.
Unfortunately the token seems not to be valid for endpoints like `/api/v1/peers` and returns the following error response:
```
{
    "message": "invalid jwt claims"
}
```

The key was generated with the identityPrivateKey stored in the config file. It also makes no difference if the jwtAuth is enabled or disabled for the node in the main.conf.

When using a JWT token that is generated for the dashboard after a successful login this issue does not occur and e.g. `/api/v1/peers` returns the expected data in response

**To Reproduce**
- Due to the issue mentioned here [Link](https://github.com/gohornet/hornet/issues/1123) the node is stopped
- Generate the key 
```
docker run -u 39999:39999 --rm -it -v /var/lib/hornet/p2p:/app/p2p gohornet/hornet:1.0.2 --p2p.peerStore.path=/app/p2p/store tool jwt-api
```
- Start the node 
```
systemctl start hornet
```
- Call the peers endpoint : 
```
curl https://iota.devster-hh.de/api/v1/peers -XGET -H "Authorization: Bearer $TOKEN" -H 'Accept: application/json' -H 'Content-Type: application/json'
```
- Returns the error message mentioned above

**Expected behavior**
I would expect to have the api jwt token to work the same like the jwt token for the dashboard.

**Environment information:**
 - HORNET version  1.0.2

**Additional context**
JWT Payload from working token:
```
{
   ....
  "dashboard": true,
  "api": false
}
```

JWT Payload from the not working api token:
```
{
   ....
  "dashboard": false,
  "api": true
}
```

**Comment by alexsporn** [comment]
You are trying to access the dashboard api with a node api token.

**Comment by pauli2406** [comment]
So are the endpoints described in here: [Swagger](https://editor.swagger.io/?url=https://raw.githubusercontent.com/rufsam/protocol-rfcs/master/text/0026-rest-api/rest-api.yaml) not describing existing rest api endpoints but a mixture between dashboard and api endpoints?

And if so what would be the correct endpoint to retrieve peer data via rest when authenticating with jwt?

**Comment by pauli2406** [comment]
> You are trying to access the dashboard api with a node api token.

In that case is the generated jwt token  by tool jwt-api for [Node event api](https://playground.asyncapi.io/?load=https://raw.githubusercontent.com/luca-moser/protocol-rfcs/rfc/node-event-api/text/0033-node-event-api/0033-node-event-api.yml) and not the [Iota rest api](https://editor.swagger.io/?url=https://raw.githubusercontent.com/rufsam/protocol-rfcs/master/text/0026-rest-api/rest-api.yaml) ?
If so it would really make sense to add a generator for the iota api as well...

**Comment by muXxer** [comment]
@pauli2406 
As alex tried to explain, you are misusing the API.
You need to expose the RestAPI port, then the generated token works.
You are using the forwarded API that is only for internal use by the dashboard.

**Comment by pauli2406** [comment]
@muXxer 
So that means you have exposed similar endpoints with a different base url/port and authentication within hornet?
a. For the Hornet Dashboard that uses a dashboard JWT Token
b. For the Rest Api that can be exposed and secured with a api JWT Token?

If so do I configure the Port for the rest api (b) with the following param? `bindAddress: "0.0.0.0:14265"`

And setting this would allow me after exposing it to the public within my reverse proxy to authenticate my request with the JWT Token of type api and call secured endpoints like the list of peers with the following route : `https://iota.devster-hh.de:14265/api/v1/peers` .

That assumption correct?

If not, could you provide me with a more detailed instruction of hornet configurations that are required to call the secured endpoints, e.g. peers?

Also, why are the permittedRoutes accessible via the dashboard api when using a api JWT token and not restricted to the dashboard JWT token. This would avoid confusion between both apis.
Best regards,
Marcel

**Comment by muXxer** [comment]
Your assumption is correct.

We partly use the same endpoints from the rest API but internally forwarded for the dashboard.
We will make it a bit more clear with future changes.
@alexsporn was already working on this after talking to nuriel about this topic.

**Comment by pauli2406** [comment]
@muXxer and @alexsporn
Thanks for your tips, I now managed to get it running, in the end it was a problem with my reverse proxy configuration...

Unfortunately I think the current solution it is not optimal yet. This is due to the missing possibility to only protect crucial endpoints of the node with a JWT token instead of all of them or none.

The current solution only offers enabled or disabled, which in my case when building an app either forces the user to enable JWT Auth to gain full functionality access and enforces sending the token with every request (/info etc.) or to disable JWT Auth for reduced functionality and requires him to add configurations within the reverse proxy to protect some more security relevant endpoints.

Do you plan to allow configuring some sort of hybrid structure in the upcoming changes that would allow to expose some routes without JWT auth and some with in?

Next to this I think it would be a really neat feature to add the token generation as a functionality within the dashboard.
I guess at some point I should try to contribute myself instead of just asking for stuff ;)
