### ISSUE TITLE
System resource in "get Node Info" response 

### ISSUE THREAD

**Issue by sdellava** [iotaledger/hornet#1126]
The GET /api/v1/info REST API return very useful information to evaluate the node status but do not include any information related to the underlying environment.

Whit this feature request I suggest to add a couple of additional information to the node response. In example:

``` 
{
  "data": {
    "name": "HORNET",
    "version": "1.0.2",
    "isHealthy": true,
    "networkId": "chrysalis-mainnet",
    "bech32HRP": "iota",
    "minPoWScore": 4000,
    "messagesPerSecond": 65,
    "referencedMessagesPerSecond": 72.2,
    "referencedRate": 111.07692307692307,
    "latestMilestoneTimestamp": 1622631608,
    "latestMilestoneIndex": 297042,
    "confirmedMilestoneIndex": 297042,
    "pruningIndex": 269001,
    "features": ["PoW"],
    "systemInfo" : {
        "cpuUsage" : 64,
        "MemoryUsage" : 43,
        "dikUsage" : 70,
        "databaseSize" : 28
    }
  }
} 
```
The systemInfo property include some basic information collected from the system with standard lib.

These information allow to build a very simple monitoring and system and to build a API call balancer that can route incoming calls to a node whit less system load.

**Comment by muXxer** [comment]
That sounds very feature creep to me.
If you need something like that on your server, better use software that was made especially for that purpose.
For example https://github.com/prometheus/node_exporter

**Comment by sdellava** [comment]
Maybe you can collect data from Prometeus but having all node health related info in one API response provide a very useful tool.
