### ISSUE TITLE
Milestones taking a long time to confirm

### ISSUE THREAD

**Issue by h0m35t4r** [iotaledger/hornet#1129]
Certain milestones are either taking a very long time to confirm > 30 minutes or never confirm. Have to delete the database and start over to fix.

**Environment information**
 - OS: Debian 10 Stable
 - RAM: 4GB
 - Cores: 4 Cores, 4 threads
 - Type: VM under FreeBSD. Intel E3-1220, RAID 10
 - HORNET version 1.02

**Additional context**
I have run the go profiler as suggested on discord. 

https://we.tl/t-qqWQdioxwx

**Comment by muXxer** [comment]
Can you run the bench io tool?
`./hornet tool bench-io`

**Comment by h0m35t4r** [comment]
Average IO speed: 33 MB/s (64534x 32+1000 byte chunks with rocksdb database, total 67 MB/516 MB, 32266 objects/s, 12.91%. 13s left...)
Average IO speed: 17 MB/s (72193x 32+1000 byte chunks with rocksdb database, total 74 MB/516 MB, 16089 objects/s, 14.44%. 26s left...)
Average IO speed: 11 MB/s (72194x 32+1000 byte chunks with rocksdb database, total 74 MB/516 MB, 10326 objects/s, 14.44%. 41s left...)
Average IO speed: 12 MB/s (104836x 32+1000 byte chunks with rocksdb database, total 108 MB/516 MB, 11659 objects/s, 20.97%. 33s left...)
Average IO speed: 13 MB/s (142187x 32+1000 byte chunks with rocksdb database, total 147 MB/516 MB, 12936 objects/s, 28.44%. 27s left...)
Average IO speed: 14 MB/s (180611x 32+1000 byte chunks with rocksdb database, total 186 MB/516 MB, 13902 objects/s, 36.12%. 22s left...)
Average IO speed: 16 MB/s (227768x 32+1000 byte chunks with rocksdb database, total 235 MB/516 MB, 15193 objects/s, 45.55%. 17s left...)
Average IO speed: 16 MB/s (271493x 32+1000 byte chunks with rocksdb database, total 280 MB/516 MB, 15978 objects/s, 54.30%. 14s left...)
Average IO speed: 17 MB/s (311685x 32+1000 byte chunks with rocksdb database, total 322 MB/516 MB, 16411 objects/s, 62.34%. 11s left...)
Average IO speed: 17 MB/s (346723x 32+1000 byte chunks with rocksdb database, total 358 MB/516 MB, 16517 objects/s, 69.34%. 9s left...)
Average IO speed: 17 MB/s (379799x 32+1000 byte chunks with rocksdb database, total 392 MB/516 MB, 16518 objects/s, 75.96%. 7s left...)
Average IO speed: 17 MB/s (409647x 32+1000 byte chunks with rocksdb database, total 423 MB/516 MB, 16391 objects/s, 81.93%. 5s left...)
Average IO speed: 16 MB/s (433338x 32+1000 byte chunks with rocksdb database, total 447 MB/516 MB, 15996 objects/s, 86.67%. 4s left...)
Average IO speed: 15 MB/s (433372x 32+1000 byte chunks with rocksdb database, total 447 MB/516 MB, 14733 objects/s, 86.67%. 4s left...)
Average IO speed: 14 MB/s (433373x 32+1000 byte chunks with rocksdb database, total 447 MB/516 MB, 13770 objects/s, 86.67%. 4s left...)
Average IO speed: 14 MB/s (440213x 32+1000 byte chunks with rocksdb database, total 454 MB/516 MB, 13122 objects/s, 88.04%. 4s left...)
Average IO speed: 14 MB/s (479597x 32+1000 byte chunks with rocksdb database, total 495 MB/516 MB, 13491 objects/s, 95.92%. 1s left...)
Average IO speed: 14 MB/s (500000x 32+1000 byte chunks with rocksdb database, total 516 MB/516 MB, 13248 objects/s, took 37.74s)

**Comment by muXxer** [comment]
That looks kinda unstable and really slow. Even a cheap VPS on hetzner has almost twice the speed.
Since no one else has these problems, I'm 100% sure its a problem in your setup.

Some milestones trigger snapshotting and pruning, which means these milestones are heavier regarding disc IO. If your setup can't handle that, the confirmation of the milestones will take longer.

**Comment by h0m35t4r** [comment]
Thanks for letting me know. I will upgrade my disks.

**Comment by muXxer** [comment]
Maybe its a problem with your VM setup and not the discs? :shrug: 
Can you try the same test on the host again?

**Comment by h0m35t4r** [comment]
I will take a look into it when I can and get back to you. In the meantime I have some NVMe disks on the way. Think it is best I dedicate some resources for the project
