### ISSUE TITLE
issue in creating rocksdb

### ISSUE THREAD

**Issue by hiraarzo** [iotaledger/hornet#1132]
after cloning this github setup when i run main.go file for creation of node i always get this error.

Spammerpanic: For RocksDB support please compile with '-tags rocksdb'

i tried adding  '-tags rocksdb' but still unresolvable..

kindly help if anyone know the issue.
thankyou.

**Comment by no8ody** [comment]
It is recommend to use the following script to build hornet:
`hornet/scripts/build_hornet_rocksdb_builtin.sh`

**Comment by muXxer** [comment]
Yeah you need to use the provided script to build with the correct flags.
Issue closed.
