### ISSUE TITLE
Hornet node did not shutdown

### ISSUE THREAD

**Issue by centercirclesolutions** [iotaledger/hornet#115]
Hornet V2.11
Pi4 Ubuntu ARM64 4GB
Profile: custom (as provided by default)

Upon syncing I shut down Hornet and copied the mainnetdb to a backup. I restarted Hornet and then 15 to 20 minutes later after seeing a lot of swapping I was going to change to a lighter profile. upon using systemctl stop Hornet started the shutdown process but was still processing milestones. 
Log attached: [HornetNotShuttingDown.txt](https://github.com/gohornet/hornet/files/4022797/HornetNotShuttingDown.txt)

**Comment by muXxer** [comment]
Should be fixed in the latest version
