### ISSUE TITLE
Tangle Glumb (Graph) Stops after 30 seconds

### ISSUE THREAD

**Issue by centercirclesolutions** [iotaledger/hornet#116]
Hornet V2.11 (Built from Git Source) (TangleGlumb cloned in same dir as hornet)
Pi4 Ubuntu ARM64 4GB
Profile: custom (As provided)
Browser Chrome Version 79.0.3945.88 (Official Build) (64-bit)
Dell XPS 15 i7 32GB

The Tangle Graph starts to Populate but stop after about 20-30 seconds i stops and only a refresh of the browser will restart. Also if the top two switches are clicked the page becomes unresponsive.

**Comment by muXxer** [comment]
I tested it again on my machine.
For me it works with Firefox and Chrome on via localhost.

Is this maybe something in your network causing this?

**Comment by muXxer** [comment]
Was fixed with #270
