### ISSUE TITLE
Add tags and approvees support to findTransactions

### ISSUE THREAD

**Issue by viossat** [iotaledger/hornet#147]
**Is your feature request related to a problem? Please describe.**
IRI allows to findTransactions by addresses, bundles, tags and approvees. While Hornet only allows the two first ones. That's enough for applications like Trinity, but some tools (eg. statistics, visualizer) requires the two others.

**Describe the solution you'd like**
As discussed with the dev team, tags and approvees are currently not indexed to save some disk space and memory. I propose to add an option to index tags and approvees, disabled by default. As local snapshots files will stay shared without those extra indexed data, Hornet would need to create the indexes if not present.
That feature could be extended to the addresses index (I don't think that's possible for bundles), enabled by default, allowing some low-performance private nodes to save more hardware resources.

**Describe alternatives you've considered**
I currently use IRI for findTransactions requests but really want to switch to Hornet.

**Comment by muXxer** [comment]
Added in #195
