### ISSUE TITLE
Two Hornet Nodes Panic with a few hours of each other

### ISSUE THREAD

**Issue by centercirclesolutions** [iotaledger/hornet#148]
**Describe the bug**
Running two nodes on Pi4 4GB Hornet 3.0 2GB Profile both are running as services (no docker)

They have been running fine for about 1 - 2 days and both had a panic error on different transactions within a few hour of each other.

I've attached the logs for analysis.

[Hornet_Panic.zip](https://github.com/gohornet/hornet/files/4074557/Hornet_Panic.zip)

**Comment by muXxer** [comment]
Should be solved with #199
