### ISSUE TITLE
Transaction flagged as not confirmed during LS creation with objectstorage

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/hornet#158]
**Describe the bug**
Node crashed while getting the approvees of a milestone during local snapshot creation.

[hornet.log](https://github.com/gohornet/hornet/files/4083449/hornet.log)

**To Reproduce**
Run 8d5455e0d7c282f562c5147df8d61a1802d633a0

**Expected behavior**
Shouldn't crash

**Environment information:**
 - OS: Ubuntu
 - RAM: 32 gb
 - Cores: 8 cores
 - Type: VPS]
 - HORNET version 8d5455e0d7c282f562c5147df8d61a1802d633a0

**Comment by centercirclesolutions** [comment]
Same issue Pi4 4GB 2GB profile Ubuntu ARM64 tx-objectstorage branch

[tx-objectstorage LS Panic.log](https://github.com/gohornet/hornet/files/4084969/tx-objectstorage.LS.Panic.log)

**Comment by muXxer** [comment]
Solved with #199
