### ISSUE TITLE
A transaction which was in a bundle bucket, wasn't found during AddTransaction again

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/hornet#159]
**Describe the bug**
In the error log, an AddTransaction on the bundle bucket is executed but then crashes, because a corresponding transaction which is set to be already in the bucket, wasn't found when quried via the objectstorage.

[auto02.log](https://github.com/gohornet/hornet/files/4085180/auto02.log)

**To Reproduce**
- Run 8d5455e0d7c282f562c5147df8d61a1802d633a0

**Expected behavior**
Shouldn't crash.

**Environment information:**
 - OS: 18.04
 - RAM: 32
 - Cores: 8
 - Type: VPS
 - HORNET version 8d5455e0d7c282f562c5147df8d61a1802d633a0

**Comment by muXxer** [comment]
Solved with #199
