### ISSUE TITLE
Changes to neighbors.json are no longer recognized if neighbors were previously added via API

### ISSUE THREAD

**Issue by IoTMOD** [iotaledger/hornet#165]
**Describe the bug**
Changes to the neighbors.json config are no longer recognized if neighbors were previously added via API

**To Reproduce**
- Start HORNET
- Edit and save `neighbors.json` --> changes will be recognized
- Add a neighbor with `addNeighbors` --> changes are saved to `neighbors.json`
- Edit and save `neighbors.json` again --> changes are no longer recognized

**Expected behavior**
Changes will always be detected.

**Environment information:**
 - OS: Ubuntu 19.10
 - HORNET 0.3.0

**Comment by muXxer** [comment]
@IoTMOD can you try again with the latest dev branch??

**Comment by IoTMOD** [comment]
The issue still exists in the latest develop branch (1e6e39d).
We need to investigate this further. I don't know why it doesn't work, yet.

**Comment by muXxer** [comment]
Somehow the new content in the file is not recognized by viper after the first SaveConfig call.

**Comment by muXxer** [comment]
https://github.com/spf13/viper/issues/742

**Comment by luca-moser** [comment]
Closed due to inactivity.
