### ISSUE TITLE
handshake failed, neighbor is already connected

### ISSUE THREAD

**Issue by VanDeRub** [iotaledger/hornet#18]
**Describe the bug**
After restart i'm not able to connect to my neighbor to whom i had a stable connection before restart

**To Reproduce**
- restart node

**Expected behavior**
- Error does not show up every time after restart

**Environment information:**
 - OS: Ubuntu 18.04
 - RAM: 4 GB
 - Cores: 2 Cores
 - Type: VPS
 - HORNET version 0.2.1

`ReceivingState error: handshake failed: couldn't handshake properly: xx.xx.xxx.xxx:15600: neighbor is already connected
2019/12/13 02:57:50 [ ERROR ] Gossip: connection error on neighbor xx.xx.xxx.xxx:15600: close tcp yy.yy.yy.yyy:15600->xx.xx.xxx.xxx::56700: use of closed network connection`

**Comment by luca-moser** [comment]
* Does your neighbor have its max neighbors option increased?
* Is the neighbor actually not connected after the restart or are you just concerned about the error message?

**Comment by VanDeRub** [comment]
- No "maxneighbors" is set to 5, the default value
- neighbor is online

**Comment by luca-moser** [comment]
> neighbor is online

What I meant is, is the neighbor `connected` when you query your node via `getNeighbors`?
Also, did you make sure that you don't have the same neighbor twice in your neighbors list?

**Comment by VanDeRub** [comment]
Sry, all my neighbors are connected stable since a while. Can't reproduce and i didn't query the last time. I'll watch out if it happens once again.
