### ISSUE TITLE
Hornet should exit if tcp neighboring port is already in use

### ISSUE THREAD

**Issue by nuriel77** [iotaledger/hornet#180]
**Describe the bug**
If the tcp neighboring port (e.g. 15600/tcp) is already in use by another application hornet just throws an error in the log but doesn't exit.

**To Reproduce**
- Let netcat listen on port 15600 tcp
- startup hornet
- check the logs: it will report:
```
Jan 28 10:36:18 server.com hornet[19055]: TCP error: listen tcp 0.0.0.0:15600: bind: address already in use
```
But still continue running.

**Expected behavior**
Given that this is the most important port for hornet, there's no reason it should continue running if this port is not free to use. That would make it clear to the user something's amiss.

**Environment information:**
Doesn't matter

**Comment by alexsporn** [comment]
Fixed with https://github.com/gohornet/hornet/pull/204
