### ISSUE TITLE
develop branch: HORNET returns unwanted cli flag

### ISSUE THREAD

**Issue by IoTMOD** [iotaledger/hornet#182]
**Describe the bug**
HORNET returns a `--objectstorage.directory` cli flag on requesting help

**To Reproduce**
- Run `go run main.go -h` with the latest develop branch

**Expected behavior**
Do not show the `--objectstorage.directory` cli flag

**Additional context**
Maybe we can use this for a fix:
https://github.com/spf13/pflag#hidden-flags

**Comment by muXxer** [comment]
Solved with #199
