### ISSUE TITLE
TCP error - too many open files

### ISSUE THREAD

**Issue by VanDeRub** [iotaledger/hornet#19]
**Describe the bug**
Hornet panic -> Node crash's

**Environment information:**
 - OS: Ubuntu 18.04
 - RAM: 4 GB
 - Cores: 2 Cores
 - Type: VPS
 - HORNET version 0.2.1

**Additional context**
- uptime: about 8 hours
- VPS is only running hornet nothing else
- 4 neighbors
- Panic occured after spam

Logs:
`TCP error: accept tcp [::]:15600: accept4: too many open files
Dec 14 13:56:22 Ubuntu-Hornet hornet[7493]: message repeated 20754 times: [ TCP error: accept tcp [::]:15600: accept4: too many open files]
`
`
Dec 14 13:56:22 Ubuntu-Hornet hornet[7493]: panic: runtime error: invalid memory address or nil pointer dereference
`
`
Dec 14 13:56:22 Ubuntu-Hornet hornet[7493]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x967c92]`

**Comment by luca-moser** [comment]
Is there any way you can reproduce this error?

**Comment by VanDeRub** [comment]
Had this Error just once. It happend after i spammed the node for a while. Spammed it again several times but it didn't show up again.

**Comment by muXxer** [comment]
I will close this issue for now
