### ISSUE TITLE
Object storage crashes

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/hornet#190]
**Describe the bug**
This is a collection of crashes since the object storage changes for book keeping:
* Failed confirmation due to missing transaction: https://ybin.me/p/182ec1762224b7fa#aFsDMtnJXdSWQhZ82rWvbOq2EHpNTEiL+p0Kq0MVO08=
Transaction CISUDHALBKFDBM... does exist.
* Negative balance diff computation on milestone confirmation:
https://ybin.me/p/2e8b184fb8a6a88d#Oa/P5dm7SoD8GSwOVhFEILgM4d2a6fcFWfjVEKome48=
https://ybin.me/p/eae0e8eeced9c74b#SaapQAtPgWJzg69DJhltNwizwUYBMdYeQ74t8yhvbu8=

**Comment by muXxer** [comment]
Should be solved with #199
