### ISSUE TITLE
Spent addresses are not saved in local snapshot file

### ISSUE THREAD

**Issue by centercirclesolutions** [iotaledger/hornet#229]
**Describe the bug**
Starting Hornet with a snapshot file that contains spent adressess loads them but when the first sync and local snapshot happen they are not written back

**To Reproduce**
D/L LS with Spent Addresses
Start Hornet.... Sync
view spent address load messages in log file
View Local Snapshot file (23MB) 

**Expected behavior**
Spent Addresses should be saved back into the Local Snapshot file Size 642MB

**Environment information:**
 - OS: Ubuntu 19
 - RAM: 8GB
 - Cores: 4
 - Type: Intel i5
 - HORNET 3.0 Dev (87679db)

**Additional context**

**Comment by IoTMOD** [comment]
Should be fixed with #230
