### ISSUE TITLE
LS Spent Address load fails with: mlock failed

### ISSUE THREAD

**Issue by centercirclesolutions** [iotaledger/hornet#239]
**Describe the bug**
Starting in commit 664ccd014464f7e2f20b668282053fd2108588c0 spent address load fails with the error: 
```
runtime: mlock of signal stack failed: 12
runtime: increase the mlock limit (ulimit -l) or
runtime: update your kernel to 5.3.15+, 5.4.2+, or 5.5+
fatal error: mlock failed
runtime stack:
runtime.throw(0x1159ee0, 0xc)
        /usr/local/go/src/runtime/panic.go:1112 +0x72
runtime.mlockGsignal(0xc01c246f00)
        /usr/local/go/src/runtime/os_linux_x86.go:72 +0x107
```

**To Reproduce**
Start Hornet for any build after the commit listed above
Hornet fails while loading snapshot with spend addresses

**Workaround**
You can increase the mlock limit in several ways. Since the low limit in Ubuntu 19 seems to be related to systemd services, placing `LimitMEMLOCK=infinity` in the services config file eliminates the panic error.

**Expected behavior**
Hornet Starts

**Environment information:**
 - OS: Ubuntu 19.10
 - RAM: 8GB
 - Cores: 4 Cores
 - Type: Intel i5
 - HORNET Develop branch

**Additional context**
Here are two stack dumps during spent address load (where it seems to fail on current develop)
Good Start 87679dbc155bdbb43c6e77d18b5cf520d70af1b5
https://ybin.me/p/8a44eae04295adca#Eysj3aXawBWGzzNQoX2Hg7wSLMUsOThHHi8sCF8ZzLM=

Bad Start 154578d40c34f3f7606902c0cc8143b04cc16005
https://ybin.me/p/8cf7665c7fb37908#mi0JXxK3fyc556iDjc3EwhRZ2W2Sy1CuJwso+jcp0Y4=

Log 
https://ybin.me/p/e973ff77cea9ddd0#x/sCvHjpXUFieNZTrLKV+qctV8O1CrKX5zTrawYbqzs=

**Comment by tylerw1369** [comment]
Does the same for windows 10. Just FYI

**Comment by muXxer** [comment]
It's a problem with Go 1.14 right?

**Comment by centercirclesolutions** [comment]
It's a problem with ubuntu 19.10 (as well as hornet using alot of memory locks) but if we could reference something in the documentation or changelog about mlock and the adjustment to the Systemd file then we can probably remove this.

**Comment by IoTMOD** [comment]
:+1:
Moved to the HORNET wiki repo: gohornet/wiki/issues/10
