### ISSUE TITLE
Precompiled Docker files

### ISSUE THREAD

**Issue by IoTMOD** [iotaledger/hornet#25]
Automatically build Docker images for all architectures (ARM, ARM64, AMD64) and push them to the docker hub on new releases.

- [x] Create Docker Hub account
- [ ] Implement into GoReleaser 
   - [x] AMD64
   - [ ] ARM
   - [ ] ARM64

**Comment by georg90** [comment]
since this was closed, no plans to create an images for arm / arm64?
