### ISSUE TITLE
Graph Websocket / Web Page Fail with concurrent write

### ISSUE THREAD

**Issue by centercirclesolutions** [iotaledger/hornet#258]
**Describe the bug**
panic when refreshing the graph page

**To Reproduce**
Run graph, after lockup and closed browser tabs. Re-opened tab and connect to graph url. Graph was connecting (spinning) for 1 minute. 
Refreshed browser and panic ensued

**Expected behavior**
Graph refreshes

**Environment information:**
 - OS: Ubuntu 19.10
 - RAM: 8GB
 - Cores: 4 Cores
 - Type: Intel i5
 - HORNET Develop branch 

**Additional context**
![image](https://user-images.githubusercontent.com/44786846/76687006-4a7b6500-65dd-11ea-9004-829d51b22979.png)

**Comment by muXxer** [comment]
Fixed with #272
