### ISSUE TITLE
Node crashes: Could not open new DB - Cannot acquire directory lock on "mainnetdb".  Another process is using this Badger database.

### ISSUE THREAD

**Issue by ghost** [iotaledger/hornet#26]
The first time i activated the GoHornet node, i realized i hadn't insert the neighbor yet; therefore, during the "[ INFO ] Snapshot: Importing current ledger" operation, i blocked the node execution by pressing CTRL+C.

I added the new neighbor and we i try to reactivate the node, this error pops up:
Could not open new DB:

2019/12/15 18:32:24 [ INFO ] Node: Loading Plugin: Gossip ... done
panic: Could not open new DB: Cannot acquire directory lock on "mainnetdb".  Another process is using this Badger database.: resource temporarily unavailable .

After this error, the node crashes.

![image](https://user-images.githubusercontent.com/10340922/70866760-d42f7e00-1f6d-11ea-8e2f-fd950074c5c4.png)

This error is now appearing every time i try to reactivate the node and the node can't be reactivated.

I had to delete the mainnetdb folder to solve the situation; then, reactivating the node, everything works.

 - OS: Ubuntu 16.04
 - RAM: 6 GB
 - Cores: 6 cores
 - Type: VPS on Contabo
 - HORNET version 0.2.3

**Comment by muXxer** [comment]
There was another HORNET running in the background, which blocked the DB.
Please kill all the running processes first.
