### ISSUE TITLE
Add ability to specify preferIPv6 for neighbors via the API

### ISSUE THREAD

**Issue by nuriel77** [iotaledger/hornet#28]
**Is your feature request related to a problem? Please describe.**
The config.json has as example:
```
      {
        "identity": "example1.neighbor.com:15600",
        "preferIPv6": false
      },
```
I understand that preferIPv6 is currently only configurable via the configuration file.

**Describe the solution you'd like**
Be able to add a neighbor via the API while specifying (optional) preferIPv6 true or false (default to false).

**Describe alternatives you've considered**
No alternative?

**Additional context**
Support configurable priority for IPv6 address resolution for domain names.

**Comment by IoTMOD** [comment]
Hi @nuriel77,

the current addNeighbors API command looks like this:

```json
{
  "command": "addNeighbors",
  "uris": [
    "tcp://8.8.8.8:14265",
    "tcp://8.8.8.8:14265"
  ]
}
```

So I think we basically have two options (without doing a breaking change and become incompatible to IRI):
1. Set the preferIPv6 option for all uris passed (if IPv4 address: ignore preferIPv6 for this address)
```json
{
  "command": "addNeighbors",
  "uris": [
    "tcp://my01.domain:14265",
    "tcp://my02.domain:14265"
  ],
  "preferIPv6": true
}
```
2. Add another API command like `addNeighborsIPv6`

What would do you prefer? Or do you have another suggestion?

**Comment by nuriel77** [comment]
@IoTMOD well, if addressing this already I guess it is best to set IPv6 as default (linux kernel resolves default IPv6) and as citrullin mentioned.

Other option I was thinking of is a little ugly, optionally allow to write it as a prefix, e.g: `"ipv4+tcp://my01.domain:14265"`.

All other cases resolve IPv6 default unless address supplied is an IPv4 address. 
In case ipv4+tcp syntax provided on an IPv6 address, ignore the ipv4 syntax.

The advantage is that it would allow to configure a per-neighbor preference while not breaking any existing GUIs/tools.

If not this idea, maybe just do what IRI does? (as it uses Java's global setting) thus set it globally in Hornet's config?

The options you suggested are nice. I only wonder how that would work with existing GUIs (for example the one I've added to the playbook). It is hard to tell it which neighbor should have preference for a protocol (or neighbors have to be added separately)
