### ISSUE TITLE
Comnet: Total does not match supply

### ISSUE THREAD

**Issue by r-c-k** [iotaledger/hornet#302]
**Describe the bug**
Hornet panics with "panic: GetAllLedgerBalances() Total does not match supply: 0 != 2779530283277761".

**Environment information:**
 - OS: macOS Catalina 10.15.3
 - 0.4.0-rc2

**Additional context**
https://pastebin.com/bQkSyy2z

**Comment by r-c-k** [comment]
Disabling local snapshots seems to solve the issue until the next restart

**Comment by muXxer** [comment]
Fixed with #304
