### ISSUE TITLE
Error when starting hornet 0.4.0-rc2 

### ISSUE THREAD

**Issue by tylerw1369** [iotaledger/hornet#311]
Describe the bug
When first starting up my comnet node and connecting to neighbors, it starts to get needed tx's and then throws this error

To Reproduce

Make a clean install of hornet 0.4.0 rc-2
run hornet comnet with default settings

Expected behavior
start the node and work on syncing.

Environment information:

OS: ubuntu 18.04.4
RAM: 32GB
Cores: 16
Type: windows 10 wsl 1 i believe
HORNET version 0.4.0 rc-2
[hornet.log](https://github.com/gohornet/hornet/files/4366263/hornet.log)

**Comment by muXxer** [comment]
`export_comnet.bin: no such file or directory`

you have to download the local snapshot file of comnet and rename it!
