### ISSUE TITLE
Comnet shutdown hangs on badger garbage collection

### ISSUE THREAD

**Issue by TeeVeeEss** [iotaledger/hornet#314]
**Describe the bug**
Shutdown of Comnet hangs on running badger garbage collection

**To Reproduce**
Run comnet on console. After a few hours stop with CTRL-C.  Shut down starts but hangs on garbage collection
**Expected behavior**
Should do proper shutdown.

**Environment information:**
 - OS: Ubuntu 18.04
 - RAM: 8 GB
 - Cores: 4 Cores
 - Type: Strato VPS
 - Browser chrome
 - HORNET version 0.4.0-rc2, profile 4gb

**Additional context**
Gathered as much as info as possible, see https://ybin.me/p/4dedb3fea252f3d2#ZhBiQs0ZW7s7eflqqNVx4eKQ22R2x7wWNloLgZODjXw=
with:
- config.json
- last log lines from console
- full trace from debug/pprof

On the same VPS runs my mainnet hornet node without problems
![image](https://user-images.githubusercontent.com/17521100/77311913-506df600-6d01-11ea-9c31-556d228aa3d4.png)

**Comment by muXxer** [comment]
Fixed with #319
