### ISSUE TITLE
Hornet incomplete shutdown

### ISSUE THREAD

**Issue by centercirclesolutions** [iotaledger/hornet#32]
While shutting down Hornet and exiting with a ctrl-C it seems that not all hornet processes are triggered to shutdown as there are still transaction log messages intermixed with the shutdown log messages. At the end the process hangs and has to be killed thus corrupting the database. Attached is a partial log file.

[LogErrorHornet12-15-2019.txt](https://github.com/gohornet/hornet/files/3965787/LogErrorHornet12-15-2019.txt)

**Comment by QNODE-CA** [comment]
I have experienced something very similar now twice in a row, on a freshly installed 0.26 node.  Node has only one neighbor on my LAN, also running hornet. After node has synced, sending Ctrl+C stops some processes, but not hornet itself.  SSH console becomes unresponsive. Logging in from a second console shows that hornet still running. 
[cannot shutdown hornet.txt](https://github.com/gohornet/hornet/files/3969024/cannot.shutdown.hornet.txt)
![console hanging on ctrl+c](https://user-images.githubusercontent.com/10619487/70923108-31faaf00-1fdc-11ea-89cf-8d87f6a58fae.png)

**Comment by ghost** [comment]
I experienced exactly the same behavior, even starting / stopping the GoHornet node via systemctl:

![image](https://user-images.githubusercontent.com/10340922/70934765-f04f2000-203e-11ea-8060-5e7ed573592f.png)

And when i try to re-activate the node, the DB is corrupted and i need to delete the mainnetdb folder

![image](https://user-images.githubusercontent.com/10340922/70934860-30ae9e00-203f-11ea-8f2e-dceb42c75f60.png)

OS: Ubuntu 16.04
VPS: Contabo
CPU: 6 cores
RAM: 16 GB

**Comment by muXxer** [comment]
Fixed in v0.2.7
