### ISSUE TITLE
Stopping Solidifier takes a lot of time

### ISSUE THREAD

**Issue by svenger87** [iotaledger/hornet#34]
**Describe the bug**
Stopping Solidifier takes a lot of time in a Raspberry Pi 4.
The process seems to be singlethreaded and uses only one core.

**To Reproduce**
Shutdown hornet and start a Stopwatch 😆 

**Expected behavior**
Parallelize the thread and make use of all available cores.

**Environment information:**
 - OS: DietPi Buster
 - RAM: 4GB
 - Cores: 4 Cores]
 - Type: Raspberry Pi 4]
 - HORNET version [0.2.4]

**Additional context**
You guys rock

**Comment by muXxer** [comment]
The solidifier is busy. Here is a CPU profile. [cpu_profile.pdf](https://github.com/gohornet/hornet/files/3969883/cpu_profile-2.pdf)

**Comment by muXxer** [comment]
![solidifier](https://user-images.githubusercontent.com/32371094/70939274-3066d080-2048-11ea-8502-3e84722305d5.png)
30 Minutes to stop solidifier

**Comment by muXxer** [comment]
Fixed in v0.2.7
