### ISSUE TITLE
Direct Peering Fails on RC5

### ISSUE THREAD

**Issue by centercirclesolutions** [iotaledger/hornet#355]
**Describe the bug**
Direct peering fails with `connection refused` Autopeering is turned on for both nodes. 
acceptAnyConnection is only true for *iota.direct*

**To Reproduce**
Add peers to each nodes peering.json

*note* turning on acceptAnyConnection on *Little Small* allowed peering to initiate.

**Expected behavior**
Nodes should add both hosts and initiate gossip

**Environment information:**
**Little Small**
 - Ubuntu 18.04 4GB 2 Core Hetzner CX21
 - Hornet Version 0.4.0-rc5-c829585
 - acceptAnyConnection = false

**iota.direct**
 - Ubuntu 18.04 16GB 4 Core Hetzner CX41
 - Hornet Version 0.4.0-rc5-7e8fc74
- acceptAnyConnection = true

**Additional context**
**iota.direct**
Log> https://ybin.me/p/82f305df7f4362aa#woRVd41ajqw+CM7obsDrWQAtGSLbwgbKj9e/6B3pZSM=
peering.json> https://ybin.me/p/4734fd9ac475f5f3#53cKxKSh9pdgnW6q1a4mwbNSDfbkZiE7qQKVvu41UjM=

**Little Small**
Log> https://ybin.me/p/4edacc0bf9c585eb#acEwcSt997NnYUNAF4uQbnxP+Nu6BluCGCLnJUu8Sys=
peering.json> https://ybin.me/p/005ab2af25c36820#NUlxEqwWFuEO0XgKisKAopJhlypOnsn+cwUM3FwEmzk=

**Comment by IoTMOD** [comment]
I can neither find a log entry about the modification of the `peering.json` file nor the attempt to add the respective other neighbor.

- Have you previously removed or added neighbors via API?
- Is the neighbor shown in the dashboard?
- Does the peering work after a restart of both nodes?

**Comment by centercirclesolutions** [comment]
Both nodes had each other configured from initial start. There were edits to peering.json to update other nodes during that timeframe.

**Comment by tylerw1369** [comment]
I have the same issue between iri and hornet.  I'll see if I can catch it when it says disconnected in hornet and grab the log

**Comment by muXxer** [comment]
Seems to be related to #165
