### ISSUE TITLE
IPv6 neighbors do not seem to be removed from the dashboard

### ISSUE THREAD

**Issue by QNODE-CA** [iotaledger/hornet#360]
**Describe the bug**
One of my hornet nodes is showing 12 neighbors, most of them are IPv6 (Not Connected)

**To Reproduce**
start hornet 
wait for neighbors to join
so far this has only happened on one of my hornet nodes (Hetzner VPS), not sure why

**Expected behavior**
Usually non-connected neighbors are removed quickly from the dashboard

**Environment information:**
 - OS: Ubuntu 18.04.4 LST
 - RAM: 2 GB
 - Cores: 1
 - Type: Hetzner CX11 VPS
 - Browser: chrome
 - HORNET version 0.4-rc5

![screencapture-curly-iri-host-8081-neighbors-2020-03-30-17_11_49](https://user-images.githubusercontent.com/10619487/77973964-9a7b4c80-72aa-11ea-8964-81bffb6ce14a.png)

**Comment by muXxer** [comment]
fixed with #373
