### ISSUE TITLE
Reduce revalidation logs

### ISSUE THREAD

**Issue by viossat** [iotaledger/hornet#391]
**Describe the bug**
During the DB revalidation, Hornet re-writes the analyzed transactions counter in the logs after each analyzed transaction:
https://github.com/gohornet/hornet/blob/3b5bb500d2e197d0fa0748d2dcac03829a4d46e4/plugins/tangle/revalidation.go#L151
I use a centralized logs system on a cloud provider, this implementation leads to a lot of single-line useless logs like:
```
analyzed 313824 transactions analyzed 313825 transactions analyzed 313826 transactions analyzed 313827 transactions analyzed 313828 transactions analyzed 313829 transactions analyzed 313830 transactions analyzed 313831 transactions analyzed 313832 transactions analyzed 313833 transactions analyzed 313834 transactions analyzed 313835 transactions analyzed 313836 transactions analyzed 313837 transactions analyzed 313838 transactions analyzed 313839 transactions analyzed 313840 transactions analyzed 313841 transactions analyzed 313842 transactions analyzed 313843 transactions analyzed 313844 transactions analyzed 313845 transactions analyzed 313846 transactions analyzed 313847 transactions analyzed 313848 transactions analyzed 313849 transactions analyzed 313850 transactions analyzed 313851 transactions analyzed 313852 transactions analyzed 313853 transactions analyzed 313854 transactions analyzed 313855 transactions analyzed 313856 transactions analyzed 313857 transactions analyzed 313858 transactions analyzed 313859 transactions 
```
Also, writing a line for each analyzed transaction may take longer than the analysis of the transaction itself. The performance of the revalidation would probably be better without those logs at each tx.

**Expected behavior**
Writing the logs in a new line every X thousands of analyzed transactions.

**Environment information:**
 - OS: Linux
 - HORNET version 0.4.0-RC8

**Comment by muXxer** [comment]
done
