### ISSUE TITLE
createSnapshot WebAPI broken (always returns error)

### ISSUE THREAD

**Issue by centercirclesolutions** [iotaledger/hornet#400]
**Describe the bug**
When calling the createSnapshot WebAPI it always returns an error stating that the targetIndex is either too new or too old

**To Reproduce**
I kept getting too old errors so I used a higher targetIndex and the found that adjacent index numbers gave too old and too new so it was impossible to run without an error.
`curl -s http://127.0.0.1:14265 -X POST -H 'Content-Type: application/json' -H 'X-IOTA-API-Version: 1' -d '{"command":"createSnapshot","targetIndex":1385383`
`{"error":"minimum: 1385386, actual: 1385383: snapshot target is too old."`

Then incremented by one
`curl -s http://127.0.0.1:14265 -X POST -H 'Content-Type: application/json' -H 'X-IOTA-API-Version: 1' -d '{"command":"createSnapshot","targetIndex":1385384`
`{"error":"maximum: 1385383, actual: 1385384: snapshot target is too new."}`

**Expected behavior**
API shoud either provide correct information in the error or the it should find the right targetIndex and initiate the snapshot *(just do it)* 

**Environment information:**
 - Ubuntu 19.04 8GB 4 Core Intel i5
 - Version 0.4.0-rc8-787de48

**Comment by muXxer** [comment]
Fixed with #404
