### ISSUE TITLE
Pruning does not reduce DB size

### ISSUE THREAD

**Issue by centercirclesolutions** [iotaledger/hornet#416]
**Describe the bug**
Reducing the amount of pruning does not reduce or limit the size of the the database and results in the node crashing due to a full file system

**To Reproduce**
start hornet and set pruning to 3000 (milestones) monitored over several days and DB continued to grow. Log messages indicate that pruning is happening but te DB continues to grow.

*Logs from my server*
https://ybin.me/p/25400c5d773dc9a9#SWzGSD8iPxi+83y59lBLndxayS/TECd5KAQTo1rzcAA=

**Expected behavior**
Hornet should prune milestones at the limit set to allow the DB size to not exceed the filesystem. 

**Environment information:**
 - Ubuntu 18.04 8GB 4 Core CX41 with 150GB root filesystem
 - HORNET 0.4.0-rc8-e3a93da

**Comment by luca-moser** [comment]
Can you verify that when you run with a profile using `"numVersionsToKeep": 0,` this problem persists?

https://github.com/dgraph-io/badger/issues/1228#issuecomment-606076406

**Comment by luca-moser** [comment]
Forget what I just posted, it seems that doing that actually will keep infinite versions around due to a bug in BadgerDB.

**Comment by centercirclesolutions** [comment]
Yes, Max tried this change already. It didn't go so well

**Comment by alexsporn** [comment]
@centercirclesolutions please try with my PR. Actually pruning initially increases the database size. It is just after Badger value GC runs that the size decreases again.

**Comment by alexsporn** [comment]
Fixed with 0.4.0-rc9
