### ISSUE TITLE
Hornet - Bolt Alpha Issue

### ISSUE THREAD

**Issue by centercirclesolutions** [iotaledger/hornet#433]
**Describe the bug**
Running Hornet RC9-Alpha with Bolt. After a day the dashboard is empty and other weird things start to happen ( alternating between 0 and 1K transactions )

**To Reproduce**
Start hornet and set pruning to 200 (this may not be necessary as ericvrp had no pruning and the spammer running). Node runs fine and memory and DB size increase. This issue happened to at least two server so it may be data related vs an individual server issue. 

**Eric will provide additional information from his node in a subsequent comment.**

*Logs and Dump from my server*
[hornet_comnet_bolt_issue.zip](https://github.com/gohornet/hornet/files/4633187/hornet_comnet_bolt_issue.zip)
[pprof stack dump](https://ybin.me/p/54be6c901de80b61#QCCChBZA1Xi+KVfio/REuf8tIahZsaOU6WpVwjZK03w=)

**Expected behavior**
Hornet works correct 

**Environment information:**
 - Ubuntu 18.04 8GB 4 Core CX41 with 150GB root filesystem
 - Version 0.4.0-rc8-16154c8

**Comment by ericvrp** [comment]
**Describe the bug**
Same as issue above but I was running with Badger (not Bolt) on Comnet!

**Version used**
- Version https://github.com/ericvrp/hornet/commit/9fe99c67c68b8294e13ad9e676de2b2e4a5757ae
- Build with: go build -tags=pow_avx -ldflags="-s -w -X github.com/gohornet/hornet/plugins/cli.AppVersion=0.4.0"

**Reproduce**
The time it takes is random but usually within a few hours. I have not been able to reproduce with the spammer disabled so enabling the spammer might bring the problem to light quicker.

**These config changes**
```
"node": {
   "enablePlugins": ["Spammer"]
},
spammer": {
     "cpuMaxUsage": 0,
     "tpsRateLimit": 0,
     "workers": 7
}
```

**Environment information:**
- AMD 2400G with 16GB internal storage +123SSD free
- Linux 5.5.18-3-MANJARO #1 SMP PREEMPT Sun Apr 19 19:51:26 UTC 2020 x86_64 GNU/Linux

![IMG_0301](https://user-images.githubusercontent.com/4216292/82033396-f5230900-969c-11ea-9bd8-1841fca45585.png)
![IMG_0302](https://user-images.githubusercontent.com/4216292/82033405-f8b69000-969c-11ea-8c37-0948df7d907a.png)

**Comment by ericvrp** [comment]
The last part of mylogfiles. 

[pm2.zip](https://github.com/gohornet/hornet/files/4633437/pm2.zip)

**Comment by svenger87** [comment]
Added a log snippet from my node.
It´s the relevant part where hornet stopped working with BoltDB.

[snip.txt](https://github.com/gohornet/hornet/files/4633452/snip.txt)

**Comment by ericvrp** [comment]
Not sure if this is related to restarting the node or caused by this bug directly but I get this traceback after restarting.

```
0|hornet  | 2020-05-15T11:33:27+02:00   INFO    Tangle  Milestone confirmed (72696): txsToConfirm: 938, collect: 24.891876ms, total: 58.789296ms
0|hornet  | 2020-05-15T11:33:27+02:00   INFO    Tangle  New solid milestone: 72696, 0.07 TPS, 15.41 CTPS, 23500.00% conf.rate
0|hornet  | 2020-05-15T11:33:27+02:00   INFO    Tangle  Run solidity check for Milestone (72699)...
0|hornet  | 2020-05-15T11:33:27+02:00   INFO    Tangle  Solidifier finished: txs: 2950, collect: 247ms, total: 496ms
0|hornet  | 2020-05-15T11:33:27+02:00   PANIC   Tangle  Milestones missing between (72696) and (72699).
0|hornet  | github.com/gohornet/hornet/plugins/tangle.solidifyMilestone
0|hornet  |     /home/hornet/hornet/plugins/tangle/solidifier.go:363
0|hornet  | github.com/gohornet/hornet/plugins/tangle.configureTangleProcessor.func3
0|hornet  |     /home/hornet/hornet/plugins/tangle/tangle_processor.go:51
0|hornet  | github.com/iotaledger/hive.go/workerpool.(*WorkerPool).startWorkers.func1
0|hornet  |     /home/hornet/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200508125657-76ee9eb66cf8/workerpool/workerpool.go:158
0|hornet  | panic:
0|hornet  | Milestones missing between (72696) and (72699).
0|hornet  | goroutine 3036346 [running]:
0|hornet  | go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0070c7290, 0x0, 0x0, 0x0)
0|hornet  |     /home/hornet/go/pkg/mod/go.uber.org/zap@v1.13.0/zapcore/entry.go:230 +0x545
0|hornet  | go.uber.org/zap.(*SugaredLogger).log(0xc0109284a0, 0xc015568b04, 0x118c17b, 0x29, 0xc005aa3e28, 0x2, 0x2, 0x0, 0x0, 0x0)
0|hornet  |     /home/hornet/go/pkg/mod/go.uber.org/zap@v1.13.0/sugar.go:234 +0x100
0|hornet  | go.uber.org/zap.(*SugaredLogger).Panicf(...)
0|hornet  |     /home/hornet/go/pkg/mod/go.uber.org/zap@v1.13.0/sugar.go:159
0|hornet  | github.com/gohornet/hornet/plugins/tangle.solidifyMilestone(0x0)
0|hornet  |     /home/hornet/hornet/plugins/tangle/solidifier.go:363 +0x5a8
0|hornet  | github.com/gohornet/hornet/plugins/tangle.configureTangleProcessor.func3(0xc0455a7520, 0x2, 0x2, 0xc01fd03ce0)
0|hornet  |     /home/hornet/hornet/plugins/tangle/tangle_processor.go:51 +0x8c
0|hornet  | github.com/iotaledger/hive.go/workerpool.(*WorkerPool).startWorkers.func1(0xc000442c80)
0|hornet  |     /home/hornet/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200508125657-76ee9eb66cf8/workerpool/workerpool.go:158 +0x1ad
0|hornet  | created by github.com/iotaledger/hive.go/workerpool.(*WorkerPool).startWorkers
0|hornet  |     /home/hornet/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200508125657-76ee9eb66cf8/workerpool/workerpool.go:134 +0x5e
PM2       | App [hornet:0] exited with code [2] via signal [SIGINT]
```

**Comment by ericvrp** [comment]
A re-restart gave no traceback

**Comment by alexsporn** [comment]
Please try again with 0.4.0-rc9
