### ISSUE TITLE
Bundle not Found Error

### ISSUE THREAD

**Issue by centercirclesolutions** [iotaledger/hornet#437]
**Describe the bug**
Latest Development branch as error with "bundle not found"

**To Reproduce**
Run server

[*Server Log* ](https://ybin.me/p/48b7ed5849e569d8#d9/ejgMv/cVDjz8AeY3LOTug+EpdZJgNAc/fI4wKZvw=)

**Expected behavior**
HORNET works correct 

**Environment information:**
 - Ubuntu 18.04 8GB 4 Core CX41 with 150GB root filesystem
 - Version 0.4.0-rc8-8318629

**Comment by alexsporn** [comment]
0.4.0-rc8-8318629 does not match the commit that we released as rc9. Do you have all the changes?

**Comment by luca-moser** [comment]
What kind of pruning parameters did you set on this particular node?

**Comment by svenger87** [comment]
Same here
[crash.txt](https://github.com/gohornet/hornet/files/4655162/crash.txt)

**Comment by luca-moser** [comment]
@svenger87 what pruning parameters are you using?

**Comment by svenger87** [comment]
@luca-moser 
```
"pruning": {
      "enabled": true,
      "delay": 1000
```

**Comment by svenger87** [comment]
Same happened on comnet

[comnet.txt](https://github.com/gohornet/hornet/files/4657498/comnet.txt)

**Comment by alexsporn** [comment]
Probably fixed with #441
