### ISSUE TITLE
DB Size increasing with pruning @ 200

### ISSUE THREAD

**Issue by centercirclesolutions** [iotaledger/hornet#446]
**Describe the bug**
Pruning is set to 200 which should stop the DB from growing after 3-4 hours. My node has now started to exponentially increase in DB size every 4 hours.

**To Reproduce**
Run server with pruning at 200

[Log](https://ybin.me/p/80428c90c9416191#Jah53kV7bQDIZYedgpD5XVE7PDE6B3mWeTUQrMUZ77w=)
[trace_boltdb_increase.zip](https://github.com/gohornet/hornet/files/4669498/trace_boltdb_increase.zip)
[Stack Dump](https://ybin.me/p/ff3c8142042d03ea#8XnGzxn5lzg+KZCRGjmVgawFcxkECfZ+it3iDSABQ9I=)
[Heap](https://ybin.me/p/07b801b36e10bdbf#FxcZloZWeg0xRM/RB7/6/z1BDcxqilOebNGwbC3GkGk=)
[alloc](https://ybin.me/p/416b5b543471d891#q1K/GSti14Wk7XuhrrJHlXlH3aj4eTyHHogeJGQpgys=)

**Expected behavior**
HORNET works correctly

**Environment information:**
 - Ubuntu 18.04 8GB 4 Core CX41 with 150GB root filesystem
 - Version 0.4.0-rc10-7511e71
- Go 14.3

**Comment by alexsporn** [comment]
Fixed with #451
