### ISSUE TITLE
Crash with FATAL Level

### ISSUE THREAD

**Issue by knight-ryu12** [iotaledger/hornet#447]
**Describe the bug**
I am not sure what causes this behavior.

**To Reproduce**
Unable to provide.

**Environment information:**
 - OS: ArchLinux
 - RAM: 4GB
 - Cores: 4 Cores
 - Type: X86_64
 - HORNET version 0.4.0-rc10

**Additional context**
https://ybin.me/p/448c41cdc3ff5937#S1k1vdQOv137FCPQWezUm9wvIft7XoEpKkj8Dg037zc=

**Comment by muXxer** [comment]
Looks like an unsafe pointer problem in bbolt.
Maybe this issue is fixed since we changed bbolt settings in #451.
Should this problem occur again, please open a new issue report.

**Comment by muXxer** [comment]
There seems to be an unmerged fix for the problem.
https://github.com/etcd-io/bbolt/pull/220

**Comment by knight-ryu12** [comment]
yeah, looks like it. thanks for an insight.
