### ISSUE TITLE
Failing to gracefully shutdown may cause reverting infinity

### ISSUE THREAD

**Issue by knight-ryu12** [iotaledger/hornet#448]
**Describe the bug**
Seems like there's bug around reverting process that causes infinitely reverting therefore node doesn't really start.

**To Reproduce**
Failing to stop node may or may not cause this issue; I am not sure.

**Expected behavior**
Normal revert and start node correctly.

**Additional context**
https://ybin.me/p/a91c8ef4861dfc1c#zOpmfJE1wdt8F7rRxeDkKZcFTMB4bNpSPo7QFh9SF9o=

**Comment by knight-ryu12** [comment]
https://keybase.pub/chromaryu/mainnetdb.tar.gz corrupted DB.

**Comment by muXxer** [comment]
Fixed in #452
