### ISSUE TITLE
5 Neighbours - after changing the cooaddress

### ISSUE THREAD

**Issue by ghost** [iotaledger/hornet#459]
**Describe the bug**
After i have updated to the new CooAddress i have constantly 5 peered neighbors
2 outbound / 3 inbound

**To Reproduce**
used the instruction from the Cooaddress change. After that the Bug appeared

**Environment information:**
 - OS: [raspbian lite]
 - RAM: [4 GB]
 - Cores: [4 Cores]
 - Type: [Raspberry Pi 4]
 - Browser [chrome]
 - HORNET version [0.4.0 rc11]

**Comment by muXxer** [comment]
This is a race condition in the autopeering module. Not a problem at all.
Thx for the bugreport! :)
