### ISSUE TITLE
Spam Event Log Gathering

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/hornet#473]
Post your full node log. If available also the pprof CPU and heap profiles.

**Comment by centercirclesolutions** [comment]
My results from the stress Test:

[Hetzner CPX41 8 core 16 GB 160 SSD]

[stresstest_dave_ef.log.gz](https://github.com/gohornet/hornet/files/4718237/stresstest.log.gz)
[heap.zip](https://github.com/gohornet/hornet/files/4718257/heap.zip)
[stresstest_profile.zip](https://github.com/gohornet/hornet/files/4718243/stresstest_profile.zip)
[Load Test Hornet Results.xlsx](https://github.com/gohornet/hornet/files/4718266/Load.Test.Hornet.Results.xlsx)

**Comment by renewid** [comment]
[hornet_stresstest_renew.gz](https://github.com/gohornet/hornet/files/4718951/hornet_stresstest_renew.gz)
[ded. Root-Server@Netcup, 2CPU Xeon Gold 6140@2.3GHz, 120GB SSD, 20GB RAM]

Changed to Mainnet @ 18:22:50 bc out of sync.

**Comment by gobbli** [comment]
[hornet_stresstest_hornet-test-01_gobbli#9178.zip](https://github.com/gohornet/hornet/files/4731230/hornet_stresstest_hornet-test-01_gobbli.9178.zip)
[hornet_stresstest_hornet-comnet-01_gobbli#9178.zip](https://github.com/gohornet/hornet/files/4731226/hornet_stresstest_hornet-comnet-01_gobbli.9178.zip)
[hornet_stresstest_hornet-comnet-02_gobbli#9178.zip](https://github.com/gohornet/hornet/files/4731227/hornet_stresstest_hornet-comnet-02_gobbli.9178.zip)
[hornet_stresstest_hornet-comnet-03_gobbli#9178.zip](https://github.com/gohornet/hornet/files/4731228/hornet_stresstest_hornet-comnet-03_gobbli.9178.zip)
[hornet_stresstest_hornet-comnet-04_gobbli#9178.zip](https://github.com/gohornet/hornet/files/4731229/hornet_stresstest_hornet-comnet-04_gobbli.9178.zip)

**logfiles re-uploaded at 04.06.2020**

Alls Nodes running on a Proxmox Virtual Environment.

Node hornet-test-01: 4 x Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz, 10GB RAM, SDD
Node hornet-comnet-01:  4 x Intel(R) Xeon(R) CPU E5-2690 0 @ 2.90GHz, 10GB RAM, 15k SAS
Node hornet-comnet-02:  4 x Intel(R) Xeon(R) CPU E5-2690 0 @ 2.90GHz, 10GB RAM, 15k SAS
Node hornet-comnet-03:  4 x Intel(R) Xeon(R) CPU E5-2690 0 @ 2.90GHz, 10GB RAM, 15k SAS
Node hornet-comnet-04:  4 x Intel(R) Xeon(R) CPU E5-2690 0 @ 2.90GHz, 10GB RAM, 15k SAS

**Comment by uwec** [comment]
[hornet_stresstest_uwec.gz](https://github.com/gohornet/hornet/files/4719011/hornet_stresstest_uwec.gz)
Hetzner CX41

**Comment by TeeVeeEss** [comment]
[comnet_spam_event_xee_vee.zip](https://github.com/gohornet/hornet/files/4719303/comnet_spam_event_xee_vee.zip)
8x Intel(R) Xeon(R) CPU E3-1275 v5 @ 3.60GHz, 64 GB RAM, SSD
only console log, not running as service. Added some pprof info as well.

**Comment by QNODE-CA** [comment]
[comnet-stresstest-Jun-1.zip](https://github.com/gohornet/hornet/files/4719373/comnet-stresstest-Jun-1.zip)

0.4.0-rc13 / ubuntu 20.04 LTS
node was losing sync around 1000 tps.  VM 8 AMD TR cores, 16 GB, iSCSI storage (SSD)

**Comment by WernerderChamp** [comment]
Hetzner CPX31.
Sadly fergot to dump the logs on my temporary CX51
[hornet_logs.zip](https://github.com/gohornet/hornet/files/4719574/hornet_logs.zip)

**Comment by Nyrsta** [comment]
[hornet_stresstest_Nyrsta.gz](https://github.com/gohornet/hornet/files/4719661/hornet_stresstest_Nyrsta.gz)
0.4.0-rc13 / ubuntu 18.04
CPX51 - 16 core - autopeering - Stayed in sync during spam event

**Comment by Nyrsta** [comment]
[hornet_stresstest_nyrsta.gz](https://github.com/gohornet/hornet/files/4719763/hornet_stresstest_nyrsta.gz)
0.4.0-rc13 / ubuntu 18.04
CPX51 - 16 core - autopeering - stayed pretty good in sync during spam event

**Comment by Nyrsta** [comment]
[SoloStressTrial.zip](https://github.com/gohornet/hornet/files/4731761/SoloStressTrial.zip)
Solo Stress trial on 3 June, with confirmation rate/Milestone affected by spammer setting

**Comment by muXxer** [comment]
Thx for all these infos. Helped us a lot.
