### ISSUE TITLE
Graceful shutdown when stopping HORNET

### ISSUE THREAD

**Issue by HankMoody089** [iotaledger/hornet#477]
**Describe the bug**
When stopping HORNET with the command "sudo service hornet stop" there comes the failure that this causes a graceful shutdown with a fatal error. There is a countdown and after this is over and some time, HORNET will be stopped.

**To Reproduce**
Comes since rc13 when I stop with the command "sudo service hornet stop"

**Expected behavior**
I expected a normal shutdown of HORNET service.

**Environment information:**
 - OS: Ubuntu 20.04 - 64 bit
 - RAM: 4 GB
 - Cores: 4 Cores
 - Type: Raspberry Pi 4b and HDD USB 3.0
 - Browser MAC Safari V 13.1.1
 - HORNET version v0.4.0-rc13
 - NO PLUGINS enabled

**Additional context**
LOG: https://ybin.me/p/d84fde548ff2f254#gmHJ4x5ihBouXWaaQGiTf9x6237pDXd9zbhYVuqBmHU=

**Comment by Ohios089** [comment]
Addition: NO PLUGINS enabled

**Comment by HankMoody089** [comment]
Digged a little deeper now in this. Think it could be that I have been oos while doing the shutdown. Maybe pruning at this moment and this could cause the error upon? Just a suggestion... ;-)
