### ISSUE TITLE
Balances of Addresses without tx since snapshot not shown in explorer

### ISSUE THREAD

**Issue by alexsporn** [iotaledger/hornet#48]
**Describe the bug**
Search for an address in the tangle explorer, which hasn’t had any tx since the used snapshot. It will show 404 instead of the balance from the snapshot.

**To Reproduce**
- Go to tangle explorer
- Search for RHKWT9JUSAJIQJVDZJYI9KZLGXFFRW9IZSQG9YSCKQXMDSBAHKGEZUXNSBXHZIPVK9RPCVNEALKSTCJBXAZGOLIVKB
- See 404 error

**Expected behavior**
I expect to see the balance as in https://thetangle.org/address/RHKWT9JUSAJIQJVDZJYI9KZLGXFFRW9IZSQG9YSCKQXMDSBAHKGEZUXNSBXHZIPVK9RPCVNEALKSTCJBX

**Environment information:**
 - HORNET version 0.2.7

**Comment by luca-moser** [comment]
Fixed through https://github.com/gohornet/hornet/pull/57
