### ISSUE TITLE
Peering issues. Difficult to obtain and maintain neighbors.

### ISSUE THREAD

**Issue by easyridergs** [iotaledger/hornet#481]
After 15 minutes the node loses its neighbors and finds no more.

[hornet_peeringissues.gz](https://github.com/gohornet/hornet/files/4732123/hornet_peeringissues.gz)

**Comment by muXxer** [comment]
Please check if your ports are opened correctly.
use the comnet.thetangle.org bot in the #comnet channel

`@comnet.thetangle.org peer YOURAUTOPEERINGID`
