### ISSUE TITLE
Adding Manual Peer when acceptAnyConnection is true removes peer

### ISSUE THREAD

**Issue by centercirclesolutions** [iotaledger/hornet#488]
**Describe the bug**
When acceptAnyConnection is true and that node is paired adding them to the peering.json removes them until the next restart of HORNET

**To Reproduce**
- Ensure acceptAnyConnection is true
- Ensure Peer is connected but not in peering.json
- Add Peer to peering.json

**Expected behavior**
Peer will be in the manual list but not removed

*This was observed on the fix-autopeering branch but is likely to occur on the main develop branch (V4.0 RC13). I will update with results of tests soon*

**Comment by muXxer** [comment]
Should be fixed with #579
