### ISSUE TITLE
Comnet not getting synced after missing some milestones

### ISSUE THREAD

**Issue by TeeVeeEss** [iotaledger/hornet#502]
**Describe the bug**
I found my comnet node unsynced, no apparent reasons why it should not be synced. Pruning stopped at the latest solid milestone. Mainnet node behind the same router is synced.

**To Reproduce**
See attached log where between 15:00 and 16:00 the detected milestone jumps from 164352 to 164405.

**Expected behavior**
Even if some milestones are missed, the pruning should continue and lead to "jumping" over the missed milestones to become synced again.

**Environment information:**
 - OS: Arch Linux 5.6.6-arch1-1
 - RAM: 64 GB
 - Cores: 8 Cores
 - Type: Bare metal
 - HORNET version 0.4.0-8f64f7f

**Additional context**
[20200607_comnet_missed_milestones.gz](https://github.com/gohornet/hornet/files/4742811/20200607_comnet_missed_milestones.gz)

**Comment by muXxer** [comment]
Not a bug, you only were unlucky to get dead neighbors. You can clearly see that in your logs.

**Comment by TeeVeeEss** [comment]
I agree, no bug, but not a situation you want. It's not good to stay unsynced in such a situation. Do you see any solution besides deleting the db and restart hornet?

**Comment by muXxer** [comment]
We recommend to add a good static peer as a fallback solution to autopeering, since it's the nature of autopeering that this can happen. BTW: did you open your ports correctly? You can check that with the comnet bot in discord

**Comment by TeeVeeEss** [comment]
Yup, ports are/were open and I *do* have a static peer, but apparently that peer was not good enough or also unsynced. Any thoughts about continuing the pruning while unsynced?
