### ISSUE TITLE
panic: Error downloading snapshot file... x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by sebastienratez** [iotaledger/hornet#504]
Hi,

Using either docker-compose or docker build, I get the following error:

`panic: Error downloading snapshot file: Get "https://ls.manapotion.io/export.bin": x509: certificate signed by unknown authority`

Ubuntu 18 with latest docker-ce installed.

Ran the tutorial at https://docs.iota.org/docs/hornet/1.0/tutorials/install-hornet-docker. It looks pretty straightforward but this error keeps showing. Untouched config.json or other file.

[Full logs](https://github.com/gohornet/hornet/files/4745309/hornet.txt) attached.

**Comment by muXxer** [comment]
Fixed with #506
