### ISSUE TITLE
Misleading update available message in logs/dashboard for pre-releases

### ISSUE THREAD

**Issue by nuriel77** [iotaledger/hornet#521]
**Describe the bug**
Running version v0.4.0

The logs show:
```
2020-06-13T14:00:22Z    INFO    CLI     Update to 0.4.1-rc.1 available on https://github.com/gohornet/hornet/releases/latest
```
(note that the URL will anyhow take you to the latest official release 0.4.0)

The dashboard also indicates there's an update.
**To Reproduce**
- Run an official version e.g. 0.4.0, startup the node
- Check the logs, check the dashboard

**Expected behavior**
Don't announce that an update is available for pre-releases.
Or if there's a reason to do that, fix the URL? As it is currently pointing to the latest release and not to pre-release (in case one is available)
**Environment information:**
n/a

**Comment by alexsporn** [comment]
Fixed with #527
