### ISSUE TITLE
Hornet 0.4.1-rc1 crashed with "panic: assertion failed"

### ISSUE THREAD

**Issue by Travetown** [iotaledger/hornet#522]
**Describe the bug**
After a few hours of running Hornet crashed with 
**panic: assertion failed: write: zero-length inode key**

Restart failed with
**PANIC        Tangle        failed to retrieve snapshot milestone index: database error: key not found: Database revalidation failed! Please delete the database folder and start with a new local snapshot.**

**To Reproduce**
No idea. This error occurs irregularly and is not reproducible for me.

**Environment information:**
 - OS:  Ubuntu 20.04
 - RAM: 8 GB
 - Cores: 4 Cores
 - Type: VPS
 - HORNET version 0.4.1-rc1. Has also occurred with version 0.4.0.

[Crash-Hornet.rtf.zip](https://github.com/gohornet/hornet/files/4778103/Crash-Hornet.rtf.zip)
[Restart_Hornet.rtf.zip](https://github.com/gohornet/hornet/files/4778105/Restart_Hornet.rtf.zip)

**Comment by Travetown** [comment]
I have completely reinstalled the VPS.  Not a problem since then.

**Comment by muXxer** [comment]
Thx for feedback
