### ISSUE TITLE
Error parsing IPv6 gossip address

### ISSUE THREAD

**Issue by DollyVolley** [iotaledger/hornet#528]
**Describe the bug**
When a valid IPv6 address is used for gossip, a warning is displayed during startup stating that too many colons are contained in the address. Other "bindAddress" fields do not seem to be effected.

**To Reproduce**
- Go to /var/lib/hornet/config.json
- Set network.gossip.bindaddress to any valid IPv6 eg. [::]:15600
- Start the hornet node

**Expected behavior**
- Normal start of node
- Gossip working

**Environment information:**
 - OS: [Ubuntu 20.04]
 - RAM: [4 GB]
 - Cores: [e.g. 4 Cores]
 - Type: [Raspberry Pi 4B]
 - HORNET version [0.4.0]

**Additional context**
Warning I received with network.gossip.bindadress: [::1]:15600

![stuff](https://user-images.githubusercontent.com/46133123/84829093-761c4a00-b027-11ea-8600-109b5e1c6faf.png)

**Comment by muXxer** [comment]
Fixed with #530
