### ISSUE TITLE
not syncing after node is shutdown.

### ISSUE THREAD

**Issue by ghost** [iotaledger/hornet#536]
**Describe the bug**
initial install and start seem to trigger syncing.
when i shutdown  node,   after a day restart it again
it doesn't seem to start syncing. even with fully synched nodes in neighbours. 
 it does gossip though. 

**To Reproduce**
-start node  first time. let it sync (if you are lucky you get fullly synced somethimes it doesn't)
close node, (control C)
wait some time..

start node again
doesn't sync 
**Expected behavior**
always sync asap

**Environment information:**
 - win 10
 - RAM: [16 GB]
 - Cores: [ 8 fysical  Cores]
 - Type: [desktop pc]
 - HORNET version HORNET-0.4.1-rc1

**Additional context**
same issue 2 different pc's

**Comment by muXxer** [comment]
fixed with #535

**Comment by ghost** [comment]
haha nice one.  that was quick :)

**Comment by muXxer** [comment]
always one step ahead :)
