### ISSUE TITLE
After a restart the node was incapable syncing to the LMI

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/hornet#54]
**Describe the bug**
I let the node synchronize until it was solid and then shutdown cleanly. After the restart, the node was busy trying to get the missing transactions it needed to solidify the milestone 2 steps away: https://ybin.me/p/4145451fa46d278f#qjAZwap39dEVsraPZ8ZMDAReimpeSf8Po1udyCx9GgI=

**To Reproduce**
- Shutdown cleanly
- Wait for some milestones to be issued
- Restart
- See the solidifier getting kicked on multiple times and not being able to solidify

Only happens rarely (otherwise another issue report would already have been written)

**Expected behavior**
Given the small delta of only 2 milestones the node had from the LMI, syncing up should have taken less than 5 seconds after the restart.

**Environment information:**
 - OS: Windows 10
 - RAM: 32 GB
 - Cores: 16 cores
 - Type: Custom
 - HORNET version 0.2.7

**Comment by muXxer** [comment]
@luca-moser is this still a problem with latest dev?
