### ISSUE TITLE
pruneDatabase API feedback

### ISSUE THREAD

**Issue by viossat** [iotaledger/hornet#540]
I recently tried to use the `pruneDatabase` API command and would like to give a feedback to improve it. The automatic pruning is disabled on the node (`snapshots.pruning.enaled=false`). I'm running Hornet 0.4.1-RC1.

1. I requested a `targetIndex` which was too close from `milestoneStartIndex`. It returns error `not enough history` if `targetIndex < milestoneStartIndex - 50`. I understand the technical concept of entrypoint but as that index is far behind the current local snapshot it may be possible to prune only 1 milestone. Also Hornet used to prune 1 milestone after each new solid milestone. At least the error message should mention the minimal `targetIndex`.
2. If `targetIndex = milestoneStartIndex - 50`, it returns error `milestone (<milestoneStartIndex>) not found!: critical error`.
3. I was not able to reproduce but during a pruning I got those logs:
```
INFO	Snapshot	snapshot/pruning.go:222	Pruning milestone (1449513) took 37.204293ms. Pruned 350 transactions.
INFO	Snapshot	snapshot/pruning.go:181	Pruning milestone (1449514)...
INFO	Snapshot	snapshot/pruning.go:222	Pruning milestone (1449514) took 261.218µs. Pruned 0 transactions.
INFO	Snapshot	snapshot/pruning.go:181	Pruning milestone (1449515)...
INFO	Snapshot	snapshot/pruning.go:222	Pruning milestone (1449515) took 232.014µs. Pruned 0 transactions.
INFO	Snapshot	snapshot/pruning.go:181	Pruning milestone (1449516)...
INFO	Snapshot	snapshot/pruning.go:222	Pruning milestone (1449516) took 205.188µs. Pruned 0 transactions.
```
Three milestones were pruned of "0 transactions", but those milestones also contain other transactions in addition to their own 3 transactions. Requesting `getTrytes` on those milestone hashes still return the complete trytes.

**Comment by muXxer** [comment]
Fixed with #543
