### ISSUE TITLE
static node does not connect properly (0.4.1-rc4)

### ISSUE THREAD

**Issue by Travetown** [iotaledger/hornet#546]
**Describe the bug**
One of my static neighbors was "waiting". His node (0.4.0) indicated that my node is unsynced. But my node was synced. (Mainnet) Only after restarting my node has established a connection with his node.

**To Reproduce**
I have no idea at all

**Expected behavior**
Great connection with the static peers

**Environment information:**
 - OS: Ubuntu 20.04
 - RAM:  8 GB
 - Cores: 4 Cores
 - Type: VPS
  - HORNET version 0.4.1-rc4

**Additional context**
2020-06-25T15:25:28+02:00	INFO	Peering	connected with xx.xxx.xxx.xx:15600 [alias: xxx-1] [feature set(s): STING]
2020-06-25T15:25:28+02:00	WARN	Peering	error EOF

This warning can often be found in the log. Not just for static peers

**Comment by muXxer** [comment]
Should be fixed with #547
