### ISSUE TITLE
Node stops syncing after 4 days

### ISSUE THREAD

**Issue by TeeVeeEss** [iotaledger/hornet#561]
**Describe the bug**
After 4 days without a problem my node suddenly is unsynced and some 400 Milestones behind.

**To Reproduce**
I really don't know. I have 3 static peers (2 IRI, 1 Hornet) which are rock solid and always synced.

**Expected behavior**
Just keep running synced or a clear explanation why the Solidifier stops.

**Environment information:**
 - OS: Ubuntu 18.04
 - RAM: 8 GB
 - Cores: 4 Cores
 - Type: Strato VPS
 - HORNET version 0.4.1

**Additional context**
Added a full pprof, a screenshot of the current status and some Tangle-logging of the last 2 days.
![image](https://user-images.githubusercontent.com/17521100/86949836-8bc8ef00-c14f-11ea-9925-95e6b33aed47.png)
[hornet_full_pprof.log.gz](https://github.com/gohornet/hornet/files/4892194/hornet_full_pprof.log.gz)
[Hornet_Tangle_logging_last_2_days.log.gz](https://github.com/gohornet/hornet/files/4892225/Hornet_Tangle_logging_last_2_days.log.gz)

Will keep the node running if more info or logging is needed.

**Comment by IoTMOD** [comment]
Hi @TeeVeeEss,
thanks for your bug report.
We have seen a lot of problems at higher TPS with this type of VPS / provider lately (slow disc I/O)

About 460 MS ago (MS 1470400) the healthy spam started again, this could be the reason (disc I/O limit).
![image](https://user-images.githubusercontent.com/34713374/86952382-32fb5580-c153-11ea-830c-bd8cefa04d8c.png)

**Comment by TeeVeeEss** [comment]
Hmm, ok, that sounds reasonable. Do you (the HORNET team) see some kind of solution for the I/O bottleneck? It could lead to losing nodes or yet more concentration of nodes on specific hosters.

**Comment by muXxer** [comment]
If you run a node, or any type of software, it needs some resources. If you don't have them, the software can't run properly. It's unfortunately as easy as that :)
