### ISSUE TITLE
public node crashed

### ISSUE THREAD

**Issue by QNODE-CA** [iotaledger/hornet#565]
**Describe the bug**

node panicked:
panic: Ledger diff for milestone 1489898 creates negative balance for address ���uUv?���1�hvP�5��N&R�P��GZ��+��I ��dd�: current 0, diff -26

database corrupted, currently revalidating...

**To Reproduce**
not sure, but timing of at least another public node neighbor of mine crashing in a short time might be significant

**Expected behavior**
node in sync, functioning normally

**Environment information:**

 - OS:  Ubuntu 20.04 LTS
 - RAM:  32 GB
 - Cores:  6 vCore
 - Type:  AMD TR
 - HORNET version 0.4.1

**Additional context**

req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, LSMI/LMI: 1489897/1489897, TPS (in/new/out): 00110/00029/00075
2020-07-20T18:05:34-07:00       INFO    Tangle  Run solidity check for Milestone (1489898)...
2020-07-20T18:05:34-07:00       INFO    Tangle  Solidifier finished: txs: 2, collect: 0s, total: 0s
2020-07-20T18:05:34-07:00       INFO    Tangle  Valid milestone detected! Index: 1489898, Hash: KFZRQWVEBNDPVPRCZOPAHKSKFHKAGEJWESRDAEPYGFQMNBEKUCWMJLACTB9ORSUTKSFUMP9UBYJC99999
req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, LSMI/LMI: 1489897/1489898, TPS (in/new/out): 00102/00029/00077
panic: Ledger diff for milestone 1489898 creates negative balance for address ���uUv?���1�hvP�5��N&R�P��GZ��+��I ��dd�: current 0, diff -26

goroutine 309 [running]:
github.com/gohornet/hornet/pkg/model/tangle.ApplyLedgerDiffWithoutLocking(0xc010299770, 0x1110016bbea, 0x29e16c0, 0x31)
        /opt/hornet/pkg/model/tangle/ledger_db.go:265 +0xa2a
github.com/gohornet/hornet/plugins/tangle.confirmMilestone(0xc00016bbea, 0xc01020f560)
        /opt/hornet/plugins/tangle/confirmation.go:124 +0xf75
github.com/gohornet/hornet/plugins/tangle.solidifyMilestone(0x16bbea)
        /opt/hornet/plugins/tangle/solidifier.go:385 +0x670
github.com/gohornet/hornet/plugins/tangle.configureTangleProcessor.func3(0xc0103cafc0, 0x2, 0x2, 0xc00675ff80)
        /opt/hornet/plugins/tangle/tangle_processor.go:51 +0x8c
github.com/iotaledger/hive.go/workerpool.(*WorkerPool).startWorkers.func1(0xc000156140)
        /root/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200623195435-4722a3081401/workerpool/workerpool.go:158 +0x1ad
created by github.com/iotaledger/hive.go/workerpool.(*WorkerPool).startWorkers
        /root/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200623195435-4722a3081401/workerpool/workerpool.go:134 +0x5e

**Comment by Travetown** [comment]
My two nodes are also no longer alive. Hornet aborts when syncing with MS 1489898 and then restarts.

2020-07-21T08:20:49+02:00        INFO        Tangle        New solid milestone: 1489897, 0.00 TPS, 7.73 CTPS, 0.00% conf.rate
2020-07-21T08:20:49+02:00        INFO        Tangle        Run solidity check for Milestone (1489898)...
2020-07-21T08:20:49+02:00        INFO        Tangle        Solidifier finished: txs: 1487, collect: 92ms, total: 282ms
[148B blob data]
goroutine 298 [running]:
github.com/gohornet/hornet/pkg/model/tangle.ApplyLedgerDiffWithoutLocking(0xc005559770, 0x80016bbea, 0x29dd6a0, 0x31)
         /__w/hornet/hornet/pkg/model/tangle/ledger_db.go:265 +0xa2a
 github.com/gohornet/hornet/plugins/tangle.confirmMilestone(0xc00016bbea, 0xc01aeab640)
         /__w/hornet/hornet/plugins/tangle/confirmation.go:124 +0xf75
 github.com/gohornet/hornet/plugins/tangle.solidifyMilestone(0x0)
         /__w/hornet/hornet/plugins/tangle/solidifier.go:385 +0x670
 github.com/gohornet/hornet/plugins/tangle.configureTangleProcessor.func3(0xc0063d2e80, 0x2, 0x2, 0xc0004627e0)
         /__w/hornet/hornet/plugins/tangle/tangle_processor.go:51 +0x8c
 github.com/iotaledger/hive.go/workerpool.(*WorkerPool).startWorkers.func1(0xc0004dc230)
         /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200623195435-4722a3081401/workerpool/workerpool.go:158 +0x1ad
 created by github.com/iotaledger/hive.go/workerpool.(*WorkerPool).startWorkers
         /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200623195435-4722a3081401/workerpool/workerpool.go:134 +0x5e
 runtime: note: your Linux kernel may be buggy
 runtime: note: see https://golang.org/wiki/LinuxKernelSignalVectorBug
 runtime: note: mlock workaround for kernel bug failed with errno 12
 hornet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
 hornet.service: Failed with result 'exit-code'.

**Comment by MaKla89** [comment]
Same here!

**VPS:** Hetzner CPX21, AMD Epyc, 3 vCores, 4GB RAM

This screenshot was taken after deleting the mainnetdb but NOT the snapshot and trying to sync:

<img width="1094" alt="HornetCrash" src="https://user-images.githubusercontent.com/33317175/88022986-8a74ca80-cb30-11ea-9d5d-f47101476e8c.PNG">

Deleting mainnetdb/ and the snapshot did help (only deleting the mainnetdb did NOT help, after syncing to 1489897 my node crashed as well unless I delete the snapshot)

**Comment by bztes** [comment]
Same error message for me. My both nodes crashed at around 3am CEST. ARM and AMD64.
[0305-firstcrash-arm64.txt](https://github.com/gohornet/hornet/files/4951831/0305-firstcrash-arm64.txt)

**Comment by rajivshah3** [comment]
Same for me:

```
Jul 21 01:05:33 localhost docker[1661902]: req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, LSMI/LMI: 1489897/1489897, TPS (in/new/out): 00080/00029/00139
Jul 21 01:05:34 localhost docker[1661902]: 2020-07-21T01:05:34Z        INFO        Tangle        Valid milestone detected! Index: 1489898, Hash: KFZRQWVEBNDPVPRCZOPAHKSKFHKAGEJWESRDAEPYGFQMNBEKUCWMJLACTB9ORSUTKSFUMP9UBYJC99999
Jul 21 01:05:34 localhost docker[1661902]: 2020-07-21T01:05:34Z        INFO        Tangle        Run solidity check for Milestone (1489898)...
Jul 21 01:05:34 localhost docker[1661902]: 2020-07-21T01:05:34Z        INFO        Tangle        Solidifier finished: txs: 2, collect: 0s, total: 0s
Jul 21 01:05:34 localhost docker[1661902]: [148B blob data]
Jul 21 01:05:34 localhost docker[1661902]: goroutine 313 [running]:
Jul 21 01:05:34 localhost docker[1661902]: github.com/gohornet/hornet/pkg/model/tangle.ApplyLedgerDiffWithoutLocking(0xc017f57770, 0x6c9e0016bbea, 0x29dd6a0, 0x31)
Jul 21 01:05:34 localhost docker[1661902]:         /__w/hornet/hornet/pkg/model/tangle/ledger_db.go:265 +0xa2a
Jul 21 01:05:34 localhost docker[1661902]: github.com/gohornet/hornet/plugins/tangle.confirmMilestone(0xc00016bbea, 0xc017496a80)
Jul 21 01:05:34 localhost docker[1661902]:         /__w/hornet/hornet/plugins/tangle/confirmation.go:124 +0xf75
Jul 21 01:05:34 localhost docker[1661902]: github.com/gohornet/hornet/plugins/tangle.solidifyMilestone(0x16bbea)
Jul 21 01:05:34 localhost docker[1661902]:         /__w/hornet/hornet/plugins/tangle/solidifier.go:385 +0x670
Jul 21 01:05:34 localhost docker[1661902]: github.com/gohornet/hornet/plugins/tangle.configureTangleProcessor.func3(0xc012ec82c0, 0x2, 0x2, 0xc012c80720)
Jul 21 01:05:34 localhost docker[1661902]:         /__w/hornet/hornet/plugins/tangle/tangle_processor.go:51 +0x8c
Jul 21 01:05:34 localhost docker[1661902]: github.com/iotaledger/hive.go/workerpool.(*WorkerPool).startWorkers.func1(0xc00077e140)
Jul 21 01:05:34 localhost docker[1661902]:         /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200623195435-4722a3081401/workerpool/workerpool.go:158 +0x1ad
Jul 21 01:05:34 localhost docker[1661902]: created by github.com/iotaledger/hive.go/workerpool.(*WorkerPool).startWorkers
Jul 21 01:05:34 localhost docker[1661902]:         /github/home/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200623195435-4722a3081401/workerpool/workerpool.go:134 +0x5e
Jul 21 01:05:34 localhost docker[1661902]: runtime: note: your Linux kernel may be buggy
Jul 21 01:05:34 localhost docker[1661902]: runtime: note: see https://golang.org/wiki/LinuxKernelSignalVectorBug
Jul 21 01:05:34 localhost docker[1661902]: runtime: note: mlock workaround for kernel bug failed with errno 12
Jul 21 01:05:35 localhost systemd[1]: hornet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 21 01:05:35 localhost systemd[1]: hornet.service: Failed with result 'exit-code'.
```

- OS: Ubuntu 20.04 LTS
- RAM: 15.6 GB
- Cores: 6
- Type: Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
- HORNET version 0.4.1 (with `hornet-playbook`)

**Comment by muXxer** [comment]
Please delete your DB and export.bin to redownload the latest snapshot. There was an error in a snapshot derived from one node that some nodes have been using.

The latest local snapshots on Manapotion are unaffected for the past couple weeks. The IF has also verified that these snapshots match the COO ledger state. You can verify the correct state of the Manapotion snapshots by syncing your HORNET node from the last global snapshot yourself. It is no problem in the HORNET source code. Issue closed.
