### ISSUE TITLE
Index out of range in plugins/webapi/pow.go causes a panic

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/hornet#573]
**Describe the bug**
I'm not entirely sure what triggers this error, but I've seen it a few times and @taraszka just reported seeing it as well. 

```
2020/07/23 16:28:01 [Recovery] 2020/07/23 - 16:28:01 panic recovered:
runtime error: index out of range [0] with length 0
/usr/local/go/src/runtime/panic.go:88 (0x43dc22)
/__w/hornet/hornet/plugins/webapi/pow.go:71 (0xe7e0b3)
/__w/hornet/hornet/plugins/webapi/api.go:73 (0xe81a49)
/github/home/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xcd418a)
/__w/hornet/hornet/plugins/webapi/plugin.go:65 (0xe82aea)
/github/home/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xcd418a)
/github/home/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83 (0xce788f)
/github/home/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xcd418a)
/github/home/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 (0xcddf65)
/github/home/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 (0xcdd67c)
/usr/local/go/src/net/http/server.go:2807 (0x73a4c2)
/usr/local/go/src/net/http/server.go:1895 (0x735e3b)
/usr/local/go/src/runtime/asm_amd64.s:1373 (0x4731b0)
```

The stacktrace points to this line:
https://github.com/gohornet/hornet/blob/7ab6ffe9102a2d751dc03f2a8dd3962d2a0fa0da/plugins/webapi/pow.go#L71

However, I'm not sure why `txs` would have a length of 0 if `err` was not nil:

https://github.com/gohornet/hornet/blob/7ab6ffe9102a2d751dc03f2a8dd3962d2a0fa0da/plugins/webapi/pow.go#L63-L75

**To Reproduce**
Not sure, seems related to `attachToTangle`

**Expected behavior**
No panic occurs

**Environment information:**
 - OS: Ubuntu 20.04
 - RAM: 15.6 GB
 - Cores: 6 cores
 - Type: VPS
 - Browser [e.g. chrome, safari] (e.g. for HORNET Dashboard issues)
 - HORNET version: 0.4.2

**Additional context**
Also seen on HORNET 0.4.1

**Comment by muXxer** [comment]
Fixed with #579
