### ISSUE TITLE
Hornet Crashed with Panic Error - Missing Milestone

### ISSUE THREAD

**Issue by centercirclesolutions** [iotaledger/hornet#580]
**Issue**
Hornet Server Crashed with Panic

**Environment information:**
 - Hetzner CPX41 - Ubuntu 20.04
 - HORNET Version 0.5.0-rc6-5c439bc

**Log*
[Log File](https://github.com/gohornet/hornet/files/4997842/Hornet_Comnet_Error01.log)

**Comment by muXxer** [comment]
Did your node crashed already before, and the DB was revalidated?

**Comment by centercirclesolutions** [comment]
Here's the whole log. Yes it looked like it revalidated @muXxer 
[Hornet_Comnet_Error01.log](https://github.com/gohornet/hornet/files/4997904/Hornet_Comnet_Error01.log)

**Comment by QNODE-CA** [comment]
Looks like a similar issue just occurred on my CX21 (4GB mem profile), 5000 MS delay.

hornet crashed, and was restarted.  The database was corrupted, and the revalidation process started.  Soon after completing, a second crash:
`panic: Milestones missing between (1509865) and (1509867).`


[1st crash, db revalidation, 2nd crash after that.txt](https://github.com/gohornet/hornet/files/5013015/1st.crash.db.revalidation.2nd.crash.after.that.txt)

**Comment by muXxer** [comment]
@luca-marchiori do you have the logs why it crashed the first time?
we know that revalidation is broken unfortunately. But it's hard to fix before step 2, because of bundles.

**Comment by QNODE-CA** [comment]
> @luca-marchiori do you have the logs why it crashed the first time?
> we know that revalidation is broken unfortunately. But it's hard to fix before step 2, because of bundles.

I included what I had in the log file (1st crash) - unfortunatley is not very informative:

2020-08-02T11:35:31-07:00       INFO    Peering connected with 78.47.117.143:15600 [feature set(s): STING] [autopeered WaAzWmipiuv]
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^>

  *** this was me manually restarting the node: **
2020-08-02T13:26:13-07:00       INFO    CLI     Loading plugins ...

I'll try to collect more info if this re-occurs.

**Comment by muXxer** [comment]
Should be fixed with #593
