### ISSUE TITLE
node is not syncing when i connect it to the comnet

### ISSUE THREAD

**Issue by brando14** [iotaledger/hornet#581]
hi, i have been trying to start building an iota node using the hornet on a docker image.

First try connecting it to the mainnet and everything worked perfectly.

but they recommended me to test the transfer of tokens in a test network and so I found that the devnet is no longer supported,

Then try connecting that node to the comnet.

but once I did that the node has not yet synchronized and stays in that state for a long time.

this is the config_comnet.json file 

{
  "useProfile": "auto",
  "httpAPI": {
    "basicAuth": {
      "enabled": false,
      "username": "",
      "passwordHash": "",
      "passwordSalt": ""
    },
    "excludeHealthCheckFromAuth": false,
    "permitRemoteAccess": [
      "getNodeInfo",
      "getBalances",
      "checkConsistency",
      "getTransactionsToApprove",
      "getInclusionStates",
      "getNodeAPIConfiguration",
      "wereAddressesSpentFrom",
      "broadcastTransactions",
      "findTransactions",
      "storeTransactions",
      "getTrytes"
    ],
    "whitelistedAddresses": [],
    "bindAddress": "0.0.0.0:14265",
    "limits": {
      "bodyLengthBytes": 1000000,
      "findTransactions": 1000,
      "getTrytes": 1000,
      "requestsList": 1000
    }
  },
  "dashboard": {
    "bindAddress": "0.0.0.0:8081",
    "theme": "default",
    "dev": false,
    "basicAuth": {
      "enabled": false,
      "username": "",
      "passwordHash": "",
      "passwordSalt": ""
    }
  },
  "db": {
    "path": "comnetdb"
  },
  "snapshots": {
    "loadType": "local",
    "local": {
      "depth": 50,
      "intervalSynced": 200,
      "intervalUnsynced": 1000,
      "path": "snapshots/comnet/export.bin",
      "downloadURLs": [
        "https://ls.manapotion.io/comnet/export.bin"
      ]
    },
    "global": {
      "path": "snapshot.csv",
      "spentAddressesPaths": [],
      "index": 0
    },
    "pruning": {
      "enabled": true,
      "delay": 1000
    }
  },
  "spentAddresses": {
    "enabled": true
  },
  "coordinator": {
    "address": "YBWDHGHUEB9KSOPONTLTOSSKITIBE9MXPASCLREDNV9HEABYBPTHRQGWNJWQFSYAYZRDXXIOZHWBC9DWC",
    "securityLevel": 2,
    "merkleTreeDepth": 23,
    "mwm": 10,
    "stateFilePath": "coordinator.state",
    "merkleTreeFilePath": "coordinator.tree",
    "intervalSeconds": 60,
    "checkpointTransactions": 5
  },
  "network": {
    "preferIPv6": false,
    "gossip": {
      "bindAddress": "0.0.0.0:15600",
      "reconnectAttemptIntervalSeconds": 60
    },
    "autopeering": {
      "bindAddress": "0.0.0.0:14626",
      "runAsEntryNode": false,
      "entryNodes": [
        "iotaCrvEWGfaeA1HutcULjD4uZnPhEnD5xNGfGs8vhe@enter.comnet.thetangle.org:14647",
        "GLZAWBGqvm6ZRT7jGMFAKyUJNPdvx4i5A1GPRZbGS6C9@enter.comnet.hornet.zone:14627",
        "J1Hn5r9pS5FkLeYqXWstC2Zyjxj73grEWvjuene3qjM9@entrynode.comnet.tanglebay.org:14636"
      ],
      "seed": ""
    }
  },
  "tipsel": {
    "belowMaxDepthTransactionLimit": 100000,
    "maxDepth": 5
  },
  "node": {
    "alias": "",
    "showAliasInGetNodeInfo": false,
    "disablePlugins": [],
    "enablePlugins": []
  },
  "logger": {
    "level": "info",
    "disableCaller": true,
    "encoding": "console",
    "outputPaths": [
      "stdout"
    ]
  },
  "warpsync": {
    "advancementRange": 50
  },
  "spammer": {
    "address": "HORNET99INTEGRATED99SPAMMER999999999999999999999999999999999999999999999999999999",
    "depth": 1,
    "message": "Spamming with HORNET tipselect",
    "tag": "HORNET99INTEGRATED99SPAMMER",
    "cpuMaxUsage": 0.8,
    "tpsRateLimit": 0.0,
    "bundleSize": 1,
    "valueSpam": false,
    "workers": 0
  },
  "graph": {
    "webRootPath": "IOTAtangle/webroot",
    "domain": "",
    "webSocket": {
      "uri": ""
    },
    "bindAddress": "localhost:8083",
    "networkName": "meets HORNET comnet",
    "explorerTxLink": "http://localhost:8081/explorer/tx/",
    "explorerBundleLink": "http://localhost:8081/explorer/bundle/"
  },
  "monitor": {
    "tangleMonitorPath": "tanglemonitor/frontend",
    "domain": "",
    "initialTransactions": 15000,
    "remoteApiPort": 4433,
    "webBindAddress": "localhost:4434",
    "apiBindAddress": "localhost:4433",
    "webSocket": {
      "uri": ""
    }
  },
  "mqtt": {
    "config": "mqtt_config.json"
  },
  "zmq": {
    "bindAddress": "localhost:5556"
  },
  "profiling": {
    "bindAddress": "localhost:6060"
  },
  "prometheus": {
    "bindAddress": "localhost:9311",
    "goMetrics": false,
    "processMetrics": false,
    "promhttpMetrics": false
  }
}

this the docker command:

` sudo docker run --rm -v $(pwd)/config_comnet.json:/app/config.json:ro -v $(pwd)/snapshots/comnet:/app/snapshots/comnet -v $(pwd)/comnetdb:/app/comnetdb --name hornet --net=host gohornet/hornet:v0.4.2
`

If anyone can tell me why this is, they would greatly appreciate it.

**Comment by muXxer** [comment]
comnet switched to chrysalis pt1.
you need to use the chrysalis branch or the 0.5.0 beta releases.

**Comment by brando14** [comment]
thank you my friend,
could you please provide me the branch link?

**Comment by muXxer** [comment]
https://github.com/gohornet/hornet/tree/chrysalis

**Comment by brando14** [comment]
thank you :)  it worked
