### ISSUE TITLE
0.5.0-rc6 - Node still running, but no values on Dashboard

### ISSUE THREAD

**Issue by QNODE-CA** [iotaledger/hornet#586]
**Describe the bug**

Dashboard for Comnet node stopped displaying any values.  According to CLI, node is still synced:

{
  "appName": "HORNET",
  "appVersion": "0.5.0-rc6",
  "latestMilestone": "GHHYDO9MVJXCTJWZYAKPFEQJFDFIFHTQTSQDMKO9RWDHT9SHAT9JMRNTFHOFOENYXYXXOSHN9JEIAY999",
  "latestMilestoneIndex": 638803,
  "latestSolidSubtangleMilestone": "GHHYDO9MVJXCTJWZYAKPFEQJFDFIFHTQTSQDMKO9RWDHT9SHAT9JMRNTFHOFOENYXYXXOSHN9JEIAY999",
  "latestSolidSubtangleMilestoneIndex": 638803,
  "isSynced": true,
  "milestoneStartIndex": 637801,
  "lastSnapshottedMilestoneIndex": 638702,
  "neighbors": 2,
  "time": 1596470050000,
  "tips": 3,
  "transactionsToRequest": 0,
  "features": [
    "WereAddressesSpentFrom"
  ],
  "coordinatorAddress": "UOMFQOULWQLXQQHFMFRQQTRDKDHVMRFFEGZ9LDU9TFZZ9CHDLZSIAHA9MXNSLYOERCHDUVDFEEZAEOBEW",
  "duration": 0
}

**To Reproduce**

Not sure

**Expected behavior**

Dashboard to continue display information

**Environment information:**
 - OS: Ubuntu 20.04 LTS
 - RAM:  8 GB
 - Cores:  4 vCore
 - Type: AMD TR
 - Browser  chrome, firefox
 - HORNET version: 0.5.0 (crysalis)  a0415a2

**Additional context**

logs, memory profile, screenshot

![blank dashboard](https://user-images.githubusercontent.com/10619487/89213375-d8022600-d579-11ea-8d42-33edf33ef315.png)
[comnet log.zip](https://github.com/gohornet/hornet/files/5017550/comnet.log.zip)
[memory_profile.pdf](https://github.com/gohornet/hornet/files/5017552/memory_profile.pdf)

After Ctrl+C hornet did not manage to shutdown cleanly.  Including log after shutdown request

[comnet_0.5.0-rc6.txt](https://github.com/gohornet/hornet/files/5017977/comnet_0.5.0-rc6.txt)

**Comment by iConMayrhofer** [comment]
For me this error always occurred after/under heavy load.
[out.log](https://github.com/gohornet/hornet/files/5017094/out.log)
It must have happened sometime between 12:00-14:00. But I'm not sure.  
I also have bigger logfiles if needed. But I'm pretty sure that it happened in the mentioned timespan.

**Comment by Dr-Electron** [comment]
For me this error always occurred after/under heavy load.
[out.log](https://github.com/gohornet/hornet/files/5017115/out.log)
It must have happened sometime between 12:00-14:00. But I'm not sure.
I also have bigger logfiles if needed. But I'm pretty sure that it happened in the mentioned timespan.

**Comment by muXxer** [comment]
I need a full goroutine stack dump to solve that :(
Could someone please create one?

**Comment by ericvrp** [comment]
rc7: [goroutine.txt](https://github.com/gohornet/hornet/files/5034775/goroutine.txt)

**Comment by Dr-Electron** [comment]
[stackdump.txt](https://github.com/gohornet/hornet/files/5035273/stackdump.txt)

**Comment by centercirclesolutions** [comment]
Here's my info

[full stack Dump](https://ybin.me/p/882aac8f79055ee8#GxEO5nyPP+3GdNXDB2hXhcqECKC1y25Tu1uPxGrPwYM=)
[Goroutine](https://ybin.me/p/bdf04e0b5cda3544#GxpKOv7afnpp6MrffaEhgtSGlbbxBCU3y8xIyAo1cWY=)
[Alloc](https://ybin.me/p/ea20df638bbedfe7#o5wvwaw8+UsODV/X910zN2LiShmXPWWlSjW3xBjVTkQ=)
[trace_hornet.zip](https://github.com/gohornet/hornet/files/5039390/trace_hornet.zip)

**Comment by muXxer** [comment]
Thx for the stacktraces.... now I see the problem.... man, that's what I call a real deadlock :)

**Comment by alexsporn** [comment]
Fixed in #597
