### ISSUE TITLE
One static peer party in Waiting state and the other not

### ISSUE THREAD

**Issue by ericvrp** [iotaledger/hornet#596]
**Describe the bug**
One of my static peers shows me as synced yet my dashboard has him in Waiting state.

**To Reproduce**
This happened after recovery from the first wave in todays spam event. No spamming was happening at the time I noticed this.

**Expected behavior**
Both to be synced or at least in a non waiting state

**Environment information:**
 - OS: [e.g. Ubuntu 20.04]
 - RAM: [e.g. 16 GB]
 - Cores: [e.g. 4 Cores, 8 threads]
 - Type: [e.g. Dedicated server, ...]
 - Browser [e.g. Firefox on Windows] (e.g. for HORNET Dashboard issues)
 - HORNET version [0.5.0-rc8]

**Additional context**
![A2B](https://user-images.githubusercontent.com/4216292/89687716-ff9e1900-d900-11ea-874c-6f64c181ba41.png)
![B2A](https://user-images.githubusercontent.com/4216292/89687724-02007300-d901-11ea-8f04-6034c296a7d3.png)

**Comment by Travetown** [comment]
I noticed that my static neighbors change to the "waiting" status if I edit the peering.json while the node is running. The neighbors remain in this status even after a restart of Hornet. No error can be seen in the log. There is only the entry "handshaking" and then "connected".
Experience has shown that this status remains until the other side also performs a restart.

**Comment by muXxer** [comment]
Should be fixed in #650
