### ISSUE TITLE
coldstart setting in config

### ISSUE THREAD

**Issue by ericvrp** [iotaledger/hornet#598]
**Is your feature request related to a problem? Please describe.**
Whenever we tell people to remove their database and export.bin they need to find the locations depending on method of installation and they risk remove the wrong thing.

**Describe the solution you'd like**
Having “coldstart”: false in the config enables everyone to use the same CLI command (—coldstart true) to remove the correct database and correct snapshot. 

**Describe alternatives you've considered**
I find adding a top level setting not very elegant but adding it to either “db” or “snapshots” would feel like it will have a side effect because it also effects the other.

**Comment by muXxer** [comment]
Added with #996
