### ISSUE TITLE
reload on “WS disconnected”

### ISSUE THREAD

**Issue by ericvrp** [iotaledger/hornet#599]
**Is your feature request related to a problem? Please describe.**
We tell dashboard users to refresh their webpage when they didn’t notice that the web socket got disconnected. On iOS this happens to me a lot when I switch to another tab in Firefox and come back to the Hornet dashboard after a couple of minutes. 

**Describe the solution you'd like**
Would it be an idea to refresh automatically after a few seconds whenever we detect the web socket got disconnected. This way the user still can see the error message for some time to know that their is potentially an issue that need to be resolved.
 
I had something like this in mind.
```
if (!global.WSdisconnected && web socket is disconnected) {
  global.WSdisconnected = true;
  setTimeout(location.reload, 3000);
}
```

**Describe alternatives you've considered**
Alternatively we re-open the web socket connection. But I assume this has been tried and did not work for some reason.

**Comment by alexsporn** [comment]
Fixed with #605
