### ISSUE TITLE
BasicAuth not allowing certain characters in password

### ISSUE THREAD

**Issue by alexeiffel** [iotaledger/hornet#6]
When using a password with * an error message occurs:
panic: [ PANIC ] NodeConfig: Error while loading config from .: While parsing config: invalid character '*' in string escape code

Same happens when using \ etc.

**Comment by muXxer** [comment]
This works for me...
```
    "basic_auth": {
      "enabled": true,
      "username": "muxxer",
      "password": "test*123"
    }
```
Which OS are you running? Did you compiled the source on your own? Which GO version?

Do you have a JSON or YML file?

**Comment by alexeiffel** [comment]
I use Debian 10 with the HORNET-0.1.0_Linux_x86_64.tar.gz from the release page. The config.json file was included and I only changed the password to a secure one with 32 characters containing special characters. Of course I also set "enabled" to true.

I tried a short password without special characters and it works.

**Comment by muXxer** [comment]
Maybe you have other special characters in it? Can you remove special character by character until it works?

**Comment by alexeiffel** [comment]
I created a new one (since I didn't save the first one).

`"password": "*a[PmoH?C'2^$%\MO*Iy9^Uta0M/64wo1P"` gives me the error

`2019/12/12 21:40:51 [ PANIC ] NodeConfig: Error while loading config from .: While parsing config: invalid character 'M' in string escape code
panic: [ PANIC ] NodeConfig: Error while loading config from .: While parsing config: invalid character 'M' in string escape code`

**Comment by muXxer** [comment]
you can't use `\` because it is an escape sequence! That is not HORNET related but json.
If you want `\`, you have to type `\\`

**Comment by muXxer** [comment]
<https://www.freeformatter.com/json-escape.html>
`Backslash is replaced with \\`

**Comment by alexeiffel** [comment]
Oh wow I never thought about this. You are right.
