### ISSUE TITLE
Create an optimized DietPi image with Hornet

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/hornet#60]
Requirements:
* Create a DietPi image with Hornet
* The Hornet installation should be easily upgradable

**Comment by bernardoaraujor** [comment]
these might help:
https://github.com/bernardoaraujor/meta-iota/wiki/HoneyComb-Distro

https://github.com/bernardoaraujor/meta-iota/wiki/BitBaking-HoneyComb-for-the-Raspberry-Pi

**Comment by luca-moser** [comment]
@bernardoaraujor @Brootux We would like to split the bounty between you two. Would you guys be so kind and tell us whether this is ok and then make out which of you is going to receive the funds and then send the other half to the other?

**Comment by Brootux** [comment]
sounds good for me, im also okay with "receiving as the second person"

**Comment by bernardoaraujor** [comment]
@Brootux how can I get in touch with you?

**Comment by Brootux** [comment]
@bernardoaraujor Should i simply post my receive address here? Does it need any more discussion? ;)

**Comment by luca-moser** [comment]
release bounty to @bernardoaraujor

**Comment by bernardoaraujor** [comment]
FQYGIJYKHZTLMTUMZKJKHKMWBCQTKDCGPWCRBYAAPLZRULNNAOFXQZCYQCAGUZNZLEAMTPIZQSYGGZRXAJKVCGLOJW

**Comment by Brootux** [comment]
DIKVKAUGZNTKTVJFM9HAWDUYZBYFOUATRBCWLSNCQRBYMQWZCKKCLLJFAIZNEYHEZFXCWJRRMHRPRYWFXBXGQCHJLW

**Comment by bernardoaraujor** [comment]
@Brootux bundle O9XHDXVRAOXEPIYZJWXBEKHCKAJBU9FWWLQJJIJJVVEYJVJYNZZHOLYEJDPAFCSHBAAWXKWGSJONRZBJA

**Comment by Brootux** [comment]
Transaction received, you are an honorable man @bernardoaraujor 

Thanks everyone, this is the future, create more bounty issues ;)
