### ISSUE TITLE
Support for API to determine if a transaction is above max depth

### ISSUE THREAD

**Issue by laumair** [iotaledger/hornet#603]
**Is your feature request related to a problem? Please describe.**
An endpoint for checking if a transaction is above max depth should be added to the node software. Current client side implementations calculate this wrt [time](https://github.com/laumair/trinity-wallet/blob/develop/src/shared/libs/iota/transfers.js#L141). The proposed endpoint would help client applications in promotion or reattachment implementations.

**Describe the solution you'd like**
An endpoint `isBelowMaxDepth()` or `isValidTip()` should be added that accepts a transaction hash and informs the requester whether a transaction is below max depth.

**Comment by muXxer** [comment]
Added getTipInfo in #608
