### ISSUE TITLE
Feature request for removing neighbors that have only increasing "Dropped Packets"

### ISSUE THREAD

**Issue by ericvrp** [iotaledger/hornet#604]
**Is your feature request related to a problem? Please describe.**
Some peers on the /neighbors page are making no progress and should probably be removed after some time.

**Describe the solution you'd like**
When "Dropped packets" increases while metrics  "All", "New", "Stale" and "Sent" remain the same I would like to suggest we drop the neighbor. During the latest spam-event more and more nodes could not keep up while good nodes seemed to have a problem finding other healthy nodes. Maybe this helps a little.

**Describe alternatives you've considered**
Perhaps the interval should be longer that the refreshrate of the /neighbors page?

**Comment by muXxer** [comment]
Added in #608
