### ISSUE TITLE
Find the easter egg

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/hornet#61]
Be the first person to comment about the easter egg within Hornet with a description on how to access it.

**Comment by Thoralf-M** [comment]
Enable the dashboard and search for `420` in the explorer

**Comment by muXxer** [comment]
release bounty to @Thoralf-M

**Comment by Thoralf-M** [comment]
RMJCPSTWUVXLRNOGNMNJZGKXXFIKTQTVAQPXXOCGOPXNMIWSARRUV9GSCIQMDFIMFNTTNNF9CEKIRAMPZIYALDLEIB
