### ISSUE TITLE
Kicked out Neighbors

### ISSUE THREAD

**Issue by Sn00pyoo7** [iotaledger/hornet#614]
**Describe the bug**
Node is up since 2 Days with one static neighbor. After adding a second one, it kicked out the first, and dont added the second. 
Now i just have autopeered neighbors since 30 minutes.

After a restart, the first neighbor was instant peered, and could catch up very fast :-) But at his side i was not showing in his dashboard with my dns anymore, but with my ip.

The second neighbor did not connect to me, was just waiting at both sides. Waited for another 10 minutes (not helped).
He restarted, then we was instant peered. But at my side he showed not with his dns, but with his ip.

From the fist neighbor:
connected with IPHERE [alias: Snoopy007] [feature set(s): Chrysalis-Pt1]
Peering        error EOF

**To Reproduce**
- Added a second neighbor at high tps (600-900)

**Update a day later:**
Current 200tps, both static neighbors was kicked out. 
Restarted my node.
Both neighbors was on waiting. Tried to re-add a neighbor, dont helped.
On my neighbors side i showed as "not connected".... He restarted his node.

After this, on his side: `connected with (IPHERE) [alias: Snoopy007] [feature set(s): Chrysalis-Pt1]
error EOF
error failed to send message: write tcp (IPHERE)->(IPHERE): write: broken pipe `

On my side: `INFO Peering handshaking with incoming connection from (IPHERE)
WARN Peering error (IPHERE): peer is already connected`

But we where connected and synct. On my side he showed again not via his added dns in the config, but with his ip.

**Environment information:**
 - OS: Windows 10
 - RAM: 32GB
 - Cores: 6 Cores
 - Type: 8700K @5.1GHz
 - Browser Brave
 - HORNET version: Version 0.5.0-rc13

**Comment by Travetown** [comment]
The error described above -> (static) neighbors without a static IP address permanently losing the connection when changing the IP every day. The DNS entry in peering.json is not used.

**Comment by muXxer** [comment]
The "waiting" bug should be fixed with #650 

The other bug is that incoming connections are only shown by their IP, but not their DNS entry. I will investigate.

**Comment by muXxer** [comment]
Thx for your help!

Node alias should be correctly shown now with #650 
Please open a new ticket if still something goes wrong.
