### ISSUE TITLE
Comnet 0.5.0-rc13 not catching up at TPS > 600

### ISSUE THREAD

**Issue by TeeVeeEss** [iotaledger/hornet#615]
**Describe the bug**
The node is not catching up quick enough at TPS > 600 and stays unsynced at app.. 400 MS behind.

**To Reproduce**
- Have at least 1 good static peer
- Have a beefy node
- Start HORNET with comnet-config
- Wait for high TPS, at least 600
- Watch log/dashboard to check LMI/LSMI
- After a restart it seems going better for a while, but the gap between LMI and LSMI is not smaller.

**Expected behavior**
Even with high TPS stay synced.

**Environment information:**
 - OS: Arch Linux
 - RAM: 64 GB
 - Storage: 450 GB SSD
 - Cores: 8 Cores
 - Type: Baremetal
 - Browser: Chrome
 - HORNET version: v0.5.0-rc13-70d6851 (self compiled with cloned github repo, installed as service)

**Additional context**
See attached full journalctl log created with ```journalctl --no-pager --utc --no-hostname --since today -u hornet_standalone >comnet_not_catching_up.log```
[comnet_not_catching_up.log.gz](https://github.com/gohornet/hornet/files/5078687/comnet_not_catching_up.log.gz)

**Comment by muXxer** [comment]
That's weird. My small laptop is able to sync at 1000 TPS network speed within 30 minutes, and my snapshot was 270 MS behind

**Comment by TeeVeeEss** [comment]
The node is now more than 1000 MS behind, even after another restart:
```Status Not Synced
Uptime 00:16:18
LSMI/LMI: 740618 / 741623
Snapshot Index: 740418
Pruning Index: 739571
Version 0.5.0-rc13-70d6851
Request Queue Size: 7
Connected Neighbors: 2
Autopeering-ID: 45Bh1VXqUpS
```
Any more info of logs needed? Otherwise I will delete the db and start with a fresh snapshot...

**Comment by muXxer** [comment]
You can delete

**Comment by TeeVeeEss** [comment]
After a reset of my modem things went back to normal, syncing within 10 minutes from 600 MS behind. The portforwarding is very essential ;) So very probably no bug on the hornet side, therefor I will close the issue.
