### ISSUE TITLE
WarpSync eats the requests of milestone to solidify

### ISSUE THREAD

**Issue by muXxer** [iotaledger/hornet#618]
There seems to be something wrong in the WarpSync logic. 

After the "Can't solidify milestone" message, the requests are not added to the queue.
This shouldn't happen.

Another weird behavior is the "TargetUpdated" in this log.
https://ybin.me/p/2075b75ec20d4afc#stJyl4XBaT6yyDhvgGnzXtQUN4YAJ7Ln7SDaABPlKLA=

**Comment by GalRogozinski** [comment]
How was this fixed?

**Comment by muXxer** [comment]
see #637
