### ISSUE TITLE
comnet 0.5.0-rc13 - panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by QNODE-CA** [iotaledger/hornet#619]
**Describe the bug**

comnet node crashed with: 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x50c5f5]

**To Reproduce**

**Expected behavior**

node to continue functioning

**Environment information:**
 - OS:  Ubuntu 20.04 LST
 - RAM:  16 GB
 - Cores:  8  vCore
 - Type:  AMD TR
 - HORNET version: 70d6851 chrysalis - Release v0.5.0 rc13 (#613)

**Additional context**

[0.5.0-rc13 crash.log](https://github.com/gohornet/hornet/files/5086099/0.5.0-rc13.crash.log)

**Comment by muXxer** [comment]
you had MQTT activated? seems like a bug in the external lib.

**Comment by louaykamel** [comment]
@muXxer Unfortunately it was me doing Chronicle MQTT conn tests using Luca's node.

**Comment by muXxer** [comment]
Fixed in #641
