### ISSUE TITLE
Array of bundle.hash is reversed 

### ISSUE THREAD

**Issue by HarmvandenBrink** [iotaledger/hornet#63]
The array of the bundle you get back after a TX is 'upside down' (reversed), which means that the address where the tokens are send to normally is bundle[0].hash, but now it is the address of the remainder tokens.

In short: 
In IRI the bundle[0].hash is the address you want to send to.
In Hornet bundle[0].hash is the address your remaining tokens are sent to.

Example TX:

https://thetangle.org/bundle/LXYURKKVYA9VGWVYBQ9GRLOESGJISKVHAIZUFYCUWKCTXBYZKYPKRPJRCXJUEZYGTIOHJT9J9VJITIASC

In some cases you want to rely on the hash of the tx, not the address (since that would show the full amount on the address instead of only showing the amount that was sent).

**Comment by muXxer** [comment]
You shouldn't rely on the order at all, but on the addresses, right?

**Comment by muXxer** [comment]
attachToTangle API call

https://github.com/iotaledger/iri/blob/1527f771f6b788c0d0f4dda473bc698db214432e/src/main/java/com/iota/iri/service/API.java#L1325

https://github.com/gohornet/hornet/blob/fbb26776f0488b28b33f3275cb1d03f7b77b46ac/plugins/webapi/pow.go#L120

**Comment by Thoralf-M** [comment]
```go
	//reverse order so the first element is the tail tx
	if len(txs) > 1 {
		for i, j := 0, len(txs)-1; i < j; i, j = i+1, j-1 {
			txs[i], txs[j] = txs[j], txs[i]
		}
	}

	powedTxTrytes := transaction.MustTransactionsToTrytes(txs)
```
Don't know if there is a better way, but you could do it that way `if len(txs) > 1 {}` could also be removed
