### ISSUE TITLE
Pruning does not happen

### ISSUE THREAD

**Issue by ghost** [iotaledger/hornet#630]
**Describe the bug**
Although pruning is set in config.json the difference between `.latestMilestoneIndex` and `.milestoneStartIndex` and also the stored data keep increasing after having reached the pruning limit.
However, I see increased disk utilization.

**To Reproduce**
- set pruning limit in config.json:
```
    "pruning": {
      "enabled": true,
      "delay": 40000
    }
```
- start Hornet and keep it running for a few weeks
- calculate history length like this:
Make a `getNodeInfo` call and extract the `.latestMilestoneIndex` and `.milestoneStartIndex` fields.
 
**Expected behavior**
`.latestMilestoneIndex` minus `.milestoneStartIndex` should be 40000 or less.

**Actual behaviour:**
`.latestMilestoneIndex` minus `.milestoneStartIndex` keeps growing above 40000.

**Environment information:**
 - RAM: [e.g. 8 GB]
 - Cores: [e.g. 16 Cores]
 - HORNET version [e.g. 0.4.2]

**Additional context**
I could not find any history/pruning related info in the Hornet logs.

**Comment by muXxer** [comment]
was already fixed. pls update to 0.5.0
