### ISSUE TITLE
Concurrent map read and map write (Dashboard)

### ISSUE THREAD

**Issue by bztes** [iotaledger/hornet#634]
**Describe the bug**
My hornet node crashed after I opened the dashboard. The node was already online for ~16h where the error does not occur.
The error log says: "fatal error: concurrent map read and map write"
This happened around the same time where the coordinator was offline. Maybe there is a connection between the events.
As you can see in the log the restart & recovery worked without problems.

**To Reproduce**
- not deterministic

**Expected behavior**
Hornet shouldn't crash under any circumstances ;)

**Environment information:**
 - OS: Arch Linux
 - RAM: 12GB
 - Cores: 4 Cores
 - Type: Contabo VPS
 - Browser: Chrome (Linux)
 - HORNET Version: 0.5.0

[hornet-crash.log](https://github.com/gohornet/hornet/files/5101712/hornet-crash.log)

**Comment by Travetown** [comment]
The same bug with my Node.
Hetzner CPX31 Ubuntu 20.04.1 LTS
[hornet_log_mn.log](https://github.com/gohornet/hornet/files/5102330/hornet_log_mn.log)

**Comment by muXxer** [comment]
Fixed in #637
