### ISSUE TITLE
Hornet 0.5.0-rc2 - Spike in TPS every 8 to 9 minutes

### ISSUE THREAD

**Issue by QNODE-CA** [iotaledger/hornet#640]
Every 8-9 minutes my CX21 Hornet node on Mainnet registers a spike in TPS in dashboard.  Usually the spike is between 2000 and 4000 TPS.  Often this is enough to desync the node for a few seconds, but not always.

**To Reproduce**

autopeering is enabled (default), no other plugins enabled or disabled

**Environment information:**
 - OS:  Ubuntu 20.04 LTS
 - RAM:  4 GB
 - Cores:  2 vCores (Hetzner CX21 VPS)
 - HORNET version 0.5.0-rc2   af40f0e

**Additional context**
dashboard screenshots (taken a few minutes apart), last 4 days of log

![CX21 - TPS spikes](https://user-images.githubusercontent.com/10619487/91105090-04aed800-e624-11ea-8d50-22a08f3231f3.png)

![CX21 - TPS spikes 2](https://user-images.githubusercontent.com/10619487/91105099-08425f00-e624-11ea-9b54-bc7ceff85b15.png)

[cx21_hornet.zip](https://github.com/gohornet/hornet/files/5120605/cx21_hornet.zip)

**Comment by muXxer** [comment]
The node creates a snapshot, which is heavy if you enable the spent addresses. Disable them or increase the snapshot interval

**Comment by QNODE-CA** [comment]
wow, that was fast :)
