### ISSUE TITLE
When curling the node I recieve {"error": "Not Found"}

### ISSUE THREAD

**Issue by Tsangares** [iotaledger/hornet#642]
**Describe the bug**
Using Ubuntu 18, I followed the instructions from the github to install hornet, after installation it does not seem to work correctly. 

**To Reproduce**
Using `Ubuntu 18.04.3 LTS `.

I ran the following commands:

```
wget -qO - https://ppa.hornet.zone/pubkey.txt | sudo apt-key add -
sudo sh -c 'echo "deb http://ppa.hornet.zone stable main" >> /etc/apt/sources.list.d/hornet.list'
sudo apt update
sudo apt install hornet
```

Then before starting hornet, I generated a seed, and edited `/var/lib/hornet/config.json` to enable `network.autopeering.runAsEntryNode = True`. Before starting the node, I allowed all ports mentioned in the config through the firewall just in case. Then I started the node, took the public key, and added it to `network.autopeering.entryNodes` with the correct domain name and port. 

When I curl from the machine, `curl http://0.0.0.0:14265` I receive the response: `{"error":"Not found"}`. 

The logs mostly show the following:

```
Aug 26 23:41:46 marx hornet[19860]: 2020-08-26T23:41:46Z        INFO        Autopeering        autopeering/plugin.go:67        discovered: xxx.xxx.xxx.xxx:14xxx / XxCcXxCcXxCc
Aug 26 23:42:03 marx hornet[19860]: 2020-08-26T23:42:03Z        INFO        Autopeering        autopeering/plugin.go:67        discovered: xxx.xxx.xxx.xxx:14xxx / XxCcXxCcXxCc
Aug 26 23:42:03 marx hornet[19860]: 2020-08-26T23:42:03Z        INFO        Autopeering        autopeering/plugin.go:67        discovered: xxx.xxx.xxx.xxx:14xxx / XxCcXxCcXxCc
```

**Expected behavior**
When I curl the node I should be receiving the nodes information. 

**Environment information:**
 - OS: Ubuntu 18.04.3 LTS 
 - RAM: 1GB
 - Cores: 1
 - Type: VPS
 - HORNET version: 0.5.0

**Additional context**
Also the dashboard does not return anything. Nothing about the node seems to work but the logs do show autopeering...

**Comment by muXxer** [comment]
You run the node as an entrynode. This is not the fullnode mode, it only acts as an entry node for the network.

**Comment by Tsangares** [comment]
Maybe you could put, "When you run the node as an entrynode, it is not in fullnode mode, it only acts as an entry node for the network." Somewhere on the wiki page: "Tutorials: Hosting An Autopeering Entry Node"

From using IRI in the past, autopeering was not a thing until Nelson, so I assumed that autopeering was off my default. Only through making this mistake did I realized that entry node will mean not fullnode but it could be stated on the page.

**Comment by muXxer** [comment]
You are right! Thanks for the feedback.

Would you mind to do a PR to the wiki?
Since it's a community project, it would be cool if the community could help with the documentation, especially the hard to get parts.

**Comment by Tsangares** [comment]
Oh yeah I actually tried to, I wasn't sure if I could change the wiki
I will figure out how and submit a PR

**Comment by Tsangares** [comment]
Confirmed, I cannot edit the wiki page:
https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github

**Comment by Tsangares** [comment]
Okay, it does not really seem possible for me to PR the wiki. Ways to procees:

 - I could move the wiki into a documentation folder in the repo and make a PR
 - You could make the wiki publicly editable
 - You could make me a contributor and I will only make changes to the wiki
 - You could make the edit yourself

If I had more access to the wiki, I don't mind adding more documentation on node operation. I am active in the arch linux user repository so I could defiantly assist adding system support documentation in that regard.
Thank you for the help btw

**Comment by IoTMOD** [comment]
Hi @Tsangares,

how to contribute to our wiki is described here:
https://github.com/gohornet/hornet/wiki

I made an extra repo for it, which gets mirrored to the HORNET wiki repo. This way it's possible to do PRs against our wiki.
