### ISSUE TITLE
Panic in websocket connection

### ISSUE THREAD

**Issue by ghost** [iotaledger/hornet#646]
**Describe the bug**
[WebsocketPanic.txt](https://github.com/gohornet/hornet/files/5147304/WebsocketPanic.txt)
HORNET crashed while I tried to connect to the non-auth dahboard from my phone.

**Environment information:**
 - OS: Ubuntu 18.04.5 LTS
 - RAM: 8 GB
 - Cores: 4
 - Type: VPS
 - Browser: Safari mobile (iOS 12.4.8)
 - HORNET version 0.5.1

**Additional context**
The Logs. Panic is at 19:41:45.

**Comment by muXxer** [comment]
Fix in #650
