### ISSUE TITLE
Make the dashboard mobile friendly on small devices

### ISSUE THREAD

**Issue by FritzPeterAlbrecht** [iotaledger/hornet#65]
At the time the dashboard is made for bigger screens. I would like to see a mobile optimized version.

**Comment by yalamber** [comment]
Hello, I have created a pull request here https://github.com/gohornet/hornet/pull/435.

**Comment by muXxer** [comment]
release bounty to @yalamber

**Comment by muXxer** [comment]
release bounty to @yalamber

**Comment by yalamber** [comment]
HYRINTRCGYFXUMBTMDLIEEIWXNS9BWLGXEPKNHHHPBCTZGVIRO9JZKPVLTTJZJGCJG99BLCEZRRJZUAZDZGYQAH9JD

**Comment by luca-moser** [comment]
release bounty to @yalamber

**Comment by yalamber** [comment]
HYRINTRCGYFXUMBTMDLIEEIWXNS9BWLGXEPKNHHHPBCTZGVIRO9JZKPVLTTJZJGCJG99BLCEZRRJZUAZDZGYQAH9JD

**Comment by IoTMOD** [comment]
Thanks again for your contribution to HORNET!

**Comment by yalamber** [comment]
Thank you for the iotas :)
