### ISSUE TITLE
Hornet internal spammer had an error

### ISSUE THREAD

**Issue by GalRogozinski** [iotaledger/hornet#658]
**Describe the bug**

The hornet internal spammer reported an error `panic: runtime error: index out of range [0] with length 0`
The real error is masked. The error occured because of the following [line](https://github.com/iotaledger/hornet/blob/81fb8c3cf6a068972f8d37d9b46c0a09c634affe/pkg/tipselect/urts.go#L363). Notice that before it the real error `err` is returned but not handled.

I am not sure what is the root cause still, in case I will have it reproduced I shall comment.

**To Reproduce**
- Create a scenario where we have semi-lazy tips
- turn on internal spammer
- Cross fingers to reproduce

**Expected behavior**
1. Handle `err` on time
2. No error should happen

**Additional context**
```
panic: runtime error: index out of range [0] with length 0

goroutine 4016 [running]:
github.com/gohornet/hornet/pkg/tipselect.(*TipSelector).SelectSpammerTips(0xc00045c180, 0x8efe4cd62d6a700, 0x0, 0x0, 0x0, 0x27500e0, 0xc0003b8000)
        /home/galrogo/git/hornet/pkg/tipselect/urts.go:365 +0x470
github.com/gohornet/hornet/pkg/spammer.(*Spammer).DoSpam(0xc00045c200, 0x1, 0x324f800, 0xc003284720, 0x0, 0x0, 0x0, 0x0)
        /home/galrogo/git/hornet/pkg/spammer/spammer.go:81 +0xd7
github.com/gohornet/hornet/plugins/spammer.startSpammerWorkers.func2(0xc003284720)
        /home/galrogo/git/hornet/plugins/spammer/plugin.go:276 +0x745
github.com/iotaledger/hive.go/daemon.(*OrderedDaemon).runBackgroundWorker.func1(0xc002008140, 0xc0002e3580, 0xc000147a10)
        /home/galrogo/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200817231853-1c598e8496d7/daemon/daemon.go:118 +0x3b
created by github.com/iotaledger/hive.go/daemon.(*OrderedDaemon).runBackgroundWorker
        /home/galrogo/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200817231853-1c598e8496d7/daemon/daemon.go:117 +0x117
```

**Comment by muXxer** [comment]
fixed in #657
