### ISSUE TITLE
Remote Nmap on ZMQ 5556 port: node crashes

### ISSUE THREAD

**Issue by ghost** [iotaledger/hornet#66]
After the upgrade to 0.2.7, i activated the node and in few minutes it was SYNCED again.

From my home Linux PC i remotely tested the 5556 port of my node using nmap: 
`nmap my-node.com -p 5556` 

Nmap shows the port OPEN but, when i checked the node status, it was crashed.

![image](https://user-images.githubusercontent.com/10340922/71034751-63799480-211a-11ea-9352-f05d5cb525bb.png)

If you check the date / time, you see these two actions are related:

![image](https://user-images.githubusercontent.com/10340922/71033997-b3575c00-2118-11ea-8c38-6301eb6a20f5.png)

**Environment information:**
 - OS: Linux Ubuntu 16.04
 - RAM: 16 GB
 - Cores: 6 Cores
 - Type: VPS Contabo
 - HORNET version 0.2.7

**Comment by IoTMOD** [comment]
Related to #7
