### ISSUE TITLE
Create a metric for the built in spammer on the dashboard

### ISSUE THREAD

**Issue by GalRogozinski** [iotaledger/hornet#672]
**Is your feature request related to a problem? Please describe.**

CTPS is the defacto metric we use to determine the health of the tangle, but it is not the optimal one. This is because it measures how many of the total transactions have been confirmed, while users care about having their honest transactions confirmed.
For a simple example consider someone who starts spamming semi-lazy or lazy transactions, creating subtangles that have less chances of getting confirmed or fully confirmed. This will make the CTPS metric drop, although honest users emitting non-lazy transactions will still have chances close to 100% getting confirmed.

**Describe the solution you'd like**
Hornet has a built in spammer and a dashboard. I want to add a metric that tracks the built in spammer when it creates honest spam (non-lazy and non semi-lazy spam). This should better reflect the confirmation rate actual users of the network experience when they interact with the network.

**Describe alternatives you've considered**
The solution still doesn't mimic entirely an honest user because it uses a built in spammer that has very small latency that bypasses the API. Maybe a better solution is to track the confirmation rate of an external spammer?

However, I am not sure it matters that much... Also the main motivation to add the metric tot he dashboard is to tell the world that there are other metrics to look at besides CTPS.

**Additional context**
When I first joined IF there was a consensus that CTPS was a flawed metric. It seems that over time people forgot this.
With the addition of white-flag the flaws of CTPS got masked, but not completely resolved.
I shared internally a document that shows that there are conditions where we can get total CTPS and honest user's CTPS to diverge. The attacks, however, require significant hash power.

**Comment by luca-moser** [comment]
Sounds like a good feature to be implemented by an external tool tracking network metrics. We will close this for now but maybe revisit later :)
