### ISSUE TITLE
Don't solidify subtangles that are below max depth

### ISSUE THREAD

**Issue by GalRogozinski** [iotaledger/hornet#673]
**Is your feature request related to a problem? Please describe.**
If someone creates a huge non-solid subtangle and then emits a solidifying transaction that is below max depth, I/O resources are being spent solidifying it. Also the solidification status may affect other layers of Hornet (like the gossip layer).

**Describe the solution you'd like**
Don't solidify subtangles that are below max depth, unless they are approved by a milestone of course.

**Comment by muXxer** [comment]
We won't add this additional check in the solidification.
For gossip see #715
