### ISSUE TITLE
Add UTXO Storage layer

### ISSUE THREAD

**Issue by alexsporn** [iotaledger/hornet#677]
### Storage

All the underlying models are non mutable. All the fields are defined on creation.
We should only add these to the storage on whiteflag-confirmation to avoid having unconfirmed deposits in the storage

1. Deposits
    - Key: TransactionID[32]+OutputIndex[2]   (TransactionID from where the funds come)
    - Value:
        * MessageID
        * Address[32]
        * Amount (To avoid having to look up the original Deposit)

2. Unspent Deposits per Address (for current LSMI)
    - Key: Address[32]+TransactionID[32]+OutputIndex[2]   (TransactionID from where the funds come)
    - Value:
        * Empty

3. Spent Deposits per Address
    - Key: Address[32]+TransactionID[32]+OutputIndex[2]   (TransactionID from where the funds come)
    - Value:
        * Spent with TargetTransactionID (TransactionID to where the funds go)
        * Spent confirmed at MilestoneIndex

4. Ledger Diffs per MilestoneIndex
    - Key: MilestoneIndex[4]
    - Value:
        * NewDeposits: List<Address[32]+TransactionID[32]+OutputIndex[2]>
        * SpentDeposits: List<Address[32]+TransactionID[32]+OutputIndex[2]>

### What to do do to verify a new spent
- Take TransactionID and OutputIndex.
- Lookup Deposit from `1. Deposits` using the TransactionID+OutputIndex
- Take the Address of the Deposit and then look up in  `2. Unspent Deposits per Address`

### How to prune a given MilestoneIndex?
- Lookup Milestone from `4. Ledger Diffs per MilestoneIndex`
- Iterate all SpentDeposits from `3. Spent Deposits per Address`
    * Remove each deposit from `1. Deposits`
    * Remove each deposit from `3. Spent Deposits per Address`
- Remove Milestone from `4. Ledger Diffs per MilestoneIndex`

### How to create a Snapshot for a given MilestoneIndex?
- Save current unspent Deposits for the current SolidMilestoneIndex from `2. Unspent Deposits per Address`
    * Iterate over all keys, then lookup each deposit from `1. Deposits`
        * Stream all deposits to the snapshot file
- Create a diff to each previous index until the SnapshotIndex
    * Iterate back each MilestoneIndex until the SnapshotIndex and load `4. Ledger Diffs per MilestoneIndex` for each Index.       
         * Iterate the `NewDeposits` from the diff
              * Lookup each deposit from `1. Deposits` and stream the deposit to the snapshot file
         * Iterate the `SpentDeposits` from the diff
              * Lookup each deposit from `1. Deposits` and stream the deposit to the snapshot file

**Comment by luca-moser** [comment]
> Storage

For any partition containing addresses I am not sure whether we can assume them to be always 32 bytes long. I assume we will end up having different stores for `* per Address` stores.

> How to create a Snapshot for a given MilestoneIndex?

For snapshotting a given milestone index it should be enough if you add the milestone index as a value to `Deposits` and while you're iterating over `Unspent Deposits per Address`, you only stream `Deposits` of which the milestone index is `<=` the snapshot milestone index. I don't actually understand the diffing after step 1. since the snapshot file is only supposed to contain UTXOs. Can you elaborate why this has to be done? From my PoV, if a UTXO is absent for a new bootstrapping node it is implicitly spent already.

**Comment by alexsporn** [comment]
> > Storage
> 
> For any partition containing addresses I am not sure whether we can assume them to be always 32 bytes long. I assume we will end up having different stores for `* per Address` stores.
> 

Yes, that was our idea too. Would be 49 bytes for WOTS for example.

> > How to create a Snapshot for a given MilestoneIndex?
> 
> For snapshotting a given milestone index it should be enough if you add the milestone index as a value to `Deposits` and while you're iterating over `Unspent Deposits per Address`, you only stream `Deposits` of which the milestone index is `<=` the snapshot milestone index. I don't actually understand the diffing after step 1. since the snapshot file is only supposed to contain UTXOs. Can you elaborate why this has to be done? From my PoV, if a UTXO is absent for a new bootstrapping node it is implicitly spent already.

So, the reasoning behind this is to not need to load all unspent deposits into memory. When we are snapshotting, we are always at least LSMI-50, so that we can properly create SEPs.

So, our internal unspent deposits list will be at LSMI. This one we can easily stream into a file without needing to load everything into memory.

What we can then do is also stream the diffs for each LSMI-1, LSMI-2, ...,  LSMI-50 into the file. This way when the node loads the snapshot, it can import the LSMI snapshot and then apply alls this diffs in the database.
