### ISSUE TITLE
Bootstrapping Coo node can deadlock

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/hornet#686]
Daemons are not started in any particular order when all the plugins' "run()" functions have been called. If the timing is right, the Coordinator plugin will do a `Bootstrap()` while `TangleProcessor[ReceiveTx]` is not started yet, leading it to deadlock because it waits on the msgs/txs of the first milestone to be processed.

I had a quick look at master and didn't see anything in particular circumventing this bug, it occurs for me sometimes under my feat/libp2p branch though. Might be worth checking out whether master runs into the same problem.

**Comment by muXxer** [comment]
I already fixed that in pt2 branch.
See 26e22896223f1c175abf9852852778ea801b4b86

**Comment by luca-moser** [comment]
Maybe port it to master as well then?

**Comment by muXxer** [comment]
We can do this, but it will only happen at coo node startup though.
Not sure if worth the hassle :) What do you say?

**Comment by luca-moser** [comment]
It is a bad bug and should be fixed in master as well. pt2 is not going to be merged any time soon.

**Comment by muXxer** [comment]
It never happened to me because the mainnet will take quite some time to do the PoW with MWM14 for the milestone with all its transactions. In that time the TangleProcessor was started already.
But I can backport it.

**Comment by luca-moser** [comment]
I am reopening issue. We can close it when it actually has been fixed in master.

**Comment by muXxer** [comment]
Fixed with #690 
Waiting for final release before closing this issue.
