### ISSUE TITLE
Hornet stops solidifying after a manual soldiofier-event is triggered. Then "Graceful Shutdown" is unable to completee

### ISSUE THREAD

**Issue by frohal** [iotaledger/hornet#688]
**Describe the bug**
It logs that milestonedata is already in DG, and triggeres a 'Manual solidifungt'-process. This solidifies one milestone, then no more milestones are solidified.
In this state, it's also impossible to shutdown the node gracefully, as a few processes is keeping the nhe node up.
The attached stacktrace shows what's running in the state where gracefuls shutdown would have expired.

**To Reproduce**
Not sure, running on an older computer, 2 CPU 8 Gig ram and a 'normal' spinning disc.  

**Expected behavior**

**Environment information:**
 Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
 - HORNET 0.5.3

**Additional context**
Add any other context about the problem here [e.g. HORNET logs, errors, screenshots]
[50c1.log](https://github.com/gohornet/hornet/files/5361655/50c1.log)

**Comment by muXxer** [comment]
After discussions in discord we found out that you introduced a deadlock with your own code changes ;)
Issue closed.
