### ISSUE TITLE
Do not deliver broken snapshots.

### ISSUE THREAD

**Issue by c-mnd** [iotaledger/hornet#691]
Setting up a new node, I might receive 8 Mio instead of 14 Mio spent addresses.
You are working really hard to make spent addresses obsolete, but while they still exist, this should be done correctly.

**Comment by muXxer** [comment]
It's a broken snapshot of a community member. He didn't change the snapshot after we recognized the problem, so we will remove his snapshot source...

**Comment by c-mnd** [comment]
I know. A valuable member! But for other reasons. That's why I made an issue here.

**Comment by nuriel77** [comment]
> He didn't change the snapshot after we recognized the problem,

So, what was the problem and how does it happen, and how to prevent this bug from happening in the future?
I was not asked by @muXxer to change the snapshot, until I see this.
Changing it now as we speak.
But feel free to remove the download link, I just provided this to help because I was asked to.

**Comment by muXxer** [comment]
I can't see any way how this can happen, except you started your database with empty spent addresses long time ago with an old version of HORNET before we had checks in the database layer. :shrug: 
You could download the latest snapshot from IF, and start with that one and a fresh database. This way you can still provide a working snapshot from your side and I don't have to remove your snapshot source @nuriel77 :+1:

**Comment by nuriel77** [comment]
@muXxer done.
