### ISSUE TITLE
./create_snapshot_alphanet.sh and ./run_coordinator_alphanet_bootstrap.sh fail

### ISSUE THREAD

**Issue by jmcanterafonseca-iota** [iotaledger/hornet#692]
**Describe the bug**
Scripts for running Chrysalis Phase 2 Hornet are failing

**To Reproduce**
run ./create_snapshot_alphanet.sh  or ./run_coordinator_alphanet_bootstrap.sh
```
pkg/model/coordinator/coordinator.go:228:38: not enough arguments in call to createMilestone
	have (ed25519.PrivateKey, milestone.Index, *hornet.MessageID, *hornet.MessageID, [64]byte, *"github.com/gohornet/hornet/pkg/pow".Handler)
	want (ed25519.PrivateKey, milestone.Index, *hornet.MessageID, *hornet.MessageID, int, [64]byte, *"github.com/gohornet/hornet/pkg/pow".Handler)
````

**Expected behavior**
No error.

**Comment by muXxer** [comment]
We are not done yet doing changes for the new concept of rotating keys for the coordinator.
Take an older commit if you want to run a node. 88f53fe16dca5d163658a0d5524bf972e12d0c37
