### ISSUE TITLE
ZMQ lib is broken

### ISSUE THREAD

**Issue by muXxer** [iotaledger/hornet#7]
Since the maintainer of the ZMQ lib is busy, we have to fix that on our own and create a PR to the lib.

There are several problems:
- Version negotiation panics if not 64bytes long (this is wrong regarding the ZMQ spec)
- There should be no panics in the lib at all

**Comment by ThatsNotMyCode** [comment]
FYI: I made an issue on the lib for it https://github.com/go-zeromq/zmq4/issues/56

**Comment by ghost** [comment]
I agree with HIGH-PRIORITY tag

**Comment by ThatsNotMyCode** [comment]
Yes, this is the reason I can't switch to Hornet yet.
edit: now MQTT plugin is good alternative.

**Comment by muXxer** [comment]
Solved! They fixed the ZMQ lib
