### ISSUE TITLE
extend getNodeInfo with sync status

### ISSUE THREAD

**Issue by GuidAnce-git** [iotaledger/hornet#70]
Extension of the API getNodeInfo with the status whether the node is synced, for an easier monitoring of the nodes.
Something like "status": "synced" or "status":"desynced"

**Comment by IoTMOD** [comment]
Thanks for your feature request.
Why is it not possible in this case to compare the LMI with the LSMI to check if HORNET is synced or not?

**Comment by GuidAnce-git** [comment]
I've thought about this before, but it requires that the monitoring software supports calculations for status monitoring. 
For almost every monitoring software it is very easy to send a get/post and check the response against a keyword. In addition there are no possibilities to do calculations with cloud based monitoring tools (e.g. statuscake.com). Thus, node monitoring would only be possible with local adaptable monitoring tools (nagios, prtg, etc.).

**Comment by muXxer** [comment]
What about
```json
"isSynced": true,
```
