### ISSUE TITLE
Milestone gets updated even though it shouldn't

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/hornet#774]
Let a node sync up from a full snapshot it then created following panic:
https://ybin.me/p/415c646a3197a512#TKnvNBn6zo5n/Tw9VpISHc0gjfHwh5rhDppY0OwtNJk=

**Comment by muXxer** [comment]
This never happened again right @luca-moser ?

**Comment by luca-moser** [comment]
Didn't see that anymore. I'll close the issue.
