### ISSUE TITLE
Use Blake2b-256 to compute the milestone inclusion merkle root

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/hornet#779]
We're currently using Blake2b-512 as by the old version of the RFC: https://github.com/iotaledger/protocol-rfcs/blob/milestone-merkle-validation-chrysalis-pt-2/text/0012-milestone-merkle-validation/0012-milestone-merkle-validation.md. This has now been switched to Blake2b-256.

In `white_flag.go` we have to change to only take 32 bytes after the merkle root computation. `iota.go` also needs to be updated as the merkle root is also currently 64 bytes there.

We should probably get rid of the selection of the wanted hash function for the merkle root computation.

**Comment by muXxer** [comment]
I'm fine with hardcoding the used hash function.

**Comment by alexsporn** [comment]
Done with #780
