### ISSUE TITLE
Bag

### ISSUE THREAD

**Issue by kirillseba** [iotaledger/hornet#795]
**Describe the bug**

**To Reproduce**
- Go to ...
- Edit config to ...
- See error

**Expected behavior**

**Environment information:**
 - OS: [e.g. Ubuntu 18.04]
 - RAM: [e.g. 4 GB]
 - Cores: [e.g. 4 Cores]
 - Type: [e.g. Raspberry Pi 3B+, VPS, ...]
 - Browser [e.g. chrome, safari] (e.g. for HORNET Dashboard issues)
 - HORNET version [e.g. 0.2.1]

**Additional context**
Add any other context about the problem here [e.g. HORNET logs, errors, screenshots]

**Comment by muXxer** [comment]
Heavy bags, or just bags?
