### ISSUE TITLE
MQTT broker got stuck

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/hornet#816]
On testnet a Hornet node stopped publishing messages. Looking into the pprof goroutine stack trace, one can see that `WriterPacket` deadlocked.

Full Stack trace: https://ybin.me/p/d2d93dc9688ca457#AMLM/9cXYIEutRoNX7J++q7m+eZWUH8lOrY/utlbewo=
Relevant:  https://ybin.me/p/759eeb38381da71d#bUz1WTy+UdZyaZxQt3zKcHkRhAiuPKTIWKARg2pZ2tI=

**Comment by muXxer** [comment]
Fixed with #869
