### ISSUE TITLE
Allow the Bech32 prefix to be configured

### ISSUE THREAD

**Issue by obany** [iotaledger/hornet#824]
If we want to run a private tangle with a different bech32 hrp this is not currently possible as some code will only look for mainnet or testnet prefixes.

https://github.com/gohornet/hornet/blob/a153e109ca6517e14d8153a1e72886f025667f28/plugins/mqtt/util.go#L182-L187

Adding the bech32 hrp to the configuration for the node removes the requirement for the node to know which network it is running on.

In addition add the hrp from the config to the NodeStatus message to the dashboard, so the explorer knows which prefix to use.

e.g.

```go
Bech32Hrp              string          `json:"bech32_hrp"`
```

**Comment by alexsporn** [comment]
The problem I see here is that it can be misconfigured. Yo can run mainnet but use a testnet prefix in the config

**Comment by obany** [comment]
Isn't that true of any configuration option, if you configure a node incorrectly it won't work the way you expect. It doesn't affect any data or storage, just API lookups.

**Comment by alexsporn** [comment]
See #829
