### ISSUE TITLE
Potential memory leak not visible in go memory profile

### ISSUE THREAD

**Issue by adriankirchner** [iotaledger/hornet#825]
**Describe the bug**
Hornet is running for 1 day and 10 hours (started with an empty db). Monitoring indicates a constantly increasing memory usage. htop shows memory is used mostly by hornet. The go memory profile (`go tool pprof --pdf http://localhost:6060/debug/pprof/heap > memory_profile.pdf`) does not reflect this consumption.

**To Reproduce**
- Start hornet with empty db and some synced peers
- wait and observe memory usage

**Expected behavior**
Idk what to expect from this early testing stage but the memory consumption reported by system/monitoring not matching the go memory profile seems odd. Hornet dashboard reports 150 MB memory usage vs. 1.5 GB reported by htop.

**Environment information:**
 - OS: Ubuntu 20.04
 - RAM: 2 GB +  2 GB swap
 - Cores: 2
 - Type: Hetzner CPX11
 - HORNET version: alpha/chrysalis (a153e109ca6517e14d8153a1e72886f025667f28) compiled with go1.15.6
 - HORNET config: https://github.com/gohornet/hornet/blob/a153e109ca6517e14d8153a1e72886f025667f28/config_chrysalis_testnet.json

**Additional context**
[memory_profile.pdf](https://github.com/gohornet/hornet/files/5823668/memory_profile.pdf)

![Bildschirmfoto 2021-01-16 um 02 39 00](https://user-images.githubusercontent.com/149483/104794145-0aa97f00-57a6-11eb-8117-bf7cae079790.png)
![Bildschirmfoto 2021-01-16 um 02 37 50](https://user-images.githubusercontent.com/149483/104794147-1006c980-57a6-11eb-957c-2d2e990ced7b.png)
![Bildschirmfoto 2021-01-16 um 02 36 13](https://user-images.githubusercontent.com/149483/104794153-15fcaa80-57a6-11eb-94e3-063a3c13a5bf.png)

**Comment by muXxer** [comment]
I guess you mix the memory that is claimed by go, with the memory that is reserved for the process in the OS. If the OS would run out of memory, it can free the reserved memory from the process again, but as long as you have enough memory, there is no need for the kernel to free it. This is only my understanding of it and I could be wrong here. 

You could check that by creating another process that consumes remaining OS memory, so that the kernel is forced to free some memory from running processes.

If it is not the case, maybe some C code in a lib has a leak, but I don't see how Go should magically use much more space than it reports.

**Comment by adriankirchner** [comment]
you maybe right. Unfortunately I messed up my test with `memtester` and hornet got killed. I disabled swap and will test again with memtester in a couple of hours / tomorrow.

**Comment by adriankirchner** [comment]
Test today: 
- Hornet claimed to use 430 MB memory (dashboard)
- `htop` attributed rss of 1209 MB to hornet process
- `free -m` :
```
              total        used        free      shared  buff/cache   available
Mem:           1939        1367          97           2         474         670
Swap:             0           0           0
```
- `memtester 1200M`:
```
[Sun Jan 17 20:56:43 2021] Out of memory: Killed process 148214 (hornet) total-vm:2495436kB, anon-rss:1213780kB, file-rss:884kB, shmem-rss:0kB, UID:0 pgtables:2692kB oom_score_adj:0
[Sun Jan 17 20:56:44 2021] oom_reaper: reaped process 148214 (hornet), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

> I guess you mix the memory that is claimed by go, with the memory that is reserved for the process in the OS

Not sure but wouldn't that be reflected in the _available_ metric of `free`?

I'll make another test tomorrow and generate the go profiler report beforehand

**Comment by centercirclesolutions** [comment]
You might try this method to clear memory cache. https://linuxconfig.org/clear-cache-on-linux and https://linuxconfig.org/how-to-monitor-ram-usage-on-linux. Hope this helps

**Comment by adriankirchner** [comment]
Hornet gets killed every 2-3 days by the oom reaper now that I disabled swap. That happens without me allocation arbitrary memory via `memtester`.

```
[Tue Jan 26 14:01:16 2021] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/hornet-alphanet.service,task=hornet,pid=335283,uid=0
[Tue Jan 26 14:01:16 2021] Out of memory: Killed process 335283 (hornet) total-vm:3027784kB, anon-rss:1684588kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:3868kB oom_score_adj:0
[Tue Jan 26 14:01:16 2021] oom_reaper: reaped process 335283 (hornet), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

That happens while dashboard is reporting 164 MB memory usage and the go memory profile looks like this: 
[memory_profile.pdf](https://github.com/gohornet/hornet/files/5874025/memory_profile.pdf)

Without hornet running the memory footprint looks like this:

```
              total        used        free      shared  buff/cache   available
Mem:           1939         188        1003           1         748        1600
Swap:             0           0           0
```

There is absolutely no reason for the oom reaper to kill hornet if it would consume 164 MB of memory only.
I'm puzzled that no one else is observing this behaviour. 

Executing `sudo sysctl vm.drop_caches=3` as suggested in the article linked by @centercirclesolutions does not affect this issue.
If I'm really the only one observing this, feel free to close this issue. Otherwise feel free to AMA. 

Edit: currently running 1de8b74683c2a4143531c31f0e34d0dbcb534443

**Comment by TobinskiGitHub** [comment]
Hi @adriankirchner on my system I can see the same. Have had this problem for three times in the past and see no reason why the node goes oom. We discussed this also on discord with @muXxer a few days ago.

**Comment by luca-moser** [comment]
I am actually seeing the same problem with the node who serves to generate the snapshots for testnet. That node has 4GB of memory but continuously gets killed and the process/container exists with status code 137.

Perhaps we should tune the PebbleDB settings, I see that we have a plethora of options set and I am not sure we really came to these values by proper testing (for example, the 1 GB cache seems arbitrary):
```
cache := pebbleDB.NewCache(1 << 30) // 1 GB
	defer cache.Unref()

	opts := &pebbleDB.Options{
		Cache:                       cache,
		DisableWAL:                  true,
		L0CompactionThreshold:       2,
		L0StopWritesThreshold:       1000,
		LBaseMaxBytes:               64 << 20, // 64 MB
		Levels:                      make([]pebbleDB.LevelOptions, 7),
		MaxConcurrentCompactions:    3,
		MaxOpenFiles:                16384,
		MemTableSize:                64 << 20,
		MemTableStopWritesThreshold: 4,
	}

	for i := 0; i < len(opts.Levels); i++ {
		l := &opts.Levels[i]
		l.BlockSize = 32 << 10       // 32 KB
		l.IndexBlockSize = 256 << 10 // 256 KB
		l.FilterPolicy = bloom.FilterPolicy(10)
		l.FilterType = pebbleDB.TableFilter
		if i > 0 {
			l.TargetFileSize = opts.Levels[i-1].TargetFileSize * 2
		}
		l.EnsureDefaults()
	}
	opts.Levels[6].FilterPolicy = nil
```

Additionally, lets see whether the new versions help with this problem since we did update dependencies.

**Comment by TobinskiGitHub** [comment]
Out of Memory at almost 5GB DB.

System is privat, intel XEON 32GB Host with VMWare ESXi. Hornet node runs in a ubuntu-vm. GoShimmer 0.3.5 is also running on this vm for 26 days, stable. Hornet crashed everytime at ~ 4-5 GB.

From https://github.com/gohornet/hornet
   6398e3e..bfd40ca  develop    -> origin/develop
Updating 6398e3e..bfd40ca

> Feb  8 19:10:03 ubuntu-server-eval hornet-alphanet[3266755]: req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, LSMI/LMI: 39146/39147, MPS (in/new/out): 00299/00029/00172, Tips (non-/semi-lazy): 149/0
Feb  8 19:10:04 ubuntu-server-eval hornet-alphanet[3266755]: 2021-02-08T19:10:04+01:00#011INFO#011P2P-Manager#011scheduled reconnect in 30.847646704s to <peer.ID 12*NxnMNY>
Feb  8 19:10:04 ubuntu-server-eval hornet-alphanet[3266755]: 2021-02-08T19:10:04+01:00#011WARN#011P2P-Manager#011error reconnect <peer.ID 12*NxnMNY>: context deadline exceeded
Feb  8 19:10:04 ubuntu-server-eval hornet-alphanet[3266755]: 2021-02-08T19:10:04+01:00#011INFO#011P2P-Manager#011reconnecting <peer.ID 12*q2Rg5X>
Feb  8 19:10:04 ubuntu-server-eval hornet-alphanet[3266755]: req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, LSMI/LMI: 39146/39147, MPS (in/new/out): 00299/00029/00172, Tips (non-/semi-lazy): 154/0
Feb  8 19:10:05 ubuntu-server-eval hornet-alphanet[3266755]: req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, LSMI/LMI: 39146/39147, MPS (in/new/out): 00299/00029/00172, Tips (non-/semi-lazy): 154/0
Feb  8 19:10:05 ubuntu-server-eval hornet-alphanet[3266755]: 2021-02-08T19:10:05+01:00#011INFO#011WarpSync#011Synchronizing to milestone 39148
Feb  8 19:10:06 ubuntu-server-eval hornet-alphanet[3266755]: 2021-02-08T19:10:06+01:00#011INFO#011P2P-Manager#011scheduled reconnect in 30.855407357s to <peer.ID 12*q2Rg5X>
Feb  8 19:10:06 ubuntu-server-eval hornet-alphanet[3266755]: 2021-02-08T19:10:06+01:00#011WARN#011P2P-Manager#011error reconnect <peer.ID 12*q2Rg5X>: context deadline exceeded
Feb  8 19:10:06 ubuntu-server-eval hornet-alphanet[3266755]: 2021-02-08T19:10:06+01:00#011INFO#011P2P-Manager#011reconnecting <peer.ID 12*NpD2Lu>
Feb  8 19:10:06 ubuntu-server-eval hornet-alphanet[3266755]: req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, LSMI/LMI: 39146/39147, MPS (in/new/out): 00299/00029/00172, Tips (non-/semi-lazy): 155/0
Feb  8 19:10:07 ubuntu-server-eval hornet-alphanet[3266755]: req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00011, LSMI/LMI: 39146/39147, MPS (in/new/out): 00299/00029/00172, Tips (non-/semi-lazy): 155/0
Feb  8 19:10:08 ubuntu-server-eval hornet-alphanet[3266755]: req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, LSMI/LMI: 39146/39147, MPS (in/new/out): 00299/00029/00172, Tips (non-/semi-lazy): 155/0
Feb  8 19:10:09 ubuntu-server-eval hornet-alphanet[3266755]: 2021-02-08T19:10:08+01:00#011INFO#011P2P-Manager#011scheduled reconnect in 30.50448998s to <peer.ID 12*NpD2Lu>
Feb  8 19:10:09 ubuntu-server-eval hornet-alphanet[3266755]: 2021-02-08T19:10:08+01:00#011WARN#011P2P-Manager#011error reconnect <peer.ID 12*NpD2Lu>: context deadline exceeded
Feb  8 19:10:09 ubuntu-server-eval hornet-alphanet[3266755]: 2021-02-08T19:10:08+01:00#011INFO#011P2P-Manager#011reconnecting <peer.ID 12*NQiVPT>
Feb  8 19:10:09 ubuntu-server-eval hornet-alphanet[3266755]: req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00000, LSMI/LMI: 39146/39147, MPS (in/new/out): 00299/00029/00172, Tips (non-/semi-lazy): 155/0
Feb  8 19:10:10 ubuntu-server-eval hornet-alphanet[3266755]: 2021-02-08T19:10:10+01:00#011INFO#011WarpSync#011Manually starting solidifier, as some milestones are already in the database
Feb  8 19:10:10 ubuntu-server-eval hornet-alphanet[3266755]: 2021-02-08T19:10:10+01:00#011INFO#011Tangle#011Run solidity check for Milestone (39147)...
Feb  8 19:10:10 ubuntu-server-eval hornet-alphanet[3266755]: req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00025, LSMI/LMI: 39146/39147, MPS (in/new/out): 00299/00029/00172, Tips (non-/semi-lazy): 155/0
Feb  8 19:13:06 ubuntu-server-eval kernel: [3176818.028723] [3266755]     0 3266755  1457937   742680 10006528   425082             0 hornet
Feb  8 19:13:06 ubuntu-server-eval kernel: [3176818.028739] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/hornet-alphanet.service,task=horne ,pid=3266755,uid=0
Feb  8 19:13:06 ubuntu-server-eval kernel: [3176818.028825] Out of memory: Killed process 3266755 (hornet) total-vm:5831748kB, anon-rss:2970720kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:9772kB oom_score_adj:0
Feb  8 19:13:06 ubuntu-server-eval kernel: [3176818.283791] oom_reaper: reaped process 3266755 (hornet), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
Feb  8 19:13:06 ubuntu-server-eval hornet-alphanet[3266755]: req(qu/pe/proc/lat): 00000/00000/00000/0000ms, reqQMs: 0, processor: 00028, LSMI/LMI: 39146/39147, MPS (in/new/out): 00299/00029/00172, Tips (non-/semi-lazy): 155/0

**Comment by muXxer** [comment]
I pushed a commit to the dev branch, which changes the pebbleDB settings to almost default like @luca-moser proposed.
Could you please try this version again and see if you still encounter these problems?
The latest code also allows to use another DB engine. So you could also try `--db.engine=bolt` if it still doesn't work with pebble.

**Comment by adriankirchner** [comment]
![screenshot](https://user-images.githubusercontent.com/149483/107704121-08f7ac00-6cbd-11eb-9833-0218d0d8e73f.png)
Using the new pebble default settings looks way better than before (commit a89774c in graph). Good job!
I'll check again in a couple of days and close this issue if the memory usage remains stable

**Comment by muXxer** [comment]
Thx for reporting back @adriankirchner .
I really appreciate the detailed reports on this problem from everyone here!
:heart:

**Comment by muXxer** [comment]
@adriankirchner can this be closed now?

**Comment by adriankirchner** [comment]
![Bildschirmfoto 2021-02-18 um 16 14 23](https://user-images.githubusercontent.com/149483/108377626-844ce680-7204-11eb-800b-4e2fcc505c50.png)
Yes, looking stable 👌
