### ISSUE TITLE
Dashboard authentication doesn't work

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/hornet#826]
**Describe the bug**

In the chrysalis pt 2 version of Hornet, the dashboard authentication doesn't work.

**To Reproduce**
- Run `hornet tools pwdhash`
- Change Hornet config
- Restart Hornet
- Try to access dashboard

**Expected behavior**
The username and password don't get accepted. The credentials field simply reopens.

**Environment information:**
 - Browser: Firefox(Windows and macOS), Safari (macOS)
 - HORNET version: a153e10

**Comment by muXxer** [comment]
Fixed with #827
