### ISSUE TITLE
Websocket and API show different connection status 

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/hornet#835]
**Describe the bug**
One of my neighbors shows up as connected on the dashboard, but the API call returns with connected: false.

**Environment information:**
 - HORNET version: 1de8b74

**Additional context**
Websocket response:
`{
      "identity": "p2p_identity",
      "alias": "Neighbor",
      "origin_addr": "/ip4/ip-address/tcp/15600",
      "connection_origin": 0,
      "protocol_version": 0,
      "bytes_read": 0,
      "bytes_written": 0,
      "heartbeat": null,
      "info": {
        "address": "p2p_identity",
        "addresses": [
          "/ip4/ip-address/tcp/15600"
        ],
        "alias": "Neighbor",
        "sentPackets": 0,
        "droppedSentPackets": 0,
        "connected": true,
        "relation": "known"
      },
      "connected": true`
API call response:
`{
  "data": {
    "id": "p2p_identity",
    "multiAddresses": [
      "/ip4/ip-address/tcp/15600"
    ],
    "alias": "Neighbor",
    "relation": "known",
    "connected": false,
    "gossipMetrics": {
      "newMessages": 0,
      "knownMessages": 0,
      "receivedMessages": 0,
      "receivedMessageRequests": 0,
      "receivedMilestoneRequests": 0,
      "receivedHeartbeats": 0,
      "sentMessages": 0,
      "sentMessageRequests": 0,
      "sentMilestoneRequests": 0,
      "sentHeartbeats": 0,
      "droppedPackets": 0
    }
  }
}
`

**Comment by muXxer** [comment]
Fixed with #837
