### ISSUE TITLE
Add missing heartbeat and gossip metrics to dashboard messages peer info

### ISSUE THREAD

**Issue by obany** [iotaledger/hornet#836]
The peer metrics feed for the dashboard is currently missing the heartbeat and the other gossip metrics from the info.

https://github.com/gohornet/hornet/blob/f33c38b3fb7abc4339bcab52198d90b843623f9b/plugins/dashboard/plugin.go#L338

![image](https://user-images.githubusercontent.com/5030334/105677198-dba0b500-5eeb-11eb-892b-767e4545b432.png)

**Comment by luca-moser** [comment]
Indeed, it is completely off to what it is supposed to look like. I'll adjust it to be equivalent to the REST API response.

**Comment by muXxer** [comment]
I also saw that yesterday because of another issue here. Also that there is two times the "connected" info. :)

**Comment by muXxer** [comment]
Fixed with #838
