### ISSUE TITLE
Show running version upon startup in logs

### ISSUE THREAD

**Issue by nuriel77** [iotaledger/hornet#85]
**Is your feature request related to a problem? Please describe.**
Add the running version on one of the first log lines.

**Comment by IoTMOD** [comment]
Hi @nuriel77,
we will address this feature request with the next release.
However the next release will take a while :slightly_smiling_face: 
Until then you can use `./hornet -v` or `./hornet --version` to get the version if you do not want to use the API.

**Comment by nuriel77** [comment]
@IoTMOD thanks ;)
