### ISSUE TITLE
Webbrowser spammer plugin

### ISSUE THREAD

**Issue by Sn00pyoo7** [iotaledger/hornet#885]
If i have in the config:

node:
`"enableProofOfWork": true`
`"enablePlugins"  "Spammer"`

spammer:
`"autostart": false`

and want to start the spammer in the browser, all is fine. 
But i if i want to disable the spammer again, that's not working, it is starting it again. 

System: ubuntu
Browser: ungoogled chrome

**Comment by no8ody** [comment]
The url `/api/plugins/spammer/?cmd=settings` is also always called even if the spammer is disabled via configuration. But I guess it is a dashboard problem...

**Comment by alexsporn** [comment]
> The url `/api/plugins/spammer/?cmd=settings` is also always called even if the spammer is disabled via configuration. But I guess it is a dashboard problem...

That is currently the way the dashboard checks for the spammer plugin. Will be refactored soon(tm)
