### ISSUE TITLE
Automatic update

### ISSUE THREAD

**Issue by ghost** [iotaledger/hornet#89]
As a lot of releases are flowing in this period and it's really important for everyone involved in the community testing to be always updated, i suggest to implement an auto-update strategy

**Comment by muXxer** [comment]
No need for something like this. Just use nuriels playbook or compile hornet from source and use git. Auto update for a crypto currency fullnode isn't the best idea for a secure network IMHO.

**Comment by ghost** [comment]
Maybe not a full process of update (with no control by the node hosting) but, at least, a local script which can be launched by the user to perform a "one-click" update without losing any configuration, would be good

**Comment by IoTMOD** [comment]
As the config will change a lot during development it's not the best idea to have such a "one-click" update right now.

**Comment by ghost** [comment]
Ok
