### ISSUE TITLE
Promote to Known / Add Peer does not clear error message

### ISSUE THREAD

**Issue by centercirclesolutions** [iotaledger/hornet#901]
**Describe the bug**
Error message from promote to known is not cleared in dialog.

**To Reproduce**
Clicked [Promote to known] on a existing unknown peer. Clicked on OK and received the error "Failed to promote peer forbidden"
Then copied the info and pasted into add peer dialog. The add peer dialog still had the Failed error message before I entered any info (attached screenshot)

![image](https://user-images.githubusercontent.com/44786846/108820079-83071b00-7570-11eb-9752-edab6f5b78c8.png)

**Comment by obany** [comment]
Fixed in the dashboard https://github.com/iotaledger/node-dashboard/commit/cdb7bc1fc3abb819d28d8ce70edfda6a28e29122

**Comment by muXxer** [comment]
Was fixed somewhere along the way :sweat_smile:
