### ISSUE TITLE
Fix "Milestone should never be updated"

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/hornet#929]
Andrea said that this occurs in both C2 and `wf/migration` versions of Hornet and of course it is crucial to fix this.

Log from a `wf/migration` node:
https://ybin.me/p/bccdd2fc72ca4771#pZ9YUDIe9QxH1KLvz8HlDkunhzy9gzwHzmwCbHXSSHg=

C2 node:
https://ybin.me/p/d4c6a3414f0c883f#vgHYaD9pTxIFxl92zBO7wTdRdkGDAfk3tyqzcjnIEKc=

**Comment by GalRogozinski** [comment]
Happened to me as well now

https://ybin.me/p/0a48b5539a1790ed#IWX/g2nyeqD7Zuf+byKQQjPSRe1O/EcIGI8FsUFYVN4=

**Comment by GalRogozinski** [comment]
Btw, I tried to recover by simply deleting the DB and syncing from snapshot genesis
Unfortunately, I got the error again :-(

**Comment by muXxer** [comment]
Guys I'm almost sure that it is because you have a node in your configuration that has an old database, and because you respawn the network, the milestones exist twice

**Comment by GalRogozinski** [comment]
It could be that yesterday, while tinkering with the testnet tool, that I have bootstrapped coo w.o nuking the rest of the network..
I can't be entirely sure though...

but then it should have failed on the first milestone no?
else coo transmitted indexes that were already in the db w.o a bootstrap

**Comment by muXxer** [comment]
Fixed in chrysalis with #943

**Comment by muXxer** [comment]
Fixed in legacy with #944
