### ISSUE TITLE
Error while solidifying 1286798

### ISSUE THREAD

**Issue by HarmvandenBrink** [iotaledger/hornet#95]
```
2019/12/23 14:03:03 [ INFO ] Tangle: Run solidity check for Milestone (1286798)...
2019/12/23 14:03:03 [ INFO ] Tangle: Solidifier finished (10): passed: true, tx: 26, collect: 273.76µs, total: 688.355µs, entryTx: 0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x99a032]

goroutine 406825 [running]:
sync.(*RWMutex).RLock(...)
        /usr/local/go/src/sync/rwmutex.go:48
github.com/gohornet/hornet/packages/syncutils.(*RWMutex).RLock(...)
        /__w/hornet/hornet/packages/syncutils/syncutils.go:15
github.com/gohornet/hornet/packages/model/tangle.(*Bundle).IsComplete(0x0, 0x0)
        /__w/hornet/hornet/packages/model/tangle/bundle.go:630 +0x32
github.com/gohornet/hornet/packages/model/tangle.(*Bundle).IsValid(0x0, 0xe97500)
```

YWWI9WKZ9999
2019/12/23 14:02:42 [ INFO ] Tangle: Run solidity check for Milestone (1286798)...
2019/12/23 14:02:42 [ INFO ] Tangle: Milestone couldn't be solidified! 1286798
reqQ: 00164, reqQMs: 1286819, processor: 00273, LSMI/LMI: 1286797/1286847, addrsMarked

> all my nodes stopped/crashes because of this

**Comment by tanglebay** [comment]
I had the same problem and 3 of 4 nodes crashed at milestone 1286798.
[hornet.log](https://github.com/gohornet/hornet/files/3995083/hornet.log)

**Comment by QNODE-CA** [comment]
none of my 3 hornet nodes crashed at 1286798, but one of them logged something interesting:
`2019/12/23 04:03:11 [ INFO ] Tangle: Invalid milestone detected! Err: Index (1286798) older than solid milestone (1286798), Hash: CGK9MENROXXZGLMGFVQJVNSWUFOJWKNZDSKLHQMVHRIADVDLZPEAOTOLUXBGCNOCOIPQOUBDQMMUA9999: invalid milestone`

attaching log from all nodes and matching 1286798
[hornet nodes and LMI 1286798.txt](https://github.com/gohornet/hornet/files/3996006/hornet.nodes.and.LMI.1286798.txt)
