### ISSUE TITLE
Possible to change the UID - permission denied

### ISSUE THREAD

**Issue by thezepter** [iotaledger/hornet#957]
Hello, i´m using a synology NAS, added a new user and want to change the UID and GID to 39999, but the **** DSM OS did not let me do that. (sorry for my bad english)
Unfortunately, this is also not possible via SSH. The change in /etc/passwd unfortunately also brings nothing. Synology stores the UID and GID in a special database :-(

Its possible to change the UID as a variable in the docker run command or something like that ? 

**error after docker run:**

`panic: open /app/config.json: permission denied

goroutine 1 [running]:
github.com/gohornet/hornet/plugins/cli.ParseConfig()
        /__w/hornet/hornet/plugins/cli/cli.go:42 +0x85
main.main()
        /__w/hornet/hornet/main.go:34 +0x3f`

Thanks !

**Comment by muXxer** [comment]
Fixed with #1007
