### ISSUE TITLE
Stuck at "Not Synced"

### ISSUE THREAD

**Issue by dnns92** [iotaledger/hornet#960]
**Describe the bug**
I followed this tutorial: https://medium.com/@dantherealm4n/the-ultimate-guide-to-pi-hornet-5ab706f4977d#a3bb to run the hornet node. When I'm running it now, it remains stuck at "Not Synced", the tangle explorer does not show any transactions, and the visualizer wont show anything at all. 

However, I have 4 synced neighbors. Does someone know how to debug this situation?

**Expected behavior**
It worked sometime on sunday showing all the transactions in the explorer and also showing transactions in the visualizer. This is the state I would like to go back to.

**Environment information:**
- Ubuntu 20.04 on a rpi 4 2gb
- Fresh installation 
- Ports forwarded from the router to the machine:
    - 14626 tcp
    - 14627 tcp
    - 15600 tcp
    - 15601 tcp  

journalctl -u hornet -e -f does not show anything useful, see appendix
[journal.txt](https://github.com/gohornet/hornet/files/6143960/journal.txt)
![dashboard](https://user-images.githubusercontent.com/39763670/111210055-10b4b400-85cd-11eb-8a89-f7b983502a93.PNG)
![explorer](https://user-images.githubusercontent.com/39763670/111210060-114d4a80-85cd-11eb-9dae-d62e116b56ed.PNG)
![viz](https://user-images.githubusercontent.com/39763670/111210062-11e5e100-85cd-11eb-8798-fe99b3d91cc1.PNG)

**Comment by hiraarzo** [comment]
facing same issue...anyone please help.

**Comment by muXxer** [comment]
sorry had no time yet to have a look at the old version problems.
@dnns92 it seems your neighbors don't have that history anymore, since you have 14 pending requests that can't get solidified.
If a restart doesn't work, delete the snapshots and database folder and start again.

**Comment by hiraarzo** [comment]
ohh thanks for the response. It's been almost 2 weeks. I am trying to
resolve the issue and have tried all possible solutions available by you.
actually on first time creation it was working properly but later its not i
tried creating new nodes too but it doesn't work.
If I can work with some new node or version or any other solution please
let me know. it's important.
Thanks.
