### ISSUE TITLE
Block milestone payloads in REST API

### ISSUE THREAD

**Issue by muXxer** [iotaledger/hornet#979]
The node shouldn't accept milestone payloads via REST API at all.

Also the gossip flow should be adjusted, so that we don't need to check the milestone signatures twice.
Peers that send milestone payloads with invalid signatures should be dropped. 
That's also the reason we should not accept milestone payloads via REST API, otherwise an attacker could eclipse the node by creating invalid milestone payloads that are sent to all peers.

**Comment by luca-moser** [comment]
> Peers that send milestone payloads with invalid signatures should be dropped.

Elaborate why this is necessary and not the same as peers gossipping txs with invalid signatures.

**Comment by GalRogozinski** [comment]
If you do it maybe add a secret config for testing that will allow sending milestones via the API

**Comment by muXxer** [comment]
After discussions with @Wollac and @luca-moser , we won't do any special cases or blocking of milestones. Neither in the API nor the gossip.
Gossip on solidification will be changed to not have special cases for milestones either.
Issue closed.
