### ISSUE TITLE
Rasp 4 installation through APT broken

### ISSUE THREAD

**Issue by AlterX76** [iotaledger/hornet#986]
**Describe the bug**
when following the installation on rasp4 using apt, executing **apt update** I get:
N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'http://ppa.hornet.zone stable InRelease' doesn't support architecture 'armhf'

**Comment by muXxer** [comment]
It's not broken, we just don't support 32bit.
Please install a 64 bit OS on your raspberry pi.
